knative-extensions/eventing-kafka-broker

CONTRIBUTING.md
DEVELOPMENT.md
INTERNALS.md
data-plane/README.md
test/README.md

- Add `INTERNALS.md` for documenting the overall internal architecture.
- Add `DEVELOPMENT.md` explaining the basic development cycle.
- Add `data-plane/README.md` explaining data-plane architecture and directory structure.
- Add `CONTRIBUTING.md` same as `eventing` with some custom links.

Add documentation: internals, contributing, development

---

DEVELOPMENT.md

Signed-off-by: Alfusainey Jallow <alf.jallow@gmail.com>
- Use `go env GOPATH` to retrieve the path to a  user's Go directory

Remove hardcoded GOPATH from developer docs.

---

data-plane/pom.xml

- Use release 2.0.0-milestone1 of cloudevents/sdk-java

Use release 2.0.0-milestone1 of cloudevents/sdk-java

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/broker/controller.go
control-plane/pkg/reconciler/broker/controller_test.go
control-plane/pkg/reconciler/broker/topic.go
control-plane/pkg/reconciler/broker/topic_test.go

Fix `sarama` issue: https://github.com/Shopify/sarama/issues/1565 (in our case is `ClusterAdmin`, we have the same error though)
- Create a new ClusterAdmin at each loop

Create a new ClusterAdmin at each loop

---

control-plane/config/201-controller-cluster-role-binding.yaml

While trying the integration with Serving components, the controller
was unable to resolve serving Services due to non-granted permissions.
This PR binds the `addressable-resolver` cluster role to the
`kafka-broker-controller` service account, so that we can resolve all
addressable service we have as `Trigger` subscriber.
- Bind addressable-resolver cluster role to `kafka-broker-controller` service account

Bind addressable-resolver cluster role to kafka-broker-controller SA

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/file/FileWatcherTest.java

The dispatcher might restart, and as long as
it doesn't receive filesystem updates it never reconciles
existing objects, this PR allow the dispatcher to reconcile
existing objects, if any when it starts.
- Read the mounted config map when start watching it.
- Add regression unit test

Read mounted config map when start watching it.

---

control-plane/pkg/reconciler/trigger/trigger.go

It's better to retry with a controlled backoff instead of relying on the reconciler queue.
- Retry on conflicts in Trigger finalizer

Retry on conflicts in Trigger finalizer

---

test/e2e-common.sh

If it's a release branch, we need to install the respective eventing release as we do in `eventing-contrib` here:
https://github.com/knative/eventing-contrib/blob/48505ce5b1e7f370b0b4afe526b739be8481967f/test/e2e-tests.sh#L81-L82.
- Install Eventing release if it's a release branch

Install Eventing release if it's a release branch

---

test/control-plane/library.sh

`KO_FLAGS` variable is used by the `release.sh` in `test-infra` to inject custom flags, so we need to use it.
Fixes #85  
- Use `KO_FLAGS` when run ko resolve

Use KO_FLAGS when run ko resolve

---

data-plane/docker/Dockerfile
data-plane/docker/test/Dockerfile

- Hide maven transfer progress, since it pollutes a lot the CI logs

Hide transfer progress

---

control-plane/pkg/reconciler/kafka/broker_class.go

Fixes #94
- Change broker class name from `kafka` to `Kafka`

Upper-case broker class name

---

hack/release.sh

[Nightly release](https://console.cloud.google.com/storage/browser/_details/knative-nightly/eventing-kafka-broker/latest/eventing-kafka-broker.yaml) contains duplicate entries because 
we run tests and build the release at the same time
producing the same artifact, so remove the artifact
before building the release.
- remove the artifact before building the release

Fix duplicate resources in nightly release

---

test/e2e/broker_event_trasformation_test.go
test/e2e/broker_trigger_test.go
test/e2e/conformance/control_plane_conformance_test.go
test/e2e/conformance/data_plane_conformance_test.go
test/pkg/testing/run.go

To reduce the introduction of new flaky tests (bugs), 
we can run the same e2e tests multiple times, so that 
we catch bugs as soon as possible.
- Run e2e tests multiple times

Run e2e tests multiple times

---

data-plane/config/100-config-kafka-broker-data-plane.yaml
data-plane/config/template/500-dispatcher.yaml
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Configurations.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java

Fixes #141
- 🎁 Now the webclient used by dispatcher can be configured using the config map `config-kafka-broker-data-plane`
- 🧽 Some reorg of config file loading (maybe needs another pass in future)
```release-note
Now you can configure the web client options https://vertx-web-site.github.io/docs/apidocs/io/vertx/ext/web/client/WebClientOptions.html modifying the config map `config-kafka-broker-data-plane`
```

Get WebClient config from config map

---

data-plane/config/100-config-kafka-broker-data-plane.yaml
data-plane/config/template/500-dispatcher.yaml
data-plane/config/template/500-receiver.yaml
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/BaseEnv.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Configurations.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/DispatcherEnv.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
data-plane/pom.xml
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/ReceiverEnv.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/ReceiverEnvTest.java

Fixes #150
- 🧽 Some reorg of various env retrievers between dispatcher and receiver
- 🎁 Fix #150 adding configuration for http server
```release-note
Now you can configure the web client options https://vertx-web-site.github.io/docs/apidocs/io/vertx/core/http/HttpServerOptions.html modifying the config map `config-kafka-broker-data-plane`
```

Configure Vert.x HTTP server through a config map

---

proto/hack/generate_proto

Related: https://github.com/knative-sandbox/eventing-kafka-broker/pull/154
- Disable SELinux when using protobuf compiler

Disable SELinux when using protobuf compiler

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/trigger/trigger.go

The PR https://github.com/knative-sandbox/eventing-kafka-broker/pull/156 raises an issue,
we don't update the Broker and Trigger status when there is a failure.
- Update Broker and Trigger status when there is a failure
```release-note
- 🐛 Fix bug 
Update Broker and Trigger status when there is a failure.
```

Update Broker and Trigger status when there is a failure

---

control-plane/pkg/reconciler/base/receiver_condition_set.go
control-plane/pkg/reconciler/base/reconciler.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/sink/kafka_sink_test.go
control-plane/pkg/reconciler/testing/objects_broker.go
control-plane/pkg/reconciler/testing/objects_sink.go

Part of https://github.com/knative-sandbox/eventing-kafka-broker/issues/160
Since we're splitting the installation of the control plane and the
data plane to allow installing the Broker or the KafkaSink, we need
to make sure that the respective data plane is running, so check
is at least one pod of the data plane is running and reflect that
in the status.
The check is performed using a lister so the information might be
stale, but this allows avoid performing an API call against the
API server.
- Check if data plane pods are running

Check if data plane pods are running

---

control-plane/config/sink/100-webhook-cluster-role.yaml
control-plane/config/sink/100-webhook-service-account.yaml
control-plane/config/sink/200-webhook-cluster-role-binding.yaml
control-plane/config/sink/500-webhook.yaml

The Webhook deployment doesn't become ready since the
service account doesn't exist.
This PR adds a service account `kafka-webhook-eventing`
and assign it to the webhook deployment.
The name has the suffix `-eventing` to distinguish it from
the `eventing-contrib` webhook which is called `kafka-webhook`,
so that users can use both without problems.
- Add Webhook RBAC configuration

Add Webhook RBAC configuration

---

test/e2e/conformance/data_plane_conformance_test.go

Try to address:
- #179
- #174
- #172
- #171
Use the specific WaitForPodRunning instead of WaitForResourceReady
- Use WaitForPodRunning instead of WaitForResourceReady

Use WaitForPodRunning instead of WaitForResourceReady

---

control-plane/config/500-controller.yaml
control-plane/config/sink/500-webhook.yaml

Fixes https://github.com/knative-sandbox/eventing-kafka-broker/issues/192
- https://github.com/knative/pkg/pull/1714
- Project pod name as env var in our deployments

Project pod name as env var in our deployments

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandler.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/IllegalResponseException.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandlerTest.java

Fixes #194 
When a sink returns a non-event and a non-empty response there is no signal that
the event is malformed we just discard it, now we log the error.
- Return a failed future when the response is a non-event and the response is non-empty.

Log error on malformed event in response

---

control-plane/pkg/reconciler/testing/objects_broker.go
control-plane/pkg/reconciler/trigger/trigger.go
control-plane/pkg/reconciler/trigger/trigger_test.go

This PR adds a check to verify that the Trigger we're reconciling
is associated with a Broker with the annotation
`eventing.knative.dev/broker.class` set to `Kafka`.
Fixes #211 
- Don't reconcile Triggers we don't own

Don't reconcile Triggers we don't own

---

.github/workflows/knative-java-test.yaml

It's different from https://github.com/knative-sandbox/eventing-kafka-broker/pull/199 since in this one we upload reports in two different actions independently with two different flags.
- Upload Codecov Java report

Upload Codecov Java report

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/ObjectsCreator.java

Produced via:
```shell
export FILES=( $(find . -type f -not -path './vendor/*' -not -path './third_party/*' -not -path './.git/*') )
misspell -w "${FILES[@]}"
```

[Automated] Fix misspellings

---

proto/hack/generate_proto
test/data-plane/library.sh

- Motivation: https://www.redhat.com/en/blog/be-careful-when-pulling-images-short-name
- Use registry URL to reference container images

Use registry URL to reference container images

---

test/e2e-common.sh

- Release failed :sob: : https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-sandbox-eventing-kafka-broker-auto-release/1311005786016583680
```
>> Install Knative Eventing from https://storage.googleapis.com/knative-releases/eventing/previous/v0.18.0/eventing.yaml
Error: unknown flag: --strict
```
- Remove strict flag

[release-0.18] Remove strict flag

---

test/e2e-common.sh

- Release failed :sob: : https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-sandbox-eventing-kafka-broker-auto-release/1311005786016583680
```
>> Install Knative Eventing from https://storage.googleapis.com/knative-releases/eventing/previous/v0.18.0/eventing.yaml
Error: unknown flag: --strict
```
- Remove strict flag

Remove strict flag

---

data-plane/core/pom.xml
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/MetricsOptionsProvider.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/metrics/MetricsOptionsProviderTest.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordOffsetStrategyFactory.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategyTest.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestHandler.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestHandlerTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/integration/ReceiverVerticleTest.java
data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java

This PR exposes the following metrics:
1. http_events_sent_total
2. http_requests_produce_total
3. http_requests_malformed_total
All of the above metrics are counters.
(1) is incremented when the dispatcher commits the offset to Kafka.
(2) is incremented when the receiver sends successfully the message to Kafka.
(3) is incremented when the receiver receives a malformed event.
Signed-off-by Pierangelo Di Pilato <pierangelodipilato@gmail.com>
Fixes #227
- Expose metrics defined by the spec in Prometheus format
```release-note
- 🎁 Add new feature
The receiver component exposes:
- http_requests_produce_total - Number of accepted produce requests (200-level responses)
- http_requests_malformed_total - Number of malformed produce requests (400-level responses)
The dispatcher …
```

Expose metrics defined by the spec in Prometheus format

---

control-plane/config/500-controller.yaml
control-plane/pkg/config/env_config.go
control-plane/pkg/config/env_config_test.go
control-plane/pkg/core/config/utils.go
control-plane/pkg/core/config/utils_test.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/testing/factory.go
control-plane/pkg/reconciler/testing/objects_broker.go
data-plane/config/template/500-dispatcher.yaml
go.mod
vendor/modules.txt

Part of #116
- Add Retry Config to EgressConfig during broker reconciler
```release-note
- 🧽 Update or clean up current behavior
The control plane sends retry configurations to the data plane.
```

Add Retry Config to EgressConfig during broker reconciliation

---

control-plane/config/sink/500-webhook.yaml

Fixes #256
- Adds 20 seconds initial delay for liveness probe 
**Release Note**. 
```release-note
```
**Docs**

🐛 add delay in liveness for webhook

---

data-plane/docker/generate_jdk.sh

Followup of #265, part of #267
- Removed jmods we probably don't need
* `java.compiler` contains the compiler types. It's brought in by Guava and Vert.x CLI feature. we don't use the Vert.x Cli feature, so we don't need this

Removed `java.compiler` from used jmods

---

control-plane/config/500-controller.yaml
data-plane/config/sink/100-config-kafka-sink-data-plane.yaml
data-plane/config/sink/template/500-receiver.yaml

The `config-logging` volume mount isn't necessary.
Fixes #287 
- Remove config-logging volume and add server config for the sink
```release-note
- 🧽 Update or clean up current behavior
Remove config-logging volume from the controller
```

Remove config-logging volume and add server config for the sink

---

data-plane/config/sink/template/500-receiver.yaml
data-plane/config/template/500-dispatcher.yaml
data-plane/config/template/500-receiver.yaml
data-plane/docker/Dockerfile
test/data-plane/library.sh

This PR reduces the container image's sizes from `187MB` to `90MB +- 1MB`.
I worked with the [distroless community](https://github.com/GoogleContainerTools/distroless) to build non-root Java images,
the base image contains only system libraries (`glibc`, `zlib`, etc) and 
it runs as non-root, uid: `65532`.
- Base image size: ~30MB.
- Jar and the custom Java environment size: ~60MB.
Layers:
```
sha256:3041eb8028850a81494bb10b0843ae7a0822578bba3901b90dc63557f9437e9d   2 minutes ago       /bin/sh -c #(nop)  ENV PATH=/app/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin   0B                  
sha256:4ff88c0b75a38046f0c99c15333b31dd35de4b69328c981e368d2a92ded5cc20   2 minutes ago       /bin/sh -c #(nop) WORKDIR /app …
```

Reduce container images size

---

test/pkg/config/100-config-logging.yaml

There are a lot of log lines coming from Kafka clients, that
are unnecessary. This PR sets the logging level for our
loggers to `DEBUG` and keep all others to `INFO`.
- Change logging during e2e tests

Change logging during e2e tests

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Shutdown.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/utils/ShutdownTest.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java

- Gracefully clean up resources on shutdown

Gracefully clean up resources on shutdown

---

test/pkg/config/sacura/101-broker.yaml

If a Kafka Broker crashes for whatever reason we use ephemeral
storage so the messages are lost, increasing the replication
factor to 3 reduces the probability of losing events.
- Custom Broker config for sacura job
/area test

Custom Broker config for sacura job

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerMessageHandler.java

Fixes #371
- `keyValue` converts the value using an internal jackson object mapper. Because the contract may be pretty large, this operation becomes very expensive, eventually leading to thread blocked issue.

Fix thread blocked issue

---

hack/release.sh

Fixes #286
The solution diverged from the original issue, see issue discussion.
- Release `eventing-kafka.yaml` with all components in it
```release-note
`eventing-kafka.yaml` can be used to install Broker and KafkaSink.
```

Release eventing-kafka.yaml with all components in it

---

data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestMapper.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestMapperTest.java

Fixes #328
- Now we create one producer per config

Create one producer per properties in receiver

---

test/e2e-tests.sh
test/e2e/sacura_test.go

Fixes #350
This PR allows us to get individual test report output for the Sacura test,
so better test infra integration.
- Check Sacura Job status in a Go test

Check Sacura Job status in a Go test

---

test/data-plane/library.sh

We get a lot of connection reset errors during maven builds, like
```
[ERROR] Failed to execute goal on project receiver: Could not resolve dependencies for project dev.knative.eventing.kafka.broker:receiver:jar:1.0-SNAPSHOT: Failed to collect dependencies at io.vertx:vertx-web-client:jar:4.0.0.CR1: Failed to read artifact descriptor for io.vertx:vertx-web-client:jar:4.0.0.CR1: Could not transfer artifact io.vertx:vertx-web-client:pom:4.0.0.CR1 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/io/vertx/vertx-web-client/4.0.0.CR1/vertx-web-client-4.0.0.CR1.pom: Connection reset -> [Help 1]
```
and this makes our test grid red and it's difficult to see what's actually failing.
- Retry executing DP unit tests to avoid conn reset …

Retry executing DP builds to avoid conn reset errors

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticleTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/ConsumerVerticleFactoryMock.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/ReceiverVerticle.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/ReceiverVerticleTest.java
data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java

Sharing a `WebClient` across multiple verticles is discouraged by
Vertx, see https://vertx.io/docs/vertx-core/java/#_httpclient_usage.
That section talks about the HTTP Client, the `WebClient` isn't different.
> When used in a Verticle, the Verticle should use its own client instance.
Main changes are around when objects are built and in which Vertx context.
- Dispatcher non-blocking
- Receiver non-blocking
```release-note
- :broom: Update or clean up current behavior
The data plane is completely non-blocking.
```
/kind enhancement

Non-blocking data plane components

---

.github/workflows/OWNERS
control-plane/OWNERS
data-plane/OWNERS
test/OWNERS

This PR adds some OWNERS files telling to Prow to add labels
to PRs based on updated directories.
- Automatically add area label to PRs
```release-note
NONE
```

Automatically add area label to PRs

---

control-plane/pkg/reconciler/base/reconciler.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/trigger/trigger.go

DefaultBackoff is the recommended backoff for a conflict where a client
may be attempting to make an unrelated modification to a resource under
active management by one or more controllers.
- Use DefaultBackoff for resources updated by more controllers

Use DefaultBackoff for resources updated by more controllers

---

test/kafka/kafka-ephemeral-single.yaml

Fixes #472
- Set auto.create.topics.enable to false
```release-note
```
**Docs**

Change auto topic create to be false

---

control-plane/pkg/reconciler/broker/controller.go
control-plane/pkg/reconciler/sink/controller.go
control-plane/pkg/reconciler/trigger/controller.go
control-plane/pkg/reconciler/trigger/controller_test.go
test/e2e-tests.sh
test/e2e/broker_trigger_sink_test.go
test/e2e/delete_cm_test.go
test/e2e/kafka_sink_test.go
test/e2e/main_test.go
test/pkg/sink/verify.go

If our data plane ConfigMap is removed, the control plane won't
be able to recover, so adding a handler so that we resync everything
once that happens.
- Add Global resync handlers
```release-note
:bug: Fix bug
Controllers resync state when managed resources change.
```
/kind bug

Add Global resync handlers

---

control-plane/config/100-config-tracing.yaml
control-plane/config/100-kafka-broker-configmap.yaml
control-plane/config/200-controller-cluster-role.yaml
control-plane/config/200-controller-service-account.yaml
control-plane/config/201-controller-cluster-role-binding.yaml
control-plane/config/500-controller.yaml
control-plane/config/sink/100-kafka-sink.yaml
control-plane/config/sink/100-webhook-cluster-role.yaml
control-plane/config/sink/100-webhook-service-account.yaml
control-plane/config/sink/200-addressable-resolver-cluster-role.yaml
control-plane/config/sink/200-webhook-cluster-role-binding.yaml
control-plane/config/sink/400-webhook-defaulting.yaml
control-plane/config/sink/400-webhook-secret.yaml
control-plane/config/sink/400-webhook-validation.yaml
control-plane/config/sink/500-webhook.yaml
data-plane/config/100-config-kafka-broker-data-plane.yaml
data-plane/config/100-config-logging.yaml
data-plane/config/sink/100-config-kafka-sink-data-plane.yaml
data-plane/config/sink/template/500-receiver.yaml
data-plane/config/template/500-dispatcher.yaml
data-plane/config/template/500-receiver.yaml
hack/label.sh
test/config/100-config-logging.yaml
test/config/chaos/chaosduck.yaml
test/config/cm-watcher.yaml
test/config/config-br-defaults.yaml

Fixes #468 
This was suggested by @matzew (https://knative.slack.com/archives/CR2141CGY/p1607526133257700) following the PR in `eventing-kafka` (https://github.com/knative-sandbox/eventing-kafka/pull/267)
- Change release labels from `eventing.knative.dev` to `kafka.eventing.knative.dev`
```release-note
Change release labels from `eventing.knative.dev` to `kafka.eventing.knative.dev`.
```
/kind cleanup

Change release labels to kafka.eventing.knative.dev

---

data-plane/config/sink/template/500-receiver.yaml
data-plane/config/template/500-receiver.yaml

Signed-off-by: Arghya Sadhu <arghya88@gmail.com>
Fixes #482
- Set anti-affinity for receiver deployment
```release-note
Receivers now specify anti-affinity so that replicas will not be colocated
```
**Docs**

Set anti-affinity for receiver deployment

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployerVerticle.java

Logging the entire resource might block the event loop thread.
- Avoid logging the entire resource

Avoid logging the entire resource

---

control-plane/config/500-controller.yaml
control-plane/config/sink/500-webhook.yaml
data-plane/config/sink/template/500-receiver.yaml
data-plane/config/template/500-dispatcher.yaml
data-plane/config/template/500-receiver.yaml

- There is no need to hard-code replicas since the default is 1.
- An upgrade won't force a scale down if a Deployment has been
scaled up.
- Remove replicas from our Deployments

Remove replicas from our Deployments

---

hack/release.sh

Nightly release failed with:
`./hack/release.sh: line 22: ./hack/../test/data-plane/library.sh: No such file or directory`
Ref: https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-sandbox-eventing-kafka-broker-nightly-release/1340595282286481408
- Fix imports in release script

Fix imports in release script

---

control-plane/pkg/core/config/egress.go
control-plane/pkg/core/config/egress_test.go
control-plane/pkg/core/config/resource.go
control-plane/pkg/core/config/resource_test.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/sink/kafka_sink_test.go
control-plane/pkg/reconciler/trigger/trigger.go
control-plane/pkg/reconciler/trigger/trigger_test.go

During E2E tests there are a lot of no-op reconciliation
since chaosduck kills the leader pod and every time
a new replica starts we trigger a global resync that 
most of the time doesn't actually change the ConfigMap.
For example, the ConfigMap diff looks like this:
```
"""
{
- 	  "generation": "1",
+ 	  "generation": "2",
"resources": [
{
... // 15 identical lines
"""
)
```
This leads to an unnecessary reconciliation loop on the data plane
and increase update conflicts of the ConfigMap.
- Skip ConfigMap update when there are no changes
```release-note
:broom: Update or clean up current behavior
Skip ConfigMap update when there are no changes
```
/kind cleanup

Skip ConfigMap update when there are no changes

---

.github/workflows/kind-e2e.yaml

Fixes #535
- Run on K8s 1.20.0 and bump 1.19 to 1.19.4
```release-note
Support Kubernetes 1.20.
```

Run on K8s 1.20.0 and bump 1.19 to 1.19.4

---

data-plane/config/template/500-dispatcher.yaml

Fixes #537
During E2E tests there are a couple of TimeoutException due to 
DNS name resolver timeout:
```
io.vertx.circuitbreaker.TimeoutException: operation timeout
```
The root cause of the issue is https://github.com/netty/netty/issues/8880, 
and the solution is to add [`single-request-reopen` as a DNS config](https://github.com/netty/netty/issues/8880#issuecomment-558411219).
What does `single-request-reopen` do?
From https://man7.org/linux/man-pages/man5/resolv.conf.5.html
```
single-request (since glibc 2.10)
Sets RES_SNGLKUP in _res.options.  By default,
glibc performs IPv4 and IPv6 lookups in parallel
since version 2.9.  Some appliance DNS servers
cannot handle these queries properly and make the
requests time out.  This option disables the
behavior and makes glibc perform the …
```

Fix TimeoutException and DnsNameResolverTimeoutException

---

test/e2e-common.sh

Eventing webhook HPA config sets MinReplicas to 1 and while chaosduck
kills the webhook we get 0 replicas available during E2E tests.
- Patch HPA min replicas for eventing-webhook

Patch HPA min replicas for eventing-webhook

---

data-plane/profiler/run.sh

As per title, profiling CI job was trying to download Kafka from an
old page, archive links should be much more stable.

Fix link to Kafka download page

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandler.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/ConsumerVerticleFactoryMock.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategyTest.java

Fixes #380
- :bug: Now offset management is correct
```release-note
:bug: Now offset management is correct
```
**Docs**

Fix bad offset management

---

data-plane/config/100-config-kafka-broker-data-plane.yaml

Part of https://github.com/knative-sandbox/eventing-kafka-broker/issues/556
- Consume topic from the earliest offset
```release-note
:bug: Consume topic from the earliest offset
```

[release-0.20] Set auto offset reset to earliest 

---

data-plane/config/100-config-kafka-broker-data-plane.yaml

Part of https://github.com/knative-sandbox/eventing-kafka-broker/issues/556
- Consume topic from the earliest offset
```release-note
:bug: Consume topic from the earliest offset
```

[release-0.19] Set auto offset reset to earliest

---

go.mod
go.sum
vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_types.go
vendor/knative.dev/eventing/test/conformance/helpers/broker_control_plane_test_helper.go
vendor/knative.dev/eventing/test/e2e/helpers/README.md
vendor/modules.txt

As per title, a PR in eventing breaks a test knative/eventing#4843, this should fix it.

Upgrade dependencies

---

test/e2e-common.sh
third_party/eventing-latest/eventing-core.yaml
third_party/eventing-latest/eventing-crds.yaml

This makes our CI runs more reproducible.
I'm also adding automation in this job https://github.com/knative-sandbox/knobots/blob/2619abe637571f4d9d3a008a099b14a61d7b5560/.github/workflows/update-nightlies.yaml
`eventing-crds.yaml` and `eventing-core.yaml` contain YAMLs downloaded from the nightly release bucket.
Part of #596
- Install eventing from nightly release

Install eventing from nightly release

---

data-plane/config/sink/template/500-receiver.yaml
data-plane/config/template/500-dispatcher.yaml
data-plane/config/template/500-receiver.yaml
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/BaseEnv.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Shutdown.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/utils/BaseEnvTest.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/ReceiverEnvTest.java

```
{"@timestamp":"2021-02-10T09:43:50.408Z","@version":"1","message":"Failed during filesystem watch","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.Main","thread_name":"main","level":"ERROR","level_value":40000,"stack_trace":"java.nio.file.ClosedWatchServiceException: null\n\tat java.base/sun.nio.fs.AbstractWatchService.checkOpen(Unknown Source)\n\tat java.base/sun.nio.fs.AbstractWatchService.checkKey(Unknown Source)\n\tat java.base/sun.nio.fs.AbstractWatchService.take(Unknown Source)\n\tat dev.knative.eventing.kafka.broker.core.file.FileWatcher.watch(FileWatcher.java:104)\n\tat dev.knative.eventing.kafka.broker.dispatcher.Main.main(Main.java:153)\n"}
```
- Handle ClosedWatchServiceEx and timeouts
```release-note
Reduce error logging noise on clean …
```

Handle ClosedWatchServiceEx and timeouts

---

data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManagerBenchmark.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManager.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManagerTest.java

- Modified a bit the benchmark from #640 to make sure we don't measure the record allocation time (which is quite expensive in longer benchmarks and dominated over the code under test), but now we record the `UnorderdOffsetManager` allocation (as noted in the JMH javadocs, it's better to avoid using `Level.Invocation` for the state when the bench length is short
- Rewrote the unordered offset manager to be more efficient
Master + https://github.com/knative-sandbox/eventing-kafka-broker/pull/648/commits/1df960a732bc5c76d74ada2fe50ee708606e193d:
```
Benchmark                                                Mode  Cnt       Score      Error  Units
UnorderedOffsetManagerBenchmark.benchmarkMixedABit      thrpt   10   23918,942 ± …
```

Improved UnorderedOffsetManager

---

control-plane/pkg/security/secret.go
control-plane/pkg/security/secret_test.go
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/Credentials.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidator.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KafkaClientsAuth.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentials.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/PlaintextCredentials.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidatorTest.java

When `protocol=SSL` or `protocol=SASL_SSL` CA certificates aren't
required since users might want to use system's root CA set.
When `protocol=SSL` client auth might or might not be required
on the broker side. 
Users can use `user.skip: true` to disable client authentication
checks.
Note: I thought to use `user.skip` since we use `user.crt` and
`user.key` for providing client key pair.
Fixes #605
- Improve SSL support
**Docs**
- https://github.com/knative/docs/issues/3202

Improve SSL support

---

control-plane/pkg/reconciler/base/reconciler_test.go

This base reconciler is already tested through Broker, Trigger, and
KafkaSink reconcilers tests, this PR adds direct tests to it.
- Add tests to base reconciler

Add tests to base reconciler

---

control-plane/pkg/reconciler/kafka/admin_test.go
control-plane/pkg/reconciler/kafka/topic.go
control-plane/pkg/reconciler/kafka/topic_test.go

- Add more unit tests for Kafka reconciler package
- Handle trailing commas and spaces when extracting bootstrap servers

Add more unit tests for Kafka reconciler package

---

.github/CODEOWNERS

With this setting, we will need approval from
productivity for every new test, which can
easily become a bottleneck.
- Drop hack and test from CODEOWNERS

Drop hack and test from CODEOWNERS

---

test/kafka/kafka_setup.sh

`error: unable to recognize "./test/kafka/kafka-ephemeral.yaml": no
matches for kind "Kafka" in version "kafka.strimzi.io/v1beta1"
ERROR: Failed to set up Kafka cluster`
https://github.com/knative-sandbox/eventing-kafka-broker/runs/2045620738?check_suite_focus=true

Fix race condition when installing Kafka in CI

---

.github/workflows/knative-java-test.yaml
.github/workflows/knative-profile-data-plane.yaml
data-plane/profiler/run.sh

Cached dependencies allow reducing workflow run time.
ref: https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven#caching-dependencies
- Add Maven cache in GH Actions

Add Maven cache in GH Actions

---

control-plane/pkg/reconciler/trigger/trigger.go
control-plane/pkg/reconciler/trigger/trigger_test.go

In https://github.com/knative-sandbox/eventing-kafka-broker/issues/720
I noticed that our error propagation isn't helpful for troubleshooting,
since when a broker is not ready, the error in the trigger ready
condition is overridden by "Broker not found in data plane map".
Fixes #720
- Short circuit trigger reconciler when broker not ready

Short circuit trigger reconciliation when broker not ready

---

data-plane/config/broker/100-config-kafka-broker-data-plane.yaml
data-plane/config/sink/100-config-kafka-sink-data-plane.yaml
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java

As reported in slack, we don't set this interceptor.
- Set PartitionKey interceptor to PartitionKeyExtensionInterceptor
```release-note
Add producer interceptor `io.cloudevents.kafka.PartitionKeyExtensionInterceptor` to provide ordered delivery based on the partitioning extension of the CloudEvents spec.
```
/kind bug

Add producer interceptor PartitionKeyExtensionInterceptor

---

.github/workflows/kind-e2e.yaml

Kubernetes's minimum version is 1.18.
Fixes #778
- Stop testing on k8s version 1.17
```release-note
Kubernetes's minimum version is 1.18.
```

Stop testing on k8s version 1.17

---

data-plane/pom.xml

Bumps license-maven-plugin from 4.0.rc2 to 4.0.

[data-plane]: Bump license-maven-plugin in /data-plane

---

.github/dependabot.yml
data-plane/pom.xml

Bumps `protobuf.version` from 3.15.3 to 3.15.8.
Updates `protobuf-java` from 3.15.3 to 3.15.8

[data-plane]: Bump protobuf.version from 3.15.3 to 3.15.8 in /data-plane

---

.github/dependabot.yml
data-plane/benchmarks/pom.xml

Bumps `jmh.version` from 1.27 to 1.29.
Updates `jmh-core` from 1.27 to 1.29
Updates `jmh-generator-annprocess` from 1.27 to 1.29

[data-plane]: Bump jmh.version from 1.27 to 1.29 in /data-plane

---

.github/dependabot.yml

Dependabot was still targeting `master`
- Change dependabot target branch

Change dependabot target branch

---

data-plane/pom.xml

Bumps `vertx.version` from 4.0.2 to 4.0.3.
Updates `vertx-stack-depchain` from 4.0.2 to 4.0.3
Updates `vertx-junit5` from 4.0.2 to 4.0.3

[data-plane]: Bump vertx.version from 4.0.2 to 4.0.3 in /data-plane

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManager.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManagerTest.java

Fix #813
- :bug: Fix out of bounds in unordered offset manager
```release-note
:bug: Fix out of bounds in unordered offset manager
```

Fix out of bounds in unordered offset manager

---

control-plane/pkg/security/config.go
data-plane/THIRD-PARTY.txt
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidator.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidatorTest.java

Fixes #794
Strimzi doesn't support this, so we can't test this E2E :(
- Support SASL mechanism PLAIN
```release-note
Support SASL mechanism PLAIN.
```

Support SASL mechanism PLAIN

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentials.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentialsTest.java

Fixes #854
- Consider "PLAIN" as a valid input in the `KubernetesCredentials` class
```release-note
- :bug: Accept "PLAIN" as a valid `sasl.mechanism` secret value
```

fix: Allow SASLMechanism to equal "PLAIN"

---

control-plane/pkg/reconciler/trigger/trigger.go
control-plane/pkg/reconciler/trigger/trigger_lifecycle.go
control-plane/pkg/reconciler/trigger/trigger_test.go

Fixes #732
- :gift: Add some details in the existing subscriber resolved condition about the delivery order. I didn't added a new condition for it because it's quite complicated and requires several changes in eventing too
```release-note
- :gift: Add some details in the existing subscriber resolved condition about the delivery order.
```
**Docs**

Add more details in the status about ordered and unordered

---

go.mod
go.sum

Eventing bumped Go version in https://github.com/knative/eventing/pull/5359 and #873 is failing due to Go version (I suppose).
Fixes #873
- Bump Go version
```release-note
Bump Go to 1.16.
```

Bump Go version

---

control-plane/pkg/reconciler/trigger/controller.go
control-plane/pkg/reconciler/trigger/controller_test.go

Fixes #863
_Note: I'm not backporting the E2E test since it uses new dependencies._
- Do not add a finalizer on triggers without a broker
```release-note
Do not add a finalizer on triggers without a broker.
```
/kind bug

[release-0.22] Do not add a finalizer on triggers without a broker

---

.github/workflows/kind-e2e.yaml
hack/data-plane.sh

Followup of #749
- :broom: Removed `WITH_KIND` env when pushing data plane images. Now `KO_DOCKER_REPO = "kind.local"` is enough

Remove WITH_KIND

---

.github/workflows/knative-java-test.yaml
hack/data-plane.sh

JDK 15 is not supported anymore https://adoptopenjdk.net/support.html.

Bump JVM version to 16

---

.github/workflows/kind-e2e.yaml

Update KinD version as in https://github.com/knative/eventing/pull/5480

Update k8s versions for KinD tests

---

control-plane/config/sink/100-webhook-cluster-role.yaml

(similar to https://github.com/knative/eventing/pull/5501)
This patch adds the permission to update `namespaces/finalizers`.
Since knative/pkg#2098 added ownerRef refers to namespace for webhook,
we need this permission. Without it, cluster which has a stricter RBAC
rules gets the following error:
```
cannot set blockOwnerDeletion if an ownerReference refers to a resource
you can't set finalizers on ...
```

Add permission to update namespaces/finalizer to webhook cluster role

---

data-plane/config/broker/template/500-dispatcher.yaml
data-plane/config/broker/template/500-receiver.yaml
data-plane/config/sink/template/500-receiver.yaml

Fixes #1002
- using the `runAsNonRoot: true` should be enough. If do not have a hard requirement for `runAsUser`. 
If that is required, I'd think of a good way to introudce this SCC related permissions:
```
- apiGroups:
- security.openshift.io
resources:
- securitycontextconstraints
resourceNames:
- anyuid
verbs:
- use
```
```release-note
```
**Docs**

runAsNonRoot should be good enough

---

control-plane/pkg/reconciler/base/reconciler.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/sink/kafka_sink_test.go

There could be situations where our reconciler failed to update a pod annotation
in a previous reconcile and since there might be multiple pods running we
want to make sure that all pods have the same annotation.
This patch moves the logic to check that we're not performing an
unnecessary update down to when we're trying to update a single pod
annotation.

Improve data-plane pods annotation update logic

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordSender.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/AbstractConsumerVerticleTest.java

This removes the "mockish" `ConsumerRecordSender.create` and replaces it with `ConsumerRecordSender.noop`. The reason is that the method `ConsumerRecordSender.create` is not really useful in the production code, but instead for mocking. Instead, I've introduced `ConsumerRecordSender.noop` which is more specialized and serves our purpose.
- :broom: Replaced `ConsumerRecordSender.create` with `ConsumerRecordSender.noop`

Replaced ConsumerRecordSender.create with ConsumerRecordSender.noop

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/AsyncCloseable.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/metrics/MetricsTest.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordSender.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcher.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/SinkResponseHandler.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/BaseConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerRecordSender.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandler.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordSenderMock.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/SinkResponseHandlerMock.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/AbstractConsumerVerticleTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandlerTest.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestMapper.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestMapperTest.java

While working on improving the dispatcher code base, I've found out we have several code snippets, all around the `close` problem. This PR is an attempt to solidify, abstract and share code for "closing" components
The `AsyncCloseable` is like the vert.x `Closeable`, but more than accepting a promise, it returns a `Future` instead. It implements vert.x `Closeable` and can be converted to a blocking `java.util.AutoCloseable`.
It has static methods to compose multiple `AsyncCloseable` and to wrap `AutoCloseable`, for better integration with our blocking components.
- :gift: Introduce `AsyncCloseable` interface
- :broom: Cleanup all various usages of close routines and replace them with `AsyncCloseable`

Introduced `AsyncCloseable`

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/BaseEnv.java
data-plane/receiver/pom.xml
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverEnv.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverEnvTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactoryTest.java

- :broom: Moved receiver `Main`, together with the env class and the receiver factory class in a dedicated package, called `dev.knative.eventing.kafka.broker.receiver.main`
- :broom: Reorganized fields declaration in `BaseEnv` to match the style used in `ReceiverEnv`
In a followup I'll apply the same change to the dispatcher Main

Moved receiver Main to a dedicated package

---

data-plane/dispatcher/pom.xml
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/DispatcherEnv.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/Main.java

Like https://github.com/knative-sandbox/eventing-kafka-broker/pull/1031
- :broom: Moved dispatcher `Main`, together with the env class in a dedicated package, called `dev.knative.eventing.kafka.broker.dispatcher.main`

Moved dispatcher Main to a dedicated package

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/ResourcesReconciler.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerBuilder.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerImpl.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourceReconcilerTestRunner.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerImplTest.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployerVerticle.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployerVerticleTest.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/ReceiverVerticle.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestMapperTest.java

- :broom: Moved inner class `ResourcesReconcilerImpl.Builder` to `ResourcesReconcilerBuilder`
- :broom: Moved `ResourcesReconcilerImpl.builder()` to `ResourcesReconciler.builder()`
- :gift: Now `ResourcesReconcilerBuilder` provides a `buildAndListen` method which builds directly the `ResourcesReconcilerMessageHandler` as well

Streamline the usage of the ResourcesReconciler

---

data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestMapper.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestToRecordMapper.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/StrictRequestToRecordMapper.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/ReceiverTracingVerticleTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/ReceiverVerticleTest.java
data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java

- :broom: Renamed `CloudEventRequestToRecordMapper` to `StrictRequestToRecordMapper`. The reason is that, by the types, it's clearly mapping `CloudEvent`s and because `Strict` specifies that the conversion fails if the input request is not a cloudevent
- :broom: Now the `StrictRequestToRecordMapper` is a singleton
- :broom: Removed tracing logic in `StrictRequestToRecordMapper` and moved it to `RequestMapper`, where I think it belongs

Reorganize CloudEventRequestToRecordMapper

---

control-plane/pkg/core/config/utils.go
control-plane/pkg/core/config/utils_test.go
control-plane/pkg/reconciler/trigger/trigger_test.go

Fixes #757, followup of #1021, part of https://github.com/knative/eventing/issues/5148
- :gift: Support the new `DeliverySpec.Timeout` field
```release-note
Now you can specify both in Broker and Trigger delivery specs the new timeout field, as part of the experimental feature delivery-timeout. For more details: https://knative.dev/docs/eventing/experimental-features/ 
```

Glue the new DeliverySpec.Timeout

---

data-plane/THIRD-PARTY.txt
data-plane/core/pom.xml
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/impl/AllFilter.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/impl/AnyFilter.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/impl/BaseStringFilter.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/impl/ExactFilter.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/impl/PrefixFilter.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/impl/SqlFilter.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/impl/SuffixFilter.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/filter/impl/AllFilterTest.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/filter/impl/AnyFilterTest.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/filter/impl/ExactFilterTest.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/filter/impl/PrefixFilterTest.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/filter/impl/SqlFilterTest.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/filter/impl/SuffixFilterTest.java
data-plane/pom.xml

This is a totally WIP PR meant to experiment what's missing in the cloudevents-sql package in order to implement subscriptions api filters.
Depends on https://github.com/knative/eventing/issues/5204 (unless we resort to create our own Trigger api).
- :gift: Implement `Filter` for all the subscriptions API filters

Playing with Subscriptions API filters

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Shutdown.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/utils/ShutdownTest.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/Main.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java

- `Shutdown` does not expose a method that returns a `Runnable` anymore, but instead it exposes a method that automatically register the hook inside the `Runtime`
- Added private constructor to `Shutdown` and now the class is `final`
- Renamed `closeSync` to `closeVertxSync`

Encapsulate runtime hook registration inside Shutdown

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Configurations.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/utils/ConfigurationsTest.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/Main.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java

Renamed both `getProperties` and `getPropertiesAsJson` to `read[]Sync` in order to underline that the method is performing a file read and that the method is blocking, thus it shouldn't be called on the event loop

Renamed getProperties to readPropertiesSync

---

data-plane/dispatcher/pom.xml
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/Main.java
data-plane/receiver/pom.xml
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java

Fixes #1070
- :broom: Removed logstash encoder class packaging hack, now maven-shade-plugin will load by default the whole package inside the uber jar

Removed logstash main hack

---

data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/MethodNotAllowedHandler.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/ProbeHandler.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverEnv.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/MethodNotAllowedHandlerTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/ProbeHandlerTest.java
data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java

Fixes #1101 
In our receiver verticle, we want to compose handlers
using the chain of responsibility pattern. 
For example, our probe handler handles the request only when it is
a kubelet request for readiness or liveness.
Now, we are checking in our main handler if  `response.isEnded()`
to understand if a previous handler has handled the request.
This leads to the error linked in the linked issue and it's not 
a robust design (as discussed in https://github.com/knative-sandbox/eventing-kafka-broker/pull/1041#discussion_r658261607).
- Resolve response already sent with a chain of handlers
/kind bug

Resolve response already sent with a chain of handlers

---

.github/workflows/knative-java-test.yaml

This uses native caching support of GH actions
- Use the new cache dependencies feature [1]
[1] https://github.com/actions/setup-java#caching-packages-dependencies

Bump setup-java to v2 in GH action

---

test/e2e-tests.sh

Add workaround for connection timeout to maven central.
- ref https://github.com/kubernetes/test-infra/issues/23741

Workaround Prow CI failures with iptables change

---

control-plane/pkg/core/config/utils.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/testing/objects_broker.go
control-plane/pkg/reconciler/testing/objects_common.go

The resolver uses `ref.namespace` to lookup the destination
addressable.
`ref.namespace` for the `deadLetterSink` is not defaulted by the
webhook like for `trigger.subscriber.ref`, so we might receive a
destination with an empty string for
`deadLetterSink.ref.namespace` which leads to not finding the
referenced addressable service.
Fixes #1011 
- Add namespace to referenced addressable before resolving destination
```release-note
The fields `Broker.spec.delivery.deadLetterSink.ref.namespace` and `Trigger.spec.delivery.deadLetterSink.ref.namespace` are optional.
By default the controller uses the object namespace. 
```

Add namespace to referenced addressable before resolving destination

---

test/config/monitoring.yaml

avoiding DH rate limit issues - hence using GH's container registry

Download zipkin from Github's container registry

---

hack/data-plane.sh

It's better to use the maven wrapper since it doesn't require a maven installation.
- Use Maven wrapper to run unit tests

[minor] Use Maven wrapper to run unit tests

---

hack/data-plane.sh

Maven is stuck when running unit tests.
This makes our unit test job less flaky.

Debug Maven stuck

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/kafka/config.go
control-plane/pkg/reconciler/kafka/topic.go
control-plane/pkg/reconciler/kafka/topic_test.go
control-plane/pkg/reconciler/sink/kafka_sink.go

Fixes #
- Getting rid of the confusing code here, which defines a function type and then defines functions under it: https://github.com/knative-sandbox/eventing-kafka-broker/blob/c3b0e1bd9afa7e6ea1dc22f30504baf2130a5bf3/control-plane/pkg/reconciler/kafka/topic.go#L117
For me, this is a bit confusing:
```go
... 
// func type definition
type NewClusterAdminFunc func(addrs []string, config *sarama.Config) (sarama.ClusterAdmin, error)
// func definition for that func type
func (f NewClusterAdminFunc) DeleteTopic(topic string, bootstrapServers []string, secOptions security.ConfigOption) (string, error) {
...
}
// how the func is used as a struct member
type Reconciler struct {
...
// ClusterAdmin creates new sarama ClusterAdmin. It's convenient to add this as Reconciler field so that we can
// …
```

Prefactoring the structure to be able to mock ClusterAdmin - DeleteTopic func

---

control-plane/pkg/reconciler/source/source.go
control-plane/pkg/security/secrets_provider_net_spec.go
control-plane/pkg/security/secrets_provider_net_spec_test.go
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesAuthProvider.java

This PR adds a `SecurityProviderFunc` for `KafkaNetSpec` (the type
that holds references to secrets and their keys)
To avoid resolving secrets in 2 different places, I'm creating a
struct `NetSpecAuthContext` to hold the authentication context
that we need.
`NetSpecAuthContext` holds a `VirtualSecret` which is a non-existing
secret (in-memory only) so that we can reuse the existing security logic
that we have for Broker and KafkaSink and `MultiSecretReference` which
is what the contract expects.
Part of #312
- Add security provider for KafkaNetSpec
```release-note
None
```
**Docs**
```
None
```

Add security provider for KafkaNetSpec

---

control-plane/pkg/reconciler/source/source.go
control-plane/pkg/security/secrets_tracker.go
control-plane/pkg/security/secrets_tracker_test.go

This PR adds a function `TrackNetSpecSecrets` that contains the
logic to track secrets referenced by a `KafkaNetSpec` (the type
that is embedded in `KafkaSource` and has all the secret
references)
Part of #312
- Add secret tracker for KafkaNetSpec
```release-note
None
```
**Docs**
```
None
```

Add secret tracker for KafkaNetSpec

---

control-plane/pkg/core/config/egress.go
control-plane/pkg/core/config/egress_test.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/controller.go
control-plane/pkg/reconciler/kafka/client.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/source/source.go
go.mod
vendor/knative.dev/eventing-kafka/pkg/common/kafka/offset/offsets.go
vendor/modules.txt

Fixes #
- Reconcile subscribers in the control plane
- Init offsets and mark subscriptions ready
- Data plane changes (the check to see if the offsets are initialized) are to be done in a separate PR. 
```release-note
```
**Docs**

Kafka Channel Subscription reconciliation - control plane

---

control-plane/pkg/core/config/resource.go
control-plane/pkg/core/config/resource_test.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/source/source.go

The assumption that `contract.resources[*].egreeses` don't change
when we update a resource in the contract is not true anymore
(and it is not really needed for most of our resources,
only Broker needs that),
so removing the copy.
Part of #312
- Remove egresses copy when comparing resources
```release-note
None
```
**Docs**
```
None
```

Remove egresses copy when comparing resources for change detection

---

control-plane/pkg/reconciler/source/auth_provider.go

Part of #312
- Enable KafkaSource auth support
```release-note
None
```
**Docs**
```
None
```

Enable KafkaSource auth support

---

.gitignore
control-plane/cmd/kafka-controller/main.go
control-plane/cmd/webhook-kafka/main.go
control-plane/config/200-controller/200-controller-cluster-role.yaml
control-plane/config/200-controller/500-controller.yaml
control-plane/pkg/reconciler/source/controller.go
data-plane/config/source/100-config-kafka-source-data-plane.yaml
data-plane/config/source/200-source-data-plane-cluster-role.yaml
data-plane/config/source/200-source-data-plane-service-account.yaml
data-plane/config/source/201-source-data-plane-cluster-role-binding.yaml
data-plane/config/source/template/500-dispatcher.yaml
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/KeyDeserializerTest.java
hack/data-plane.sh
test/e2e-common.sh
test/e2e/kafka_source_test.go
vendor/knative.dev/eventing-kafka/test/e2e/helpers/channel_subscription_ready_test_helper.go
vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_binding_test_helper.go
vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_helper.go
vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_source.go
vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_source_test_helper.go
vendor/knative.dev/eventing-kafka/test/lib/creation.go
vendor/knative.dev/eventing-kafka/test/lib/deletion.go
vendor/knative.dev/eventing-kafka/test/lib/listers.go
vendor/knative.dev/eventing-kafka/test/lib/resources/kafka.go
vendor/modules.txt

Fixes #312
- Add E2E tests
- Enable KafkaSource controller (webhook and controller handlers)
- Add KafkaSource manifests
```release-note
None
```
**Docs**
```
None
```

Enable KafkaSource controller

---

control-plane/cmd/kafka-controller/main.go
control-plane/pkg/reconciler/base/receiver_condition_set.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/broker/controller.go
control-plane/pkg/reconciler/broker/controller_test.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/controller.go
control-plane/pkg/reconciler/sink/controller.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/sink/kafka_sink_test.go
control-plane/pkg/reconciler/source/source.go
control-plane/pkg/reconciler/source/source_test.go
control-plane/pkg/reconciler/testing/factory.go
control-plane/pkg/reconciler/testing/objects_broker.go
control-plane/pkg/reconciler/testing/objects_common.go
control-plane/pkg/reconciler/testing/objects_source.go
control-plane/pkg/reconciler/trigger/controller.go
control-plane/pkg/reconciler/trigger/trigger.go
control-plane/pkg/reconciler/trigger/trigger_test.go

- Better naming and consistency for `config.Env`
- Got rid of `broker.Config` which only had 1 additional field. That `broker.Config` thing was used in source, channel and sink. Changed those usages to `config.Env`.
-
```release-note
```
**Docs**

Better naming and consistency for config.Env and broker.Config

---

control-plane/pkg/prober/cache.go
control-plane/pkg/prober/cache_test.go

This patch adds a probe cache that allows to associate a `Status`
to a given key.
The cache prunes expired entries and calls a callback when
an entry is expired, so that controllers can re-queue associated
resources.
This is part of our work to reduce e2e tests' flakiness.
- Add probes cache
```release-note
None
```
**Docs**
```
None
```

Add probes cache

---

test/kafka/strimzi-cluster-operator.yaml

The diff won't make sense but there is a non-visible character in
between `_<hostname>_:` and `_<port>_`.
- Remove unicode control characters in Strimzi operator YAML
```release-note
None
```
**Docs**
```
None
```

Remove unicode control characters in Strimzi operator YAML

---

control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/channel_test.go
control-plane/pkg/reconciler/channel/controller.go
control-plane/pkg/reconciler/sink/kafka_sink_test.go
control-plane/pkg/reconciler/source/source_test.go
control-plane/pkg/reconciler/testing/listers.go
control-plane/pkg/reconciler/testing/objects_channel.go
control-plane/pkg/reconciler/testing/objects_common.go
control-plane/pkg/reconciler/trigger/trigger_test.go

Fixes #
- Pushing for early feedback
- Check individual commits
-
```release-note
```
**Docs**

Initial Kafka channel reconciler tests

---

data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/ControlPlaneProbeRequestUtil.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/MethodNotAllowedHandler.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/ProbeRequestUtil.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/ProbeRequestUtilTest.java

Probing is done using the knative/networking data-plane contract
(already implemented in Eventing through knative/pkg).
ref issue knative/eventing#3911
This is part of our work to reduce e2e tests' flakiness.
- Receiver handles ingress probes
```release-note
```
**Docs**

Receiver handles ingress probes

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/AsyncCloseable.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherListener.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/BaseConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/AbstractOffsetManagerTest.java

When a consumer is closed, we want to commit the offsets for all
owned partitions.
Fixes (some flaky tests)
- Commit offset on consumer close
```release-note
Commit offset on consumer close.
```
**Docs**
```
None
```

Commit offset on consumer close

---

control-plane/pkg/reconciler/base/receiver_condition_set.go
control-plane/pkg/reconciler/source/source.go
control-plane/pkg/reconciler/source/source_test.go
control-plane/pkg/reconciler/testing/objects_source.go

> when KafkaSource cannot resolve the sink, it just reports status "Unknown"
- Add KafkaSource condition for Sink resolved
```release-note
None
```
**Docs**
```
None
```

Add KafkaSource condition for Sink resolved

---

test/e2e/conformance/data_plane_conformance_test.go

Fixes #
- renaming conformance test functions
-
-
```release-note
```
**Docs**

NT: We are testing the v1, renaming to proper name

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/InvalidCloudEventInterceptor.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/KafkaConsumerRecordUtils.java
data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java

A valid CloudEvent in the CE binary protocol binding of Kafka
might be composed by only Headers.
KafkaConsumer doesn't call the deserializer if the value
is null.
That means that we get a record with a null value even though
the record is a valid CloudEvent.
This patch handles events without the data field properly
by creating the CloudEvent object from record headers, if
the above conditions apply.
Fixes #1455 
- Properly handle events without data field
```release-note
Properly handle events without the `data` field.
```
**Docs**
```
None
```

Properly handle events without the `data` field

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/KafkaConsumerRecordUtils.java
data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java

Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/1460
```release-note
Properly handle events without the `data` field.
```
**Docs**
/kind bug

[release-0.26] Properly handle events without the `data` field (#1460)

---

control-plane/pkg/reconciler/channel/channel.go

Fixes #
- as per title
-
-
```release-note
```
**Docs**

Using a CONST for the default delivery order of events

---

test/e2e_new/tracing_test.go

If we install the source and the sink in the same `rekt` phase
we might start sending events before the sink is actually ready
to accept them.
See also this comment: https://github.com/knative-sandbox/eventing-kafka-broker/issues/1205#issuecomment-972719530
Fixes #1205
- Fix flaky tracing test
```release-note
None
```
**Docs**
```
None
```

Fix flaky tracing test

---

control-plane/config/200-controller/500-controller.yaml
control-plane/pkg/config/env_config.go
control-plane/pkg/prober/async_prober.go
control-plane/pkg/prober/async_prober_test.go
control-plane/pkg/prober/cache.go
control-plane/pkg/prober/prober.go
control-plane/pkg/prober/prober_test.go
control-plane/pkg/prober/probertesting/mock_prober.go
control-plane/pkg/prober/probertesting/mock_prober_test.go
control-plane/pkg/receiver/address.go
control-plane/pkg/reconciler/base/receiver_condition_set.go
control-plane/pkg/reconciler/base/reconciler.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/broker/controller.go
control-plane/pkg/reconciler/broker/controller_test.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/channel_test.go
control-plane/pkg/reconciler/channel/controller.go
control-plane/pkg/reconciler/channel/controller_test.go
control-plane/pkg/reconciler/sink/controller.go
control-plane/pkg/reconciler/sink/controller_test.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/sink/kafka_sink_test.go
control-plane/pkg/reconciler/source/source.go
control-plane/pkg/reconciler/testing/objects_broker.go
control-plane/pkg/reconciler/testing/objects_common.go
go.mod
vendor/modules.txt

This patch adds the `Prober` that probes the receiver for readiness.
It uses the cache introduced in https://github.com/knative-sandbox/eventing-kafka-broker/pull/1401 and the data plane
probe handling introduced in https://github.com/knative-sandbox/eventing-kafka-broker/pull/1431.
- Probe resource ingress for readiness
```release-note
The kafka-controller deployment emits probe requests against the data plane (kafka-sink-receiver and kafka-broker-receiver) to determine Kafka Broker and KafkaSink readiness.
```
**Docs**
```
None
```
/kind enhancement

Probe resource ingress for readiness

---

test/e2e-upgrade-tests.sh

To unblock other PRs, I'm adding a script that will make the upgrade
test job green.
- Add upgrade test script placeholder
```release-note
None
```
**Docs**
```
None
```

Add upgrade test script placeholder

---

control-plane/cmd/kafka-controller/main.go
control-plane/cmd/webhook-kafka/main.go
control-plane/config/200-webhook/100-webhook-cluster-role.yaml
control-plane/pkg/apis/eventing/v1/broker_validation.go
control-plane/pkg/apis/eventing/v1/broker_validation_test.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/broker/controller.go
control-plane/pkg/reconciler/broker/controller_test.go
control-plane/pkg/reconciler/testing/objects_broker.go

- Remove broker.spec.config defaulting magic
- Add webhook validation (i think we're better off rejecting invalid Brokers from the start)
```release-note
`broker.spec.config` is now required.
```
**Docs**
- I'll check if docs mentions this feature (I don't thing it does)
/assign @aliok

Remove broker.spec.config defaulting magic

---

control-plane/config/100-channel/100-kafka-channel-configmap.yaml
control-plane/config/200-controller/500-controller.yaml
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/channel_test.go
control-plane/pkg/reconciler/kafka/topic.go
control-plane/pkg/reconciler/testing/objects_channel.go

Fixes #
- Channel to use new configmap format for bootstrap servers
- Nothing else is used from configmap at this moment (no auth etc.)
```release-note
```
**Docs**

Channel to use new configmap format for bootstrap servers

---

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_defaults.go
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_defaults_test.go
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_defaults.go
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_defaults_test.go
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types.go
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_validation.go
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_validation_test.go
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_types.go
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_validation.go
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/register.go
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/zz_generated.deepcopy.go
control-plane/pkg/reconciler/consumergroup/consumergroup.go

Part of #1537
- Add ConsumerGroup reconciler
```release-note
None
```
**Docs**
```
None
```
TODO: reconciler tests (follow-up PR)

ConsumerGroup reconciler

---

test/pkg/broker/broker.go
test/pkg/testing/run.go

Fixes an issue with using wrong default values when `config-br-defaults` configmap points to another cluster-default configmap that might not include configuration for Kafka. It might include for example MTChannelBasedBroker configuration in which case the Broker creation fails with an error like this
```
invalid configuration - numPartitions: 0 - replicationFactor: 0 - bootstrapServers:  - ConfigMap data: map[channelTemplateSpec:apiVersion: messaging.knative.dev/v1
kind: InMemoryChannel
]
```
- Creation a new ConfigMap in the test namespace that will be used by the Brokers.
-
-
```release-note
```
**Docs**

[main] Use Broker's own configmap for Kafka

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/testing/objects_broker.go
test/e2e_new/broker_test.go
test/e2e_new/features/broker_deleted_recreated.go
test/e2e_new/features/featuressteps/broker.go
test/e2e_new/resources/configmap/copy.go

Deleting the Broker ConfigMap prevents the Broker from being finalized
since we can't get Kafka cluster URL and credentials to remove topics.
In this patch, we're adding a finalizer to the ConfigMap associated
with the Broker and then remove it once the broker is properly
finalized.
Fixes #1580 
- Fix deleting the Broker ConfigMap prevents the Broker from being finalized
```release-note
Fix deleting the Broker ConfigMap prevents the Broker from being finalized
```
**Docs**

Fix deleting the Broker ConfigMap prevents the Broker from being finalized

---

control-plane/pkg/reconciler/consumergroup/filter.go
control-plane/pkg/reconciler/consumergroup/filter_test.go
control-plane/pkg/reconciler/trigger/v2/controllerv2.go

Every user-facing resource keeps track of the associated
ConsumerGroup resources.
This patch adds a generic filter function to be used by
KafkaSource, Trigger, and KafkaChannel reconciler.
Part of #1537 
- Add a ConsumerGroup filter function
```release-note
None
```
**Docs**
```
None
```

Add a ConsumerGroup filter function based on owner refs

---

control-plane/pkg/reconciler/broker/controller.go
control-plane/pkg/reconciler/trigger/controller.go
control-plane/pkg/reconciler/trigger/v2/controllerv2.go

When a reconciler gets promoted to be the leader, every object
gets re-queued even if it shouldn't be.
Tested in #1612
- Add promote filter function to Broker and Trigger reconciler
```release-note
None
```
**Docs**
```
None
```

Add promote filter function to Broker and Trigger reconciler

---

control-plane/config/100-kafka-internal/100-consumer.yaml
control-plane/config/100-kafka-internal/100-consumergroup.yaml

Part of #1537
- Add CRDs manifests for consumers scheduling and scaling
(No need to have any open API schema for this CRD)
```release-note
None
```
**Docs**
```
None
```

Add CRD manifests for consumers scheduling and scaling

---

data-plane/config/broker/500-dispatcher.yaml
data-plane/config/broker/500-receiver.yaml
data-plane/config/sink/500-receiver.yaml
data-plane/config/source/500-dispatcher.yaml
hack/data-plane.sh

Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/1674
The use of `TAG` for referencing images isn't reliable.
During the v1.1, release artifacts reference a `devel` image
which isn't correct.
In this patch, we start using a new tag which is based on the
image digest.
This fixes recent failures of the upgrade test.

[release-1.1] Use digest for data plane images

---

control-plane/config/100-source/200-sources-observer-aggregated-clusterrole.yaml

Eventing controller error:
```
kafkasources.sources.knative.dev is forbidden:
User \"system:serviceaccount:knative-eventing:eventing-controller\"
cannot list resource \"kafkasources\" in API group
\"sources.knative.dev\" at the cluster scope
```
/assign @aliok

Add Source Observer ClusterRole

---

data-plane/config/broker/500-dispatcher.yaml
data-plane/config/broker/500-receiver.yaml
data-plane/config/sink/500-receiver.yaml
data-plane/config/source/500-dispatcher.yaml
hack/data-plane.sh

The use of `TAG` for referencing images isn't reliable.
During the v1.1, release artifacts reference a `devel` image
which isn't correct.
In this patch, we start using a new tag which is based on the
image digest.
This fixes recent failures of the upgrade test.
Fixes #1667

Use digest for data plane images

---

.github/workflows/kind-e2e.yaml

As per title.
It just consumes GH action time for no reason.

Remove teardown phase in GH actions since it takes a lot of time

---

test/e2e_new/run.go
test/e2e_new/trigger_finalizer_test.go

Enabling Kafka Broker while running channel-based Broker with
Kafka sets incorrect finalizer.
- Verify Trigger finalizer isn't set on Triggers of another class
```release-note
None
```
**Docs**
```
None
```

Verify Trigger finalizer isn't set on Triggers of another class

---

.codecov.yaml

It uses master by default, so it can't show coverage data:
https://app.codecov.io/gh/knative-sandbox/eventing-kafka-broker/blob/master/control-plane/pkg/kafka/consumer_group_lag.go
Part of #1682 #1683

Use main as branch in codecov config

---

control-plane/pkg/kafka/consumer_group_lag_test.go

As per title, to increase code coverage.
Part of #1682

Add test for PartitionLag.String() method

---

control-plane/pkg/reconciler/consumergroup/filter.go
control-plane/pkg/reconciler/consumergroup/filter_test.go
control-plane/pkg/reconciler/trigger/v2/controllerv2.go

We need to enqueue the Trigger key associated with the 
ConsumerGroup and not the ConsumerGroup resource.
Related https://github.com/knative-sandbox/eventing-kafka-broker/pull/1611#discussion_r780340587
- Enqueue trigger when ConsumerGroups change

Enqueue trigger when ConsumerGroups change

---

test/e2e-common.sh
test/e2e/kafka_sink.go
test/e2e/kafka_sink_test.go
test/upgrade-tests.sh
test/upgrade/continual.go
test/upgrade/continual/kafka-sink-source-config.toml
test/upgrade/continual/sink_source.go
test/upgrade/continual/types.go
test/upgrade/postdowngrade.go
test/upgrade/postupgrade.go
test/upgrade/preupgrade.go
test/upgrade/suite.go

To implement KafkaSink upgrade tests we reuse an existing utility
that runs a KafkaSink test provided a `KafkaSinkSpec` object.
The continual test for KafkaSink is implemented using a combination
`KafkaSink` and `KafkaSource` as follows:
```
-> Upgrade test source
-> `KafkaSink`
-> `KafkaSource`
-> Upgrade test sink
```
We use KafkaSink and KafkaSource to avoid creating a specific
kafka consumer for the upgrade test.

Add KafkaSink upgrade tests

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/IngressProducer.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestContext.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStore.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/IngressRequestHandlerImpl.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/IngressRequestHandlerImplTest.java
data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java

See https://knative.dev/docs/eventing/observability/metrics/eventing-metrics/#broker-ingress
_Note: Eventing Core uses `broker_name` for the tag but since we have Broker/Channel/Sink, I'm using `name` instead._
Example metrics:
```
event_count_total{event_type="com.example.FullEvent",name="",namespace_name="",response_code="202",response_code_class="2xx",} 15915.0
event_dispatch_latencies_max{event_type="com.example.FullEvent",name="",namespace_name="",response_code="202",response_code_class="2xx",} 99.0
event_dispatch_latencies_bucket{event_type="com.example.FullEvent",name="",namespace_name="",response_code="202",response_code_class="2xx",le="1.0",} 7499.0
event_dispatch_latencies_bucket{event_type="com.example.FullEvent",name="",namespace_name="",response_code="202",response_code_class= …
```

Align Receiver metrics to Eventing core Ingress metrics

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java

Kafka Consumer and Producer metrics can't be scraped if we use
the prometheus naming convention since internally the micrometer
libary uses micromether specific logic to convert Kafka clients
metric names to micrometer metric names.

Fix metrics naming for Kafka clients

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java

Vert.x auto-subscribe and handling of records might grow
unbounded, and it is particularly evident when the consumer
is slow to consume messages.
To apply backpressure, we need to bound the number of outbound
in-flight requests, so we need to manually poll for new records
as we dispatch them to the subscriber service.
The maximum number of outbound in-flight requests is already configurable
with the consumer parameter `max.poll.records`, and it's critical to
control the memory consumption of the dispatcher.
Part of #1732 
```release-note
Apply back-pressure by limiting the number of in-flight dispatch requests in the unordered event consumption 
```

Bounded in-flight dispatch requests in unordered delivery for back-pressure

---

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types.go
control-plane/pkg/reconciler/source/v2/sourcev2.go

We cannot mark the `KafkaConditionConsumerGroup` as ready until
the underlying ConsumerGroup is ready.
/assign @aavarghese

Propagate ConsumerGroup status to KafkaSource

---

control-plane/pkg/receiver/address_test.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/sink/kafka_sink_test.go
test/upgrade/continual/verification.go

After deleting a topic if a producer wasn't closed yet,
closing a producer ends up blocking and requesting metadata
for `max.block.ms`.
See (under discussions KIPs, unlikely to be accepted as they are):
- https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=181306446
- https://cwiki.apache.org/confluence/display/KAFKA/KIP-286%3A+producer.send%28%29+should+not+block+on+metadata+update

Probe ingress resources on finalize

---

.github/workflows/kind-e2e.yaml

exactly like https://github.com/knative/eventing/pull/6068/files  - but for here
/assign @pierDipi

Remove k8s 1.20 APIs

---

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types.go
control-plane/pkg/reconciler/testing/objects_consumer.go
control-plane/pkg/reconciler/testing/objects_consumergroup.go
control-plane/pkg/reconciler/testing/objects_source.go
control-plane/pkg/reconciler/trigger/v2/controllerv2.go
control-plane/pkg/reconciler/trigger/v2/controllerv2_test.go
control-plane/pkg/reconciler/trigger/v2/triggerv2.go
control-plane/pkg/reconciler/trigger/v2/triggerv2_test.go

Part of #1537
/cc @pierDipi 
- Adding new Trigger reconciler unit tests for consumer scheduling and scaling
```release-note
```
**Docs**

Trigger reconciler tests for ConsumerGroup scaling

---

test/e2e-tests.sh
test/reconciler-tests.sh

This [test run](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka-broker/1728/pull-knative-sandbox-eventing-kafka-broker-integration-tests/1484140292578742272) failed with:
```
panic: test timed out after 30m0s
```

Increase E2E and rekt tests timeout

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java

Fixes #
[](https://github.com/knative-sandbox/eventing-kafka-broker/issues/1770)
- Add HTTP Header `Prefer: reply` according to [Knative specs](https://github.com/knative/specs/blob/main/specs/eventing/data-plane.md#derived-reply-events)
- :bug: Fix bug https://github.com/knative-sandbox/eventing-kafka-broker/issues/1770
```release-note
An HTTP header will be supplied to your event consumers when the broker it is communicating with supports reply events. This will always be sent while using this Kafka broker since it supports handling reply events.
```
**Docs**

Add HTTP Header 'Prefer: reply' in accordance with KNative specs

---

test/upgrade-tests.sh
test/upgrade/continual/verification.go

Fixes error such as:
Error: test/upgrade/continual/verification.go:81:9: config.FinishedSleep
undefined (type *prober.Config has no field or method FinishedSleep)
* The env variable can be removed once changes from
knative/eventing#6074 are propagated to this
repo.

Set FinishedSleep via env variable in upgrade tests 

---

control-plane/pkg/reconciler/source/v2/controllerv2.go
control-plane/pkg/reconciler/source/v2/controllerv2_test.go
control-plane/pkg/reconciler/source/v2/sourcev2.go
control-plane/pkg/reconciler/source/v2/sourcev2_test.go
control-plane/pkg/reconciler/testing/objects_consumer.go
control-plane/pkg/reconciler/testing/objects_consumergroup.go
control-plane/pkg/reconciler/testing/objects_source.go

Part of #1537
~Will be rebased on #1754~ **done**
/cc @pierDipi 
- Adding new KafkaSource reconciler unit tests for consumer scheduling and scaling
```release-note
```
**Docs**

KafkaSource reconciler tests for ConsumerGroup scaling

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerImpl.java

These logs are useful to watch control plane activities in
the data plane and auditing the behavior and they should be
IMO set to `info` since they are not a lot or in the hot path.

Promote some logs to info in data plane reconciler

---

test/upgrade-tests.sh

Exporting logs continuously during the upgrade test is useful
for debugging.

Export logs continuously during upgrade tests

---

hack/release.sh

Release 1.2.0 went wrong since the `ARTIFACTS_TO_PUBLISH`
variable has to be a string, but it was an array.

[release-1.2] Fix release: artifact to publish type

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/channel_test.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/sink/kafka_sink_test.go
test/e2e_new/features/broker_deleted_recreated.go
test/e2e_new/features/featuressteps/broker.go

This PR fixes a problem that we have since we were deleting the
finalizer without deleting the topic accordingly since we were
returning nil in `FinalizeKind` which deletes the finalizer from
the resource.

[1.2] Do not delete finalizer until the probe returns status not ready

---

.github/workflows/kind-e2e.yaml
test/reconciler-tests.sh

Fixes #
- Run channel Rekt tests
- `cloudevents` tag was required to run Rekt tests for KafkaChannel but was forgotten
- Depends on https://github.com/knative-sandbox/eventing-kafka-broker/pull/1824. It is to revert the breakage merged unnoticed because of the conformance tests not running.
```release-note
:gift: KafkaChannel becomes conformant with spec. Conformance tests are now run with every code change.
```
**Docs**

Run channel Rekt tests

---

hack/release.sh

Release 1.2.0 went wrong since the `ARTIFACT_TO_PUBLISH`
variable has to be a string, but it was an array.

Fix release: artifact to publish type

---

control-plane/cmd/webhook-kafka/main.go
control-plane/config/200-webhook/400-webhook-defaulting.yaml
control-plane/pkg/apis/core/pod_defaulting.go
control-plane/pkg/apis/core/pod_defaulting_test.go
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_types.go

To be able to mount a `ConfigMap` per dispatcher pod, we need
to use a webhook that reacts when a _dispatcher_ `Pod` is created.
Dispatcher pods are selected based on this label:
```
app.kubernetes.io/component: kafka-dispatcher
```
(so the StatefulSets kafka-source-dispatcher,
kafka-broker-dispatcher, etc must have these labels).
and only when they are in a namespace labeled with:
```
app.kubernetes.io/name: knative-eventing
```
which is the label used for the `knative-eventing` namespace.
To every dispatcher pod, we inject a volume in `spec.volumes`
`contract-resources` which then reference a ConfigMap which
has the same name as the `Pod`.
The volume can be (statically) referenced by the `VolumeMount`
section of the (to be added) StatefulSets.
Signed-off-by: Pierangelo Di Pilato …

Add Pod webhook to inject contract ConfigMap for scheduling

---

test/e2e_new/features/broker_deleted_recreated.go
test/e2e_new/features/featuressteps/broker.go

Using `DeleteResources` isn't a good idea since that function deletes
some internal resources like RBAC (for eventshub), etc
Fixes #1510

TestBrokerDeletedRecreated deletes the broker only

---

control-plane/config/200-controller/100-config-kafka-leader-election.yaml
control-plane/config/200-controller/500-controller.yaml
control-plane/config/200-webhook/500-webhook.yaml
hack/update-checksums.sh

During tests, resources aren't reconciled fast enough since
chaos duck kills pods continuously and they need to acquire
leases faster.
Similar to https://github.com/knative-sandbox/eventing-kafka/pull/1068/files

Fix leader election configuration

---

control-plane/pkg/reconciler/consumergroup/evictor.go

Remove unnecessary pointer to evictor.evict method

---

control-plane/pkg/reconciler/source/v2/controllerv2.go

`FilteringResourceEventHandler` doesn't work without a
filter function and we don't need to filter Kafka source in
the Kafka source reconciler.
Part of #1537

Fix KafkaSource v2 controller handlers

---

hack/patches/defaulting-webhook-queue-name.patch
hack/update-deps.sh
vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go

See the linked issue in `TODO: ...`
this is causing errors like:
```
channel_impl.go:76: admission webhook "validation.webhook.kafka.eventing.knative.dev" denied the request: validation failed: invalid value: : spec.retentionDuration
```
In this case, the pod webhook is the leader over the resource webhook.

Use Git patches for pkg issue and E2E tests failures

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/channel_test.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/sink/kafka_sink_test.go
test/upgrade-tests.sh

Already merged for 1.2 in
https://github.com/knative-sandbox/eventing-kafka-broker/commit/adb87f1bb9351e2b6ff473585cfe76a9d60f2c5e
This PR fixes a problem that we have since we were deleting the
finalizer without deleting the topic accordingly, we were
returning nil in `FinalizeKind` which deletes the finalizer from
the resource.
Fixes #1798

Do not delete finalizer until the probe returns status not ready

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/ConsumerRecordContext.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/ResourceContext.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/ResponseFailureException.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/AbstractConsumerVerticleTest.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/IngressRequestHandlerImpl.java

See https://knative.dev/docs/eventing/observability/metrics/eventing-metrics/#broker-filter
Eventing Core uses `broker_name` and `trigger_name` for the tag
but since we have Trigger/KafkaSource/Subscription, I'm using
`name` and `consumer_name` instead.
- Align dispatcher metrics to Eventing core filter metrics
```release-note
```
**Docs**

Align dispatcher metrics to Eventing core filter metrics

---

control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/channel_test.go
control-plane/pkg/reconciler/testing/objects_channel.go

During channel tests, I'm seeing this exception:
```
SEVERE: Unhandled exception
java.lang.IllegalArgumentException: provide a target
at dev.knative.eventing.kafka.broker.dispatcher.impl.http.WebClientCloudEventSender.<init>(WebClientCloudEventSender.java:56)
at dev.knative.eventing.kafka.broker.dispatcher.main.ConsumerVerticleFactoryImpl.createConsumerRecordSender(ConsumerVerticleFactoryImpl.java:264)
at dev.knative.eventing.kafka.broker.dispatcher.main.ConsumerVerticleFactoryImpl.lambda$get$4(ConsumerVerticleFactoryImpl.java:162)
at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91)
at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
at …
```

KafkaChannel: check for empty subscriber URI

---

data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherTest.java

The assertion for dispatch latency metrics is flaky since the
sender is a mock that doesn't do anything.
This ends up producing a dispatch latency of 0.
- Simulate dispatch latency during unit tests

Simulate dispatch latency during unit tests

---

control-plane/pkg/prober/async_prober.go
control-plane/pkg/prober/async_prober_test.go
control-plane/pkg/prober/prober.go
control-plane/pkg/prober/prober_test.go
control-plane/pkg/prober/probertesting/mock_prober.go
control-plane/pkg/prober/probertesting/mock_prober_test.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/sink/kafka_sink.go

When we probe for resource status, we want to avoid probing the
pod when the status is in our expected status.
Before this patch, we had a hard-coded expected status of
`StatusReady`, which is wrong in the `FinalizeKind` case.

Add expected status to prober

---

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_lifecycle.go
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_validation.go
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_validation_test.go
control-plane/pkg/reconciler/channel/v2/channelv2.go
control-plane/pkg/reconciler/channel/v2/controllerv2.go
control-plane/pkg/reconciler/channel/v2/controllerv2_test.go

Part of #1537 (channelv2_test.go coming soon)
- Adding new KafkaChannel reconciler to create ConsumerGroup resources
```release-note
```
**Docs**

KafkaChannel Reconciler for ConsumerGroup scaling

---

control-plane/config/eventing-kafka-broker/200-controller/200-controller-cluster-role.yaml

Part of #1537 
Error seen:
```
{"level":"error","ts":"2022-02-17T21:13:18.048Z","logger":"kafka-broker-controller","caller":"controller/controller.go:566","msg":"Reconcile error","knative.dev/pod":"kafka-controller-7b48c89984-br9pr","knative.dev/controller":"knative.dev.eventing-kafka-broker.control-plane.pkg.reconciler.consumergroup.Reconciler","knative.dev/kind":"internal.kafka.eventing.knative.dev.ConsumerGroup","knative.dev/traceid":"5f8774e4-c895-4358-9c94-070851bd4b77","knative.dev/key":"default/331aa464-5ec1-4b0d-8a3c-1d591d64ea90","duration":0.0528905,"error":"failed to reconcile consumers: failed to remove consumer default/331aa464-5ec1-4b0d-8a3c-1d591d64ea90-gn2n2: consumers.internal.kafka.eventing.knative.dev …
```

Cluster role in controller for consumer deletion update

---

control-plane/pkg/reconciler/base/reconciler.go
control-plane/pkg/reconciler/consumer/consumer.go
control-plane/pkg/reconciler/consumer/consumer_test.go
control-plane/pkg/reconciler/testing/objects_common.go

When a consumer is removed and its binding dispatcher pod also
gone (autoscaled down), the config map is cleaned up.
Part of #1537

Consumer reconciler sets ConfigMap owner reference to dispatcher pod

---

control-plane/pkg/reconciler/consumergroup/evictor.go
control-plane/pkg/reconciler/consumergroup/evictor_test.go

Part of #1537
Fixes issue documented in https://github.com/knative-sandbox/eventing-kafka-broker/issues/1537#issuecomment-1041891419
- Modify consumer group status placement to remove evicted pod via Patch rather than Update

Evictor fix for patching consumergroup when removing evicted pod placement

---

control-plane/pkg/reconciler/consumer/consumer.go

Part of #1537 
Error seen:
```
{"level":"error","ts":"2022-02-22T21:54:58.608Z","logger":"kafka-broker-controller","caller":"consumer/reconciler.go:302","msg":"Returned an error","knative.dev/pod":"kafka-controller-55f849c8bb-qsb7w","knative.dev/controller":"knative.dev.eventing-kafka-broker.control-plane.pkg.reconciler.consumer.Reconciler","knative.dev/kind":"internal.kafka.eventing.knative.dev.Consumer","knative.dev/traceid":"fe362d16-4641-4650-89c4-bd8c7f102ba9","knative.dev/key":"default/c3824c49-ebe9-4d22-bcb5-022fc74f3bc4-ldwnf","targetMethod":"ReconcileKind","error":"failed to bind resource to pod: failed to get or create data plane ConfigMap knative-eventing/kafka-source-dispatcher-1: ConfigMap \"kafka-source-dispatcher-1\" is …
```

Adding non-empty ApiVersion and Kind values for CM ownerref (Consumer)

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/ResponseFailureException.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java

Wrong import for class `HttpResponse` leads to:
```
Feb 24, 2022 12:30:30 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.ClassCastException: class io.vertx.ext.web.client.impl.HttpResponseImpl cannot be cast to class java.net.http.HttpResponse (io.vertx.ext.web.client.impl.HttpResponseImpl is in unnamed module of loader 'app'; java.net.http.HttpResponse is in module java.net.http of loader 'platform')
at dev.knative.eventing.kafka.broker.dispatcher.impl.http.WebClientCloudEventSender.lambda$send$2(WebClientCloudEventSender.java:97)
at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91)
at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
at …
```

Fix class cast exception

---

control-plane/config/eventing-kafka-broker/200-webhook/400-webhook-pod-defaulting.yaml

`knative/pkg` webhook infra doesn't work with multiple webhooks
in the same mutating webhook configuration, so this patch move
the pod webhook configuration into its own separate manifest.
Part of #1537
- Move pod mutating webhook configuration to its own manifest

Move pod mutating webhook configuration to its own manifest

---

control-plane/pkg/reconciler/consumer/controller.go
control-plane/pkg/reconciler/consumergroup/controller.go

To keep resource statuses in sync with the actual current state, we
need to global resync consumer groups when the statefulsets changes.
Part of #1537

Global resync consumers and consumergroups on statefulset changes

---

.github/workflows/kind-e2e.yaml
hack/create-kind-cluster.sh

Bump k8s versions to the latest 2 versions.
Drop verbose logging since doing through logs to 
find a failed test in GH actions is painful since 
there are all logs even of succeeded tests.
Fixes #1067

Bump k8s versions in KinD workflows and remove verbose logging

---

hack/control-plane.sh
hack/tools.go
vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
vendor/knative.dev/pkg/apiextensions/storageversion/migrator.go
vendor/modules.txt

As per title.
storage version migrator wasn't included in the tools.go file:
```
_ "knative.dev/pkg/apiextensions/storageversion/cmd/migrate"
```

Failed to build storage version migrator

---

data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java

As per title. This test is flaky probably because slow fsyncs

Increase timeout for data plane test

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/testing/objects_broker.go

Instead of adding a finalizer to the ConfigMap, we can record
the ConfigMap data in the Broker status so that we can re-build
the ConfigMap even when the ConfigMap is deleted first.
Fixes #1970
```release-note
Support brokers with long namespace and name values.
```

Use broker status annotations to stamp ConfigMap reference

---

test/upgrade/postupgrade.go

This helps catch bugs like https://github.com/knative-sandbox/eventing-kafka-broker/pull/1965.
- Verify `kafka-controller-post-install` job
- Verify `knative-kafka-storage-version-migrator` job

Verify post-install jobs succeess during post-upgrade tests

---

control-plane/pkg/reconciler/broker/broker.go

We removed the "add finalizer to the ConfigMap logic" in
https://github.com/knative-sandbox/eventing-kafka-broker/pull/1971
and we kept the "remove the ConfigMap finalizer" in `FinalizeKind`.
However, in order to remove the ConfigMap finalizer from every
existing Broker that won't be deleted in the time span going from
1.3 to whatever release we remove the logic to remove the finalizer,
we should remove the finalizer in `ReconcileKind` too.

Remove ConfigMap finalizer during reconcile

---

control-plane/config/eventing-kafka-broker/200-controller/200-controller-cluster-role.yaml

This is needed to be able to set the owner reference of the
ConfigMaps to their associated pods.

Add permission to set ConfigMap owner references to controller

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticleTest.java

By only polling for new records when the aggregate future for the
entire batch completes we are waiting too much on the responses
(which is slow).
Since the goal is to avoid having too many in-flight requests
we can poll for new records as soon as the number of in-flight requests
is under `max.poll.records`.
We are not forcing the dispatcher to send less than `max.poll.records`
requests because we don't want to keep records in memory by waiting
for responses, which means that we might have no more than
`2 * max.poll.records` requests in flight.

Poll for new records when `max.poll.records` limit isn't reached

---

data-plane/config/channel/100-config-kafka-channel-data-plane.yaml

Fixes #
- remove ignored configuration option, since the control plane does set this
```release-note
```
**Docs**

Remove auto offset setting for KafkaChannel, since the control plane does init the actual offset

---

control-plane/pkg/reconciler/consumer/consumer.go
control-plane/pkg/reconciler/source/v2/sourcev2.go
control-plane/pkg/reconciler/source/v2/sourcev2_test.go

As per title.
These values are the same we use in the existing
KafkaSource in this repository

Config retries for KafkaSource scheduler based

---

control-plane/pkg/reconciler/consumer/consumer.go

Consumer cleanup of unused field

---

control-plane/config/eventing-kafka-broker/200-controller/200-controller-cluster-role.yaml

Error previously seen:
```
type: 'Warning' reason: 'InternalError' failed to bind resource to pod: failed to get or create data plane ConfigMap knative-eventing/kafka-source-dispatcher-2: configmaps \"kafka-source-dispatcher-2\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>","knative.dev/pod":"kafka-controller-bfcdc9d66-mfkrh"}
```
Previous changes in https://github.com/knative-sandbox/eventing-kafka-broker/pull/2024 weren't sufficient for the pods to fully come up.
Part of #1537

Add more permissions to set Pod finalizers for controller 

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/channel_test.go
control-plane/pkg/reconciler/channel/v2/channelv2.go
control-plane/pkg/reconciler/channel/v2/channelv2_test.go
control-plane/pkg/security/config.go
control-plane/pkg/security/config_test.go
test/e2e-common.sh

Fixes #
- Make it possible to specify auth secret namespace in configmap
- This is needed for KafkaChannel migration because:
- It is possible to specify the auth secret namespace in the consolidated
- We will read the namespace in the migration process and just set it on the new configmap
- Default behaviour is as before: secret namespace is the configmap's namespace
```release-note
```
**Docs**

Make it possible to specify auth secret namespace in configmap

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/AsyncCloseable.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/ResponseToKafkaTopicHandler.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/BaseConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java

Sometimes when deleting resources, which end up stopping
associated data plane components the lifecycle might produce
errors (like commiting offsets after a consumer has been closed)
This PR rework the overall stop lifecycle of dispatcher
components.
Fixes https://github.com/knative-sandbox/eventing-kafka-broker/pull/2012#issuecomment-1075112440

Improve dispatcher components stop lifecycle

---

control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-scheduler.yaml

`EvenPodSpread` is specified to schedule vreplicas evenly across dispatcher pods which is very important for an equal event consumption from Kafka topic. 
`EvenPodSpread` can both be specified as a filter (predicate) OR as a scorer (priority). When specified as a predicate, the scheduler is highly constrained by the skew factor and requires a large number of pods (in some scenarios) which is not very friendly for small clusters (pods that have low capacity are filtered out and not used). Instead, we can use this plugin to score pods and schedule onto higher score pods. 
Changed `EvenPodSpread` to a priority instead of a predicate for the default config scheduler in this repo. 
Either can work depending on the cluster and the requirements. …

HA Scheduler config map update

---

test/config/monitoring.yaml
test/e2e-common.sh

Fixes issues like this one: https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka-broker/2038/upgrade-tests_eventing-kafka-broker_main/1511168436032507904
- Actually use test config-tracing
- Increase Zipkin resources to handle the increased load in upgrade tests
```release-note
```
**Docs**

Enable Zipkin tracing for upgrade tests

---

data-plane/config/broker/500-dispatcher.yaml
data-plane/config/brokerv2/500-dispatcher.yaml
data-plane/config/channel/500-dispatcher.yaml
data-plane/config/channelv2/500-dispatcher.yaml
data-plane/config/source/500-dispatcher.yaml
data-plane/config/sourcev2/500-dispatcher.yaml

The dispatcher is using the `/metrics` endpoint to signal liveness
and readiness, however, responding with metrics involves expensive
operations [1] [2] (allocations and CPU).
In this patch, I'm migrating readiness and liveness probes
to use a `TCP` probe against the same metrics server but
avoiding the above-mentioned expensive operations.
[1] https://github.com/micrometer-metrics/micrometer/blob/30c8a1bf1b0bf867232630b0dcd2b272975b68a2/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java#L101-L154
[2] https://github.com/prometheus/client_java/blob/master/simpleclient_common/src/main/java/io/prometheus/client/exporter/common/TextFormat.java

Expensive metrics endpoint for dispatcher liveness and readiness probe

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java

As discussed previously, the default timeout of 10 seconds isn't
sometimes enough to even start a Knative Service.
Using 10 minutes will avoid overriding the timeout with
`spec.delivery.timeout` in most of the use cases.
- Increase default timeout to 10 minutes
```release-note
The default request timeout is 10 minutes now, it was previously set to 10 seconds.
It can be overridden using `spec.delivery.timeout` on `Broker`, `Trigger`, `KafkaChannel` and `Subscription`.
```

Increase default timeout to 10 minutes

---

control-plane/config/eventing-kafka-broker/100-source/config-kafka-source-defaults.yaml

This ConfigMap is used by the KEDA integration.

Add ConfigMap knative-eventing/config-kafka-source-defaults

---

control-plane/cmd/post-install/kafka_source_deleter.go
control-plane/config/post-install/200-controller-cluster-role.yaml

The new `KafkaSource` doesn't support `KafkaBinding` so this
`ClusterRoleBinding` can be removed as part of the migration.

Remove KafkaBinding's podspecable ClusterRoleBinding

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java

Multiple async `poll` calls can lead to a large number of records
loaded into memory and dispatched to subscribers.
In this PR, I'm limiting the number of in-flight poll requests to 1.

Limit the number of poll calls for unordered delivery

---

test/upgrade/upgrade_test.go

This is similar to https://github.com/knative/eventing/pull/6331 . When the Eventing changes propagate to this repo we'll need to ensure cleanup of Zipkin port-forwarding. This PR fixes that.
- Clean up Zipkin port-forwarding only, when the upgrade test suite ends
```release-note
```
**Docs**

Clean up Zipkin tracing only once in upgrade tests

---

data-plane/config/broker/500-dispatcher.yaml
data-plane/config/broker/500-receiver.yaml
data-plane/config/brokerv2/500-dispatcher.yaml
data-plane/config/channel/500-dispatcher.yaml
data-plane/config/channel/500-receiver.yaml
data-plane/config/channelv2/500-dispatcher.yaml
data-plane/config/sink/500-receiver.yaml
data-plane/config/source/500-dispatcher.yaml
data-plane/config/sourcev2/500-dispatcher.yaml

To spread receivers and dispatchers across zones for HA.
Part of #1537 and Broker HA

Topology spread constraints on zones and anti-affinity for receivers and dispatchers

---

control-plane/cmd/post-install/kafka_channel_post_migration_deleter.go

Fixes #
- Wait 10 mins before deleting the consolidated channel dataplane
- To allow DNS resolution for the clients
-
```release-note
```
**Docs**

Wait 10 mins before deleting the consolidated channel dataplane

---

control-plane/pkg/reconciler/channel/channel.go

- As per title: There is no reason to do an error log, since we do have a default value to be used. Going with debug to reduce verbosity...
```release-note
```
**Docs**

Going with debug to reduce verbosity for retention duration default usage

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java

Vert.x's client, server and verticles metrics adds a lot of
allocations and their metrics exposed add little value in a
kubernetes environment or in our case.
Fixes #
- Disable unnecessary metrics
```release-note
`vertx_*` metrics have been removed since they were causing unnecessary allocations.
```

Disable unnecessary metrics

---

test/e2e-common.sh

Error when running teardown-infra to teardown Knative Eventing resources.
```
>> Delete Knative Eventing from HEAD
~/knative/eventing-kafka-broker ~/knative/eventing-kafka-broker
./hack/../test/e2e-common.sh: line 67: cd: eventing: No such file or directory
ERROR: Failed to set up Eventing
```
-
-
-
```release-note
```
**Docs**

Fix for teardown eventing

---

control-plane/pkg/prober/async_prober.go
control-plane/pkg/prober/async_prober_test.go
control-plane/pkg/prober/prober.go
control-plane/pkg/prober/prober_test.go
control-plane/pkg/reconciler/broker/controller.go
control-plane/pkg/reconciler/channel/controller.go
control-plane/pkg/reconciler/channel/v2/controllerv2.go
control-plane/pkg/reconciler/sink/controller.go
data-plane/config/broker/500-receiver.yaml
data-plane/config/channel/500-receiver.yaml
data-plane/config/sink/500-receiver.yaml

Istio doesn't work well when there is pod to pod communication.
Fixes #2107
- Prober targets service instead of pods directly
```release-note
Receiver's prober targets services instead of pods directly to allow components to be part of an Istio mesh
```

Prober targets service instead of pods directly

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/OrderedAsyncExecutor.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerMessageHandler.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/OrderedAsyncExecutorTest.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverEnvTest.java

The ordered delivery verticle had a complicated logic
to perform the next poll.
Now, it's more "Vert.x idiomatic".
Tested with some perf test runs at ~1.5k events/s and latency is <1s.
Part of https://github.com/knative-sandbox/eventing-kafka-broker/issues/2125
- Cleanup ordered delivery verticle

Clean up ordered delivery verticle

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/testing/objects_broker.go

Fixes #
-  addressing todo and remove remove cm finalizer, since it was already released
```release-note
```
**Docs**

[clean up] Removing config map finalizer left overs

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/AsyncCloseable.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/ResponseToKafkaTopicHandler.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStore.java

The binding and closing process of the metrics reporter is blocking,
so that blocks our data plane verticle deployer.

Bind and close Kafka client metrics provider asynchronously

---

control-plane/pkg/prober/async_prober.go
control-plane/pkg/prober/async_prober_test.go
control-plane/pkg/prober/prober.go
control-plane/pkg/prober/prober_test.go
control-plane/pkg/reconciler/broker/controller.go
control-plane/pkg/reconciler/channel/controller.go
control-plane/pkg/reconciler/sink/controller.go
data-plane/config/broker/500-receiver.yaml
data-plane/config/channel/500-receiver.yaml
data-plane/config/sink/500-receiver.yaml

Manual cherry pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2159
```release-note
Receiver's prober targets services instead of pods directly to allow components to be part of an Istio mesh
```

[release-1.2] Prober targets service instead of pods directly

---

data-plane/config/broker/500-dispatcher.yaml
data-plane/config/broker/500-receiver.yaml
data-plane/config/brokerv2/500-dispatcher.yaml
data-plane/config/channel/500-dispatcher.yaml
data-plane/config/channel/500-receiver.yaml
data-plane/config/channelv2/500-dispatcher.yaml
data-plane/config/sink/500-receiver.yaml
data-plane/config/source/500-dispatcher.yaml
data-plane/config/sourcev2/500-dispatcher.yaml

Sometimes there are OOM errors when memory limits are set,
so by specifying this flag we get:
- a readable report of what happened
- the pod is restarted instead of leaving the JVM in a broken
state

Add -XX:+CrashOnOutOfMemoryError flag

---

test/e2e_new/resources/kafkasink/kafkasink_test.go

Fixes #
- :broom: removing deprecated API calls
-
-
```release-note
```
**Docs**

Remove calling 'ExecuteLocalYAML', b/c it is deprecated

---

hack/data-plane.sh

Readonly variables inside functions are globally readonly, so
we cannot execute the function twice.
Fixes maybe nightly release errors.

Use local instead of readonly

---

hack/data-plane.sh

Fixes #2137
Build ./hack/run.sh fails with sed error in MacOS 
- use builtin MacOS sed in data-plane script - that should *always* work even in gsed is not installed

use builtin MacOS sed in data-plane script

---

control-plane/cmd/post-install/kafka_channel_post_migration_deleter.go

Fixes #
- the `config-kafka` CM was not removed
-
-
```release-note
```
**Docs**

Remove old Config Kafka CM for old/legacy channel

---

control-plane/config/post-install/200-controller-cluster-role.yaml

Fixes #
- Fix RBAC issue
- Post migration deleter was not able to delete some configmaps
-
```release-note
```
**Docs**

Fix RBAC for deletion of configmaps

---

control-plane/pkg/kafka/client.go
go.mod
vendor/modules.txt

Sarama metrics consume a lot of memory but we don't use/expose them.
Fixes #2226

Disable Sarama metrics since they are not exposed

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/testing/objects_broker.go
control-plane/pkg/reconciler/testing/objects_common.go

Fixes #977 
- adding support for `kafka.eventing.knative.dev/external.topic` annotation for external topic usage
```release-note
With the `kafka.eventing.knative.dev/external.topic` annotation it is possible to use an externally managed Apache Kafka topic for the broker usage
```
**Docs**

Adding annotation to drive the name of the backing topic

---

control-plane/pkg/kafka/client.go
go.mod
vendor/modules.txt

Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2225
Sarama metrics consume a lot of memory but we don't use/expose them.

[release-1.4] Disable Sarama metrics since they are not exposed (#2225)

---

data-plane/THIRD-PARTY.txt
data-plane/dispatcher/pom.xml
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticleTest.java
data-plane/pom.xml

Build on top of https://github.com/knative-sandbox/eventing-kafka-broker/pull/1425
Part of #2125
- Add rate limiter to ordered consumer verticle
**Docs**

Add rate limiter to ordered consumer verticle 

---

docs/channel/README.md

Fixes #
- Fix backtick in Channel docs
-
-
```release-note
```
**Docs**

Fix backtick in Channel docs

---

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_types.go
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_validation.go

Related to #2244 
Fixes a problem in #2219
Part of #1537

Minor fix for missing allowed key type

---

control-plane/pkg/reconciler/consumergroup/controller.go

Controller logs were getting filled with info logs for channel & trigger due to absence of v2 sts dispatchers (that will be added only when we move to HA v2 version). We currently only have source HA STS dispatchers that run the replica scheduler. So commenting this out temporarily.
```
{"level":"info","ts":"2022-06-09T07:52:03.927Z","logger":"kafka-broker-controller","caller":"state/state.go:178","msg":"failed to get statefulset","knative.dev/pod":"kafka-controller-7bcd565879-9lc6c","error":"statefulsets.apps \"kafka-channel-dispatcher\" not found"}
{"level":"info","ts":"2022-06-09T07:52:03.927Z","logger":"kafka-broker-controller","caller":"statefulset/autoscaler.go:122","msg":"error while refreshing scheduler state (will retry){error 26 0 …
```

Do not create scheduler for channel & trigger (till we move to v2)

---

control-plane/pkg/prober/async_prober.go
control-plane/pkg/prober/async_prober_test.go

When resource readiness is delayed due to the latency of the
ConfigMap propagation, the controllers might enter into a spinning
loop trying to probe receivers for readiness.

Use a constant backoff delay for probing resource ingresses

---

data-plane/config/broker/100-config-kafka-broker-data-plane.yaml
data-plane/config/channel/100-config-kafka-channel-data-plane.yaml
data-plane/config/sink/100-config-kafka-sink-data-plane.yaml
data-plane/config/source/100-config-kafka-source-data-plane.yaml

Big timeouts as before end up parking threads unnecessarily, this is
especially evident when deleting a resource end up having consumers
polling topic/partitions that don't exist anymore until timeouts
are reached.

Reduce default consumer and producer timeouts

---

hack/data-plane.sh

Related to #1968 
Deploying KafkaSource bundle was failing with error:
```
/Users/ansuvarghese/knative/eventing-kafka-broker/hack/data-plane.sh: line 70: ./mvnw: No such file or directory
```

Minor change for KafkaSource bundle setup with arm64

---

hack/data-plane.sh
hack/label.sh

Fix errors during nightly builds [1]
[1] https://prow.knative.dev/view/gs/knative-prow/logs/nightly_eventing-kafka-broker_main_periodic/1538816108792909824

`TAG` is readonly during the release

---

control-plane/pkg/reconciler/base/reconciler.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/broker/controller.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/channel_test.go
control-plane/pkg/reconciler/channel/controller.go
control-plane/pkg/reconciler/channel/v2/channelv2.go
control-plane/pkg/reconciler/channel/v2/channelv2_test.go
control-plane/pkg/reconciler/channel/v2/controllerv2.go
control-plane/pkg/reconciler/consumer/consumer.go
control-plane/pkg/reconciler/sink/controller.go
control-plane/pkg/reconciler/sink/kafka_sink_test.go
control-plane/pkg/reconciler/trigger/controller.go
control-plane/pkg/reconciler/trigger/trigger_test.go

Fixes #
- Better semantics, as we're not going to talk about system namespace anymore but talk about the namespace that the reconciler instance is going to take care of
- Prefactoring for KafkaBroker with dataplane-per-namespace
```release-note
```
**Docs**

[Prefactoring] Rename `reconciler.SystemNamespace` to `reconciler.DataPlaneNamespace`

---

control-plane/pkg/reconciler/channel/v2/channelv2_test.go

Fixes #
- Do not use `system.Namespace()` in reconciler unit tests
- Unit tests on GH actions failed because of that
- Introduced by https://github.com/knative-sandbox/eventing-kafka-broker/pull/2356
```release-note
```
**Docs**

Do not use `system.Namespace()` in reconciler unit tests

---

control-plane/config/post-install/200-storage-version-migrator-cluster-role.yaml
control-plane/config/post-install/500-storage-version-migrator.yaml

Fixes #
- adding `kafkasinks.eventing.knative.dev` to `storage-version-migrator` as a NOOP
```release-note
```
**Docs**

Adding KafkaSink to storage version migrator

---

control-plane/pkg/reconciler/trigger/controller.go
control-plane/pkg/reconciler/trigger/controller_test.go
control-plane/pkg/reconciler/trigger/trigger.go
control-plane/pkg/reconciler/trigger/trigger_test.go

Fixes #
- Pass brokerClass to Trigger reconciler instead of hardcoding it
- Prefactoring for KafkaBroker with dataplane-per-namespace
-
```release-note
```
**Docs**

[Prefactoring] Pass brokerClass to Trigger reconciler instead of hardcoding it

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/broker/controller.go

Fixes #
- Recompute broker `IngressHost` every time - needed for future dynamic dataplanes; instead of computing it once and setting it as a struct field.
- Computing: string building for the ingress service name
- Prefactoring for KafkaBroker with dataplane-per-namespace
```release-note
```
**Docs**

[Prefactoring] Recompute broker `IngressHost` every time - needed for future dynamic dataplanes

---

data-plane/config/brokerv2/500-dispatcher.yaml
data-plane/config/channelv2/500-dispatcher.yaml
data-plane/config/source/500-dispatcher.yaml

- use `HTTP` instead of _raw_ `TCP` for readinessProbe of source and V2 dispatchers 
```release-note
```
**Docs**

Use HTTP for readinessProbe

---

data-plane/config/brokerv2/500-dispatcher.yaml
data-plane/config/channelv2/500-dispatcher.yaml
data-plane/config/source/500-dispatcher.yaml

Part of #2203 
- Increasing RAM values from 25% (default) to `-XX:InitialRAMPercentage=70.0 -XX:MinRAMPercentage=70.0 -XX:MaxRAMPercentage=70.0`

Setting memory parameters for containers since default is low

---

control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml
data-plane/THIRD-PARTY.txt
data-plane/dispatcher/pom.xml
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImplTest.java
data-plane/pom.xml

Fixes #2345
See for more details https://github.com/vert-x3/vertx-circuit-breaker/issues/58#issuecomment-1161414029 for the testing of this patch.
- Remove vertx-circuit-breaker since it's overkill for our use case
- Move to a custom retry logic
```release-note
Fix high memory usage for dispatcher pods under load
```

Fix high memory usage for dispatcher pods

---

control-plane/config/eventing-kafka-broker/100-sink/100-kafka-sink.yaml
control-plane/pkg/apis/eventing/v1alpha1/kafka_sink_defaults.go
control-plane/pkg/apis/eventing/v1alpha1/kafka_sink_defaults_test.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/sink/kafka_sink_test.go
test/e2e_new/resources/kafkasink/kafkasink_test.go

Fixes #
- align the `KafkaSink` with the rest of the components and default to CE binary mode
```release-note
The KafkaSink now uses CloudEvent binary content mode as default
```
**Docs**
* PR for docs: https://github.com/knative/docs/pull/5084

KafkaSink is binary now

---

.gitignore

Without the `/` it will ignore files with the same name in all
directories

Ignore artifacts files only in the root directory

---

data-plane/dispatcher/pom.xml
data-plane/receiver/pom.xml

I'm getting StikyAssignor ClassNotFound when building the data plane
without `Jib` by running `./mvnw package` and using the jar
`data-plane/dispatcher/target/dispatcher-1.0-SNAPSHOT.jar`.

Force include all Kafka clients classes

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java

Without considering `max.poll.records` in the calculation of
the `max.poll.interval.ms` we might cause unnecessary rebalances
since without this patch slow consumers might trigger a rebalance
at every handled record (when their processing time ~= timeout).
```release-note
When using ordered delivery with slow consumers, unnecessary consumer group rebalances might be triggered, which causes higher e2e latency and increased duplicates.
```
/kind bug

Perform `max.poll.interval.ms` considering `max.poll.records`

---

data-plane/config/broker/100-config-kafka-broker-data-plane.yaml
data-plane/config/channel/100-config-kafka-channel-data-plane.yaml
data-plane/config/source/100-config-kafka-source-data-plane.yaml

During some perf-testing for KafkaSource, we've observed
that the Vert.x's default for `maxPoolSize` is too low
for parallel event dispatch.
This is just changing the default values to improve the out
of the box experience and the common use case, people can
still change it.

Increase default HTTP client max pool size

---

go.mod
test/e2e_new/main_test.go
test/e2e_new/tracing_test.go
test/e2e_new_channel/main_test.go
test/e2e_new_channel/tracing_test.go
test/pkg/tracing/tracing.go
test/pkg/tracing/zipkin.go
third_party/VENDOR-LICENSE/go.opentelemetry.io/otel/LICENSE
third_party/VENDOR-LICENSE/go.opentelemetry.io/otel/trace/LICENSE
vendor/knative.dev/eventing/test/rekt/resources/svc/service.go
vendor/knative.dev/eventing/test/rekt/resources/svc/service.yaml
vendor/modules.txt

Fixes #[585](https://github.com/knative-sandbox/eventing-kafka-broker/issues/585)
This PR still has [vendor/knative.dev/pkg/test/tracing/traces.go](https://github.com/knative-sandbox/eventing-kafka-broker/compare/main...mgencur:eventing-kafka-broker:broker_tracing_tests_main?expand=1#diff-5c620242fd33f18c3242b639e9eb8ac08720d16249744a3ba1ac8f1d5a9ede42) in vendor directory. It's a copy of [this file from knative/eventing](https://github.com/knative/eventing/blob/main/test/conformance/helpers/tracing/traces.go) with slight changes. I plan to send a PR to knative.dev/pkg and then vendor this file to this repository.
EDIT: Sent https://github.com/knative/eventing/pull/6446 which was merged and this PR has been rebased.
- Enable port-forwarding to Zipkin pod
- Send an event through Kafka …

Tracing tests for Kafka Broker and Channel

---

data-plane/config/broker/100-config-kafka-broker-data-plane.yaml
data-plane/config/channel/100-config-kafka-channel-data-plane.yaml
data-plane/config/source/100-config-kafka-source-data-plane.yaml

Having very high values by default requires using too much memory
when there are many resources and might also cause a higher chance
to have duplicates.
```release-note
The default max.partition.fetch.bytes is `65536` and `max.poll.records` is 50.
```

Reduce default max.poll.records and max.partition.fetch.bytes

---

data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherTest.java

The processing latency is sometimes too small that the distribution
produces 0 anyway.

Fix flaky processing latency assertion

---

data-plane/config/broker/100-config-kafka-broker-data-plane.yaml
data-plane/config/channel/100-config-kafka-channel-data-plane.yaml
data-plane/config/source/100-config-kafka-source-data-plane.yaml

Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/9f5409c290291a4c2113ced614e649e7d9126b57

[release-1.6] Reduce default max.poll.records and max.partition.fetch.bytes (#2456)

---

control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/sink/kafka_sink_test.go
control-plane/pkg/reconciler/testing/objects_sink.go

`contentMode` wasn't passed to the contract, so
the data plane would produce binary events regardless of
the provided contentMode.
- Pass content mode to contract in KafkaSink reconciler
```release-note
Specify a different `contentMode` on KafkaSink objects wasn't having any effect, now structured or binary content mode are properly handled.
```

Fix KafkaSink structured content mode

---

data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStore.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStoreTest.java

Part of https://github.com/knative/eventing/issues/6467
```release-note
Kafka Broker and KafkaSink ignore a trailing slash in the HTTP path.
```

Ignore trailing slashes for path-based routing

---

test/scripts/first-event-delay.sh

This test sometimes fails due to [1].
[1] https://github.com/knative/pkg/issues/1509

Retry webhook EOF errors

---

control-plane/config/eventing-kafka-broker/200-controller/200-controller-cluster-role.yaml

In OpenShift, I'm getting the above error when creating a
KafkaSource without the patch.

Fix ownerRef cannot be set on resources you cannot delete

---

test/pkg/addressable/send.go

Running them in separate t.Run functions causes issues such as the
following one because events might be sent after the t.Run ends since
they run in separate go routines in background:
panic: Fail in goroutine after
TestKafkaSinkV1Alpha1AuthPlaintext/1/send_event_0 has completed
goroutine 6809 [running]:
testing.(*common).Fail(0xc002b5c340)
/root/.gvm/gos/go1.17.8/src/testing/testing.go:710 +0x1b4
testing.(*common).FailNow(0xc002b5c340)
/root/.gvm/gos/go1.17.8/src/testing/testing.go:732 +0x2f
testing.(*common).Fatalf(0xc00437a000, {0x2b71c16, 0x22}, {0xc004acfbd8,
0x3, 0x3})
/root/.gvm/gos/go1.17.8/src/testing/testing.go:830 +0x85
knative.dev/eventing/test/lib.(*Client).SendEvent(0xc0035c2d20,
{0x3137bb0, 0xc0000e0008}, {0xc004096420, 0x11}, {0xc00437a000, 0x56},
{{0x319fac0, …

SendN sends events in a common t.Run

---

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_lifecycle.go
control-plane/pkg/reconciler/consumergroup/consumergroup.go
control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
control-plane/pkg/reconciler/testing/objects_consumer.go

When a Consumer wasn't ready, we would get a generic error
on the user-facing API which isn't optimal to debug the issue.

Propagate non-ready consumers top level condition in ConsumerGroup

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java
test/e2e_new/dls_test.go

- improve Webclient sender for non-retry errors
- adding tests
```release-note
```
**Docs**

Better handle error response on WebClientCloudEventSender

---

test/e2e_new/dls_test.go

Enable the tests that got commented out, by accident

---

control-plane/pkg/reconciler/base/reconciler.go
control-plane/pkg/reconciler/base/reconciler_test.go
control-plane/pkg/reconciler/testing/objects_broker.go
control-plane/pkg/reconciler/testing/objects_channel.go
control-plane/pkg/reconciler/testing/objects_sink.go
control-plane/pkg/reconciler/testing/objects_source.go

See https://github.com/kubernetes/client-go/issues/815
I'm using the logic used by https://pkg.go.dev/k8s.io/kubernetes/pkg/api/v1/pod#IsPodReady
but that function is not in a library package so it can't be reused.

`pod.Status.Phase == apiv1.PodRunning` is not a good way to test if pods are Running

---

test/pkg/kafka/verify_num_partitions_replication.go

Set TerminationMessagePolicy=FallbackToLogsOnError for partition-replication-factor-verifier so that we can see the failure in the pod status
Fixes #
- Set TerminationMessagePolicy=FallbackToLogsOnError for partition-replication-factor-verifier so that we can see the failure in the pod status
- Otherwise we just see the pod crash and there are no logs for the pod
-
```release-note
```
**Docs**

Set TerminationMessagePolicy=FallbackToLogsOnError in a test image

---

control-plane/pkg/reconciler/broker/broker.go

- Move code that stores Broker Configmap on status annotation to a separate function
- In addition slight rename on the function that rebuilds the config from the status annotations

nit: refactoring: Move code that stores Broker Configmap on status annotation to a separate function

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go

- reword a misleading error message, as it lacked the context of creating the `topicConfig`
```release-note
```
**Docs**

nit: Reword misleading error message

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/testing/objects_broker.go
test/e2e_new/broker_test.go
test/e2e_new/features/broker_deleted_recreated.go

Fixes #2566
- When finalizing the broker and the actual configuration can not be correctly received (e.g. an empty ConfigMap), we move on, to prevent blocking the finalization of the broker, as without deletion is stuck
- Adding a rekt test for the fix 
-
```release-note
When finalizing the broker and the actual configuration can not be correctly received (e.g. an empty ConfigMap), we move on, to prevent blocking the finalization of the broker, as without deletion is stuck
```
**Docs**

Checking if received config has data or not

---

control-plane/cmd/webhook-kafka/main.go
control-plane/pkg/apis/eventing/v1/broker_validation.go
control-plane/pkg/apis/eventing/v1/broker_validation_test.go

Fixes #2537
- Register the webhook for `Broker` resource in our webhook. We only had a validation callback before but it was never called because we didn't register the type and that was not added in the admissioncontroller.
- When I simply register the `Broker` resource with the `eventingv1.Broker` type, the webhook automatically calls `Validate()` of that type. That's not good because in that case our webhook would also validate the brokers from other classes.
- Introduced a new stub, `BrokerStub` that doesn't call the `Validate()` on `eventingv1.Broker` type. I only added the validations that are specific to our classes. We don't care about the general things (like missing config, etc) here and just leave the upstream webhook to its job. This way we would properly see the `admission …

Proper webhook registration for KafkaBroker

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherTest.java
test/e2e_new/dls_extensions_test.go

Fixes #2594 
- Avoiding "invalid" HTTP header values for CE extension, we encode the actual data of the `knativeerrordata` extension.
- updated unit and reconciler tests to reflect the base64 encoding
- added a new case for the returning http error and webpage...
```release-note
We are doing base64 encoding for the value of the `knativeerrordata`, to avoid issues with adding the data to the HTTP header, when the message is delivered to the deadlettersink. Consumers of the `knativeerrordata` must decode it in case they are interested in it. 
```
**Docs**

Doing base 64 encoding of the data

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/controller.go
test/e2e_new/broker_test.go
test/e2e_new/features/broker_deleted_recreated.go

Fixes #2569
- If apache kafka is not reachble, we do not longer block the finalization of the broker 
```release-note
If apache kafka is not reachble, we do not longer block the finalization/deletion of the knative kafka broker 
```
**Docs**

Check for kafka/network errors on finalizeKind, to unblock the borker deletion if the cluster is not reachable

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/IngressReconcilerListener.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/metrics/MetricsTest.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/IngressRequestHandler.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/IngressRequestHandlerImpl.java

Keeping meters for deleted resources around causes the
metrics endpoint to take a long time to respond with metrics
and it is also a waste of memory.
- Remove meters of deleted resources
```release-note
Remove metrics associated with deleted resources from data plane pods.
```

Remove meters of deleted resources

---

control-plane/pkg/keda/keda.go

Fix for new code in #2607 
/cc @pierDipi

KEDA as scaling library minor fix in TriggerAuth gen

---

control-plane/pkg/apis/eventing/v1alpha1/kafka_sink_types.go

- In #2391 we changed the default of the `ContentMode` for the `KafkaSink` CRD, but we did not change the doc on the actual `types` file
```release-note
```
**Docs**

NIT: Reflect that the ContentMode for KafkaSink is binary

---

control-plane/config/eventing-kafka-source/200-controller/500-controller.yaml

Error in source-controller reported:
```
kew\": 2}"},{"Name":"LowestOrdinalPriority","Weight":2,"Args":null},{"Name":"EvenPodSpread","Weight":2,"Args":"{\"MaxSkew\": 2}"}]}}
{"level":"info","ts":"2022-09-13T20:40:01.357Z","logger":"kafka-source-controller","caller":"consumergroup/controller.go:257","msg":"Schedulers policy registration","commit":"fecf5c3-dirty","knative.dev/pod":"kafka-source-controller-547955954b-g4445","configmap":"config-kafka-descheduler","policy":{"Predicates":[],"Priorities":[{"Name":"RemoveWithEvenPodSpreadPriority","Weight":10,"Args":"{\"MaxSkew\": 2}"},{"Name":"RemoveWithAvailabilityZonePriority","Weight":10,"Args":"{\"MaxSkew\": 2}"},{"Name":"RemoveWithHighestOrdinalPriority","Weight":2,"Args":null}]}}
panic: …
```

Fix for "CONSUMER_CONTRACT_CONFIG_MAP_FORMAT missing value" in source-controller

---

.github/workflows/kind-e2e.yaml
control-plane/cmd/kafka-controller/main.go
control-plane/pkg/reconciler/broker/namespaced_broker.go
control-plane/pkg/reconciler/broker/namespaced_controller.go
control-plane/pkg/reconciler/trigger/namespaced_controller.go
control-plane/pkg/reconciler/trigger/namespaced_trigger.go
test/e2e-tests.sh
test/e2e_broker/broker_redelivery_test.go
test/e2e_broker/broker_trigger_sink_test.go
test/e2e_broker/broker_trigger_test.go
test/e2e_broker/conformance/control_plane_conformance_test.go
test/e2e_new/broker_conformance_test.go
test/e2e_new/broker_not_ready_test.go
test/e2e_new/broker_test.go
test/e2e_new/dls_test.go
test/e2e_new/features/broker_deleted_recreated.go
test/e2e_new/features/featuressteps/broker.go
test/e2e_new/tracing_test.go
test/pkg/broker/broker.go
test/reconciler-tests.sh

Fixes #
- Enable namespaced broker again
- Adjust tests for the new validation rules per webhook (no cross namespace spec.config)
- 
```release-note
```
**Docs**

Enable namespaced broker again

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerImpl.java

When egress changes are detected log the egress info
at debug level instead of logging egresses that weren't
changed at info.

Remove noisy log lines "Nothing changed" at info level

---

control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml
data-plane/config/broker/500-dispatcher.yaml
data-plane/config/broker/500-receiver.yaml
data-plane/config/channel/500-dispatcher.yaml
data-plane/config/channel/500-receiver.yaml
data-plane/config/sink/500-receiver.yaml

This gives the scheduler a hint on scheduling receiver
and dispatcher pods.
```release-note
Add resource requests to all pods based on perf testing.
```

Add resource requests for every workload

---

control-plane/pkg/apis/eventing/v1/broker_validation.go
control-plane/pkg/apis/eventing/v1/broker_validation_test.go

`Spec.Config.Namespace` is not required since the logical default
is the broker's namespace.

Spec.Config.Namespace is not required

---

control-plane/config/post-install/200-controller-cluster-role.yaml

Fixes #2681 
```
ansuvarghese$ k get pods -n knative-eventing
NAME                                           READY   STATUS      RESTARTS       AGE
kafka-controller-post-install-wxz79            1/1     Running     9 (5m4s ago)   22m
```
```
ansuvarghese$ k logs kafka-controller-post-install-wxz79 -n knative-eventing
{"severity":"EMERGENCY","timestamp":"2022-09-27T22:24:31.085183047Z","logger":"kafka-broker-post-install","caller":"post-install/main.go:46","message":"source dispatcher deletion failed: failed while waiting for statefulset to come up: failed to get statefulset knative-eventing/kafka-source-dispatcher: statefulsets.apps \"kafka-source-dispatcher\" is forbidden: User \"system:serviceaccount:knative-eventing:knative-kafka-controll …
```

Fix cluster role for post install job

---

data-plane/pom.xml

- Going with Red Hat UBI8 as the OpenJDK base
```release-note
```
**Docs**

Using Red Hat OpenJDK with ubi8

---

data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherTest.java

Fix flaky failedEventsShouldBeEnhancedWithErrorExtensionsPriorToSendingToDlsBodyTooLarge test

---

control-plane/pkg/kafka/topic.go
control-plane/pkg/reconciler/channel/channel_test.go
control-plane/pkg/reconciler/channel/v2/channelv2_test.go

Fixes propagation of KafkaChannel's `retentionDuration` into KafkaTopic resource. Before this PR, `retentionDuration` was ignored.
- :gift: Consume entire sarama.TopicDetail when creating new KafkaTopic's
- :bug: And so propagate KafkaChannel's retentionDuration to KafkaTopic's config (default's to 7 days)
```release-note
New Kafka topics will be created with the default 7 day retention duration. Existing topics will _**not**_ be updated.
```

Use full TopicDetail when creating new topics

---

control-plane/pkg/reconciler/consumer/consumer.go
control-plane/pkg/reconciler/testing/objects_common.go

I noticed that sometimes we try to add the same owner
reference multiple times.

Add owner reference only when it is not present

---

control-plane/config/eventing-kafka-broker/200-webhook/400-webhook-pod-defaulting.yaml

knative/pkg modifies this field and our operator starts
to loop due to these updates but since the field is empty
is pointless to keep it.

Remove empty match expression to avoid operator loops

---

test/e2e-common.sh

Signed-off-by: Dirk Haubenreisser <haubenr@de.ibm.com>
Fixes #2729
This PR addresses the issue reported in #2729 by adding a waiting period of 180s max to the scaling operation of various deployments prior to the deployment of sacura.
Note that this affects the e2e test code only, no changes to the actual product / component code.

Fix for scaling issue

---

data-plane/THIRD-PARTY.txt
data-plane/pom.xml

Reverts knative-sandbox/eventing-kafka-broker#2678
This breaks structured logging:
```
W0927 09:16:30.950136   34760 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
Picked up JAVA_TOOL_OPTIONS: -XX:+CrashOnOutOfMemoryError
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Revert "[data-plane]: Bump ch.qos.logback.version from 1.2.11 to 1.4.1 in /data-plane"

---

test/e2e-common.sh

Signed-off-by: Dirk Haubenreisser <haubenr@de.ibm.com>
This PR is a follow-up to issue #2729 
While the initial PR for that issue did address the knative deployment scaling hiccups on the s390x platform to ,say, 95% there is still the occasional test run that fails due to the knative webhook deployment not being available at the time when sacura is to be deployed (see: https://prow.knative.dev/view/gs/knative-prow/logs/s390x-e2e-tests-sasl-plain_eventing-kafka-broker_release-1.8_periodic/1584595827215568896)
The change in this PR attempts to fix the issue fully by
a) increasing the wait timeout for the knative deployment scaling to 10 minutes
b) failing the test run deliberately in case the deployment scaling timeout is reached

Increased wait timeout, fail test if scaling times out

---

.github/workflows/kind-e2e.yaml

Fixes #
- Remove kind tests for 1.22, since we are already on min: 1.23 and also the HPA/v2 (dependency from eventing upstream) is NOT present on 1.22...
```release-note
```
**Docs**

[kind] Remove 1.22-based test iteration

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/ConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerFactory.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleBuilder.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleContext.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleLoggingContext.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/LoggingConsumerVerticleContext.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ProducerFactory.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/AbstractConsumerVerticleTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticleTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticleTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/ConsumerVerticleFactoryImplMock.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImplTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/main/FakeConsumerVerticleContext.java
hack/data-plane.sh

As highlighted in [1], our logging statements don't contain enough info to contextualize a specific log statement.
In this PR, I'm restructuring the way we create Consumer verticles, so that we can inject arbitrary context to our log statements based on the specific resource / egress they are acting for.
The large refactoring is also meant to simplify the CosumerVerticleFactoryImpl which was doing to much and it has been a cause of a recent misconfiguration [2].
Previously, we had a single CosumerVerticleFactoryImpl that was doing everything to build a Consumer verticle, now, I'm braking down the logic into multiple single purpose classes.
[1] https://github.com/knative-sandbox/eventing-kafka-broker/pull/1999
[2] https://github.com/knative-sandbox/eventing-kafka-broker/commit/1865320ffedf9 …

Refactor ConsumerVerticleFactory and enhance dispatcher logging

---

control-plane/pkg/reconciler/consumergroup/consumergroup.go

Fixes
```
Message:               failed to set up autoscaler: failed to update scaled object default/so-84c28610-c23a-4dff-8ed9-3e57bc8c3d9b: scaledobjects.keda.sh "so-84c28610-c23a-4dff-8ed9-3e57bc8c3d9b" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
Reason:                AutoscalerFailed
Status:                False
Type:                  Ready
Warning  InternalError    7m18s (x21 over 9m21s)  consumergroup-controller  failed to set up autoscaler: failed to update scaled object default/so-84c28610-c23a-4dff-8ed9-3e57bc8c3d9b: scaledobjects.keda.sh "so-84c28610-c23a-4dff-8ed9-3e57bc8c3d9b" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```
/cc @pierDipi

Metadata resource version empty fix for new Keda resources

---

control-plane/pkg/client/clientset/versioned/fake/register.go
control-plane/pkg/client/clientset/versioned/scheme/register.go
control-plane/pkg/client/internals/kafka/clientset/versioned/fake/register.go
control-plane/pkg/client/internals/kafka/clientset/versioned/scheme/register.go
control-plane/pkg/contract/subscriptionsapi.go
control-plane/pkg/kafka/consumer_group_lag_test.go
control-plane/pkg/reconciler/testing/objects_common.go
control-plane/pkg/security/secret_test.go
test/e2e_broker/broker_trigger_sink_test.go
test/e2e_new_channel/kafka_channel_upstream_test.go
third_party/pkg/client/clientset/versioned/fake/register.go
third_party/pkg/client/clientset/versioned/scheme/register.go

As per title.
Go 1.19 is now required to generate and verify generated code.

Run hack/update-codegen.sh with Go 1.19

---

control-plane/pkg/keda/keda.go
control-plane/pkg/reconciler/consumergroup/consumergroup.go
control-plane/pkg/reconciler/testing/objects_broker.go
control-plane/pkg/reconciler/trigger/v2/triggerv2.go
control-plane/pkg/reconciler/trigger/v2/triggerv2_test.go
control-plane/pkg/security/config.go

Should "UseNamespaceInConfigmap" for both brokers and channels specified by `auth.secret.ref.namespace` instead of using namespace of config map itself or namespace of reference object for v2....
This means parameters needed by KEDA will need to be referenced before creating KEDA CRs...
/cc @pierDipi @matzew

Updates to use secret data (sasl and tls) from `auth.secret.ref.namespace` for Triggerv2 and Channelv2

---

control-plane/pkg/reconciler/testing/objects_broker.go
control-plane/pkg/reconciler/trigger/v2/triggerv2.go
control-plane/pkg/reconciler/trigger/v2/triggerv2_test.go
control-plane/pkg/security/config.go

Fix for using namespace of the broker instead of status annotation namespace

---

test/e2e-common.sh

`ko` is not needed for sacura tests

Remove ko usage for sacura tests

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java

Signed-off-by: Vikram Vuppla naga.vicky@gmail.com
Fixes #
Why:
- Currently the retry is happening regardless of the response status code is retryable or not, remove the buggy retry logic
- :bug: Fix bug

Retry Only If the Status Code Is Retryable

---

control-plane/pkg/autoscaler/keda/keda.go

/cc @pierDipi 
Fixes below error:
```
{
"lastTransitionTime": "2022-11-22T16:30:29Z",
"message": "failed to set up autoscaler: SASL type value \"\" is not supported",
"reason": "AutoscalerFailed",
"status": "False",
"type": "ConsumerGroup"
},
```

Return "nil" saslType if not present for Auth

---

control-plane/pkg/apis/core/pod_defaulting.go
control-plane/pkg/apis/internals/kafka/eventing/data_plane.go
control-plane/pkg/reconciler/base/reconciler.go
control-plane/pkg/reconciler/consumer/consumer.go
control-plane/pkg/reconciler/consumergroup/consumergroup.go
control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
control-plane/pkg/reconciler/consumergroup/controller.go
control-plane/pkg/reconciler/consumergroup/controller_test.go
control-plane/pkg/reconciler/testing/objects_common.go

Since we create the contract ConfigMaps in the Consumer reconciler
but the scheduler is called in the ConsumerGroup reconciler and it
fails with "not enough pod replicas" when the data plane pods are
in pending state.
This is not evident in our CI but it might be a signal of an edge
case caused by a certain sequence of events.
In this PR, I'm creating ConfigMaps before calling the scheduler
in the ConsumerGroup reconciler so that the pods can become
ready before the scheduler verifies which pods are available
to schedule vpods.
Fixes #2750
- Create contract ConfigMaps in ConsumerGroup reconciler
```release-note
Fix Stateful set implementation of KafkaSource not working, pods remain in pending phase
```

Create contract ConfigMaps in ConsumerGroup reconciler

---

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_types.go
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/zz_generated.deepcopy.go

This breaks upgrades:
```
{"level":"error","ts":"2022-11-18T16:55:44.956Z","logger":"kafka-broker-controller","caller":"controller/controller.go:566","msg":"Reconcile error","commit":"3d507f2","knative.dev/pod":"kafka-controller-5f99c8bc78-cjgll","knative.dev/controller":"knative.dev.eventing-kafka-broker.control-plane.pkg.reconciler.consumergroup.Reconciler","knative.dev/kind":"internal.kafka.eventing.knative.dev.ConsumerGroup","knative.dev/traceid":"b26cd645-27fe-467f-bdfe-4ab856e7a1fb","knative.dev/key":"dev/894c28fc-6800-4f75-bf10-f99ca1e19f30","duration":0.136223835,"error":"admission webhook \"validation.webhook.kafka.eventing.knative.dev\" denied the request: decoding request failed: cannot decode incoming new object: json: unknown field …
```

Avoid removing AuthSpec for compatibility

---

control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-autoscaler.yaml
control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml
control-plane/config/eventing-kafka-source/200-controller/100-config-kafka-autoscaler.yaml
control-plane/config/eventing-kafka-source/200-controller/500-controller.yaml
control-plane/pkg/autoscaler/config.go
control-plane/pkg/autoscaler/keda/keda.go
control-plane/pkg/autoscaler/keda/resources.go
control-plane/pkg/reconciler/consumergroup/autoscaler_config.go
control-plane/pkg/reconciler/consumergroup/consumergroup.go
control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
control-plane/pkg/reconciler/consumergroup/controller.go
control-plane/pkg/reconciler/consumergroup/controller_test.go

Fixes #2804
- New configmap for specifying [default values](https://github.com/knative-sandbox/eventing-kafka-broker/blob/main/control-plane/pkg/autoscaler/autoscaler_api.go#L52-L63) for Autoscaling Kafka resources
```release-note
```
**Docs**

Configurable default values for autoscaler

---

control-plane/pkg/kafka/testing/admin_mock.go
control-plane/pkg/reconciler/consumergroup/consumergroup.go
control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
control-plane/pkg/reconciler/testing/errors.go

When a topic is deleted before a ConsumerGroup, we should
not fail to finalize the ConsumerGroup when deleting the
Consumer group in Kafka.

Handle ConsumerGroup finalization for deleted topics

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
test/e2e_new/broker_test.go
test/e2e_new/features/broker_deleted_recreated.go
test/e2e_new/resources/configmap/broker/broker_config.go
test/e2e_new/resources/configmap/broker/broker_config.yaml

Fixes #2828
- If secret for external managed topic is gone / not present, we do not block the finalization. The broker does anyways not need to perform any sorts of clean-ups on these externally managed topics
```release-note
```
**Docs**

Do not block finalization if secret for external topic is gone

---

test/kafka/user-sasl-scram-512.yaml
test/kafka/user-tls.yaml

- Granting permissions to delete consumer groups metadata which is (and actually already was) needed to delete consumer groups. (something we did downstream as well)
```release-note
```
**Docs**

Granting permissions to delete consumer groups metadata

---

control-plane/pkg/propagator/resource_propagator.go
control-plane/pkg/propagator/resource_propagator_test.go
control-plane/pkg/reconciler/broker/namespaced_broker.go
go.mod
test/e2e_new/features/featuressteps/broker.go
test/e2e_new/features/namespaced_broker.go

Fixes #
- Templating support in namespaced broker additional resources
- We need to *inject* the namespace into the spec of the resources created
Sample resource to put in additional resources CM is following. The `{{.Namespace}}` variable will be changed to the broker namespace.
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
...
spec:
endpoints:
- tlsConfig:
ca: {}
caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
cert: {}
serverName: "kafka-broker-receiver-sm-service.{{.Namespace}}.svc"
namespaceSelector:
matchNames:
- "{{.Namespace}}"
...
```
```release-note
Added templating support in namespaced broker additional resources, which allows injecting information to those resources.
```
**Docs**

Templating support in namespaced broker additional resources

---

control-plane/pkg/counter/counter.go
control-plane/pkg/counter/counter_test.go
control-plane/pkg/prober/cache.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/controller.go
control-plane/pkg/reconciler/broker/namespaced_broker.go
control-plane/pkg/reconciler/broker/namespaced_controller.go
control-plane/pkg/reconciler/consumergroup/consumergroup.go
control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
control-plane/pkg/reconciler/consumergroup/controller.go

When the secret is gone we successfully delete the KafkaSource but ConsumerGroup might be stuck in deletion since we can't connect to Kafka anymore.
Fixes #
- Improve ConsumerGroup finalization when missing resources
```release-note
Improve ConsumerGroup finalization when missing resources
```
**Docs**

Improve ConsumerGroup finalization when missing resources

---

control-plane/pkg/prober/cache.go
control-plane/pkg/prober/prober.go
control-plane/pkg/reconciler/broker/broker.go
test/e2e_new/broker_test.go
test/rekt/features/namespace.go
test/rekt/features/namespaced_broker.go

When the system namespace is deleted while we're running there is no point in
trying to delete the resource from the ConfigMap since the entire ConfigMap
is gone.
Fixes #2893

Fix delete namespace with a namespaced broker stuck on finalizer

---

control-plane/pkg/reconciler/broker/broker.go

Fixes #
- Move up a check for error on fetching the configmap for the brokerconfig, to avoid a later nil invocation
```release-note
```
**Docs**

chore: Move up a check for errors on fetching the broker config map

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
test/e2e_new/broker_test.go
test/rekt/features/broker_deleted_recreated.go

Fixes #2885
- No different treatment on internal or external topic for finalization
- If secret is missing, we try a number of times, otherwise we let go and do not block finalization
- added `rekt` test for "non existing secret" for "internal topic
```release-note
No different treatment on internal or external topic for finalization, and we no longer block if we can not resolve the secret reference for a number of times.
```
**Docs**

Improve finalization on missing secret ref

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/testing/objects_broker.go
test/e2e_new/bogus_config/bogus_config.yaml
test/e2e_new/bogus_config/install.go
test/e2e_new/broker_test.go
test/rekt/features/broker_deleted_recreated.go

Fixes #2815
- If an invalid topic config is present for a broker we do not block finalization
```release-note
If an invalid topic config is present for a broker we do not block finalization
```
**Docs**

Fix finalization problem when broker has incorrect topic config

---

test/kafka/kafka_setup.sh
test/kafka/strimzi-cluster-operator.yaml

- Updating just the Strimzi Operator to 0.33
- Putting in the _pure_ manifest from upstream, and doing `sed` to replace namespaces... since https://github.com/knative-sandbox/eventing-kafka-broker/pull/2381 we do have some "patched" (hard-coded) `namespace: kafka` references on the manifest, which this PR changes
0.33 release notes: https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.33.0
Some highlights:
* Use Java 17 as the runtime for all containers...
* Improved FIPS (Federal Information Processing Standards) support

Strimzi 0.33 update

---

control-plane/pkg/config/eventingkafkaconfig.go
control-plane/pkg/security/config.go
control-plane/pkg/security/secrets_provider_legacy_channel_secret.go
control-plane/pkg/security/secrets_provider_legacy_channel_secret_test.go

Fixes #2905
In #2902 we migrated the `getAuthConfigFromSecret` and `extractProtocol` functions, as they were used in `ResolveAuthContextFromLegacySecret`: https://github.com/knative-sandbox/eventing-kafka-broker/blob/df192313795eb858fc10132dac474bd7cfe8b032/control-plane/pkg/security/secrets_provider_legacy_channel_secret.go#L33-L34
At that place they are only to figure out the protocol and doesn't need all the other overhead. 
This PR addresses it and simplifies the  `getAuthConfigFromSecret` and `extractProtocol` functions to just have a function that given a "legacy channel secret" returns `protocolStr, protocolContract`.
In addition we cleanup the `KafkaAuthConfig` structs which are thus not needed anymore.
This is the follow up on …

Simplify `getAuthConfigFromSecret` and `extractProtocol`

---

control-plane/pkg/reconciler/consumergroup/evictor.go
control-plane/pkg/reconciler/consumergroup/evictor_test.go

```
E0125 19:04:18.704663       1 runtime.go:79] Observed a panic: "makeslice: cap out of range" (runtime error: makeslice: cap out of range)
goroutine 427 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1d6fba0?, 0x2408810})
/remote-source/knative-kafka-broker/app/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x7fcd35b823a0?})
/remote-source/knative-kafka-broker/app/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1d6fba0, 0x2408810})
/usr/lib/golang/src/runtime/panic.go:838 +0x207
knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup.removePlacement(...)
```

Fix evictor panic

---

control-plane/pkg/reconciler/base/reconciler.go
control-plane/pkg/reconciler/broker/namespaced_broker_test.go
control-plane/pkg/reconciler/consumer/consumer_test.go
control-plane/pkg/reconciler/consumergroup/consumergroup_test.go

When contract configmaps are created, we don't enforce
owner references to be set when they are create which
could lead to leftovers ConfigMaps when:
- KafkaNamespaced brokers are deleted
- kafka-source-dispatcher pods are deleted (for source v2)

Enforce owner references on contract ConfigMap creation

---

data-plane/THIRD-PARTY.txt
data-plane/core/pom.xml

Exclude slf4j-jboss-logmanager from quarkus-vertx for logging

---

data-plane/config/broker/500-receiver.yaml
data-plane/config/channel/500-receiver.yaml
data-plane/config/sink/500-receiver.yaml

- Increase memory limits of kafka broker receiver to get arround [SRVKE-1409](https://issues.redhat.com/browse/SRVKE-1409)
- Increase memory limits of kafka channel receiver
- Increase memory limits of kafka sink receiver

Increase receivers memory requests

---

test/e2e_new/broker_trigger_sink_test.go

Skipping `TestBrokerTiggersSink` test due to #2951 and https://github.com/knative-sandbox/eventing-kafka-broker/pull/2932#discussion_r1094801731 to save resources until fixed.

Skip `TestBrokerTiggersSink` test

---

DEVELOPMENT.md

Jib doesn't support `kind.local`

Remove mention for kind.local in Development docs

---

test/upgrade-tests.sh
test/upgrade/postdowngrade.go
test/upgrade/upgrade_test.go

Description: The original Bash solution for collecting logs doesn't work for upgrade tests because the Pods are restarted during upgrades and the exported logs are empty in the end. This can be seen e.g. [here](https://gcsweb.knative.dev/gcs/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka-broker/2946/upgrade-tests_eventing-kafka-broker_main/1626255704035692544/artifacts/knative-eventing/)
- Re-use recently implemented changes from knative.dev/pkg and knative.dev/eventing for log streaming from system namespaces.
- Stream logs for a predefined set of Pods.
```release-note
```
**Docs**

Stream logs from system namespace in upgrade tests

---

hack/control-plane.sh
hack/data-plane.sh
test/e2e-common.sh

`pwd` or `dirname $0` is not reliable way of getting the repo root
dir, so I'm using `$(dirname "$(realpath "${BASH_SOURCE[0]}")")`.
Tested this in eventing-istio.

Fix bash scripts import paths

---

control-plane/config/eventing-kafka-broker/200-webhook/400-webhook-pod-defaulting.yaml

Instead of using the custom `app.kubernetes.io/name` for selecting a specific namespace we use the
`kubernetes.io/metadata.name` label that is enforced by the API server on each namespace
https://kubernetes.io/docs/reference/labels-annotations-taints/#kubernetes-io-metadata-name
The benefit is that some installations create the system namespace themself so the app.kubernetes.io/name that is defined in core might not be present, leading to a non functioning KafkaSource.

Use kubernetes.io/metadata.name for namespace selector

---

test/pkg/tracing/zipkin.go

Fixing a linting issue from using a deprecated variable from zipkin.
```
Error: SA1019: zipkin.ZipkinTracingEnabled is deprecated: Use IsTracingEnabled for checking the current state.  (staticcheck)
```
To check if zipkin tracining is enabled, `zipkin.IsTracingEnabled()` can be used. During the setup (`SetupZipkinTracingFromConfigTracing()` -> `SetupZipkinTracing()`) it is set to `true`:
https://github.com/knative-sandbox/eventing-kafka-broker/blob/fc17e7686e3fe8d2e071402d5ff6e2aaacf6572a/vendor/knative.dev/pkg/test/zipkin/util.go#L150

Fix linting issue from usage of deprecated zipkin variable

---

control-plane/pkg/reconciler/broker/namespaced_broker.go
control-plane/pkg/reconciler/broker/namespaced_broker_test.go
test/rekt/features/namespaced_broker.go

In EKB controller, we use Manifestival to create resources that are in "additional resources". When we have the RoleBinding like this in the Manifest:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
name: knative-prometheus-k8s
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: Role
name: knative-prometheus-k8s
subjects:
- kind: ServiceAccount
name: prometheus-k8s
namespace: openshift-monitoring           # --> changed
```
will become:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
name: knative-prometheus-k8s
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: Role
name: knative-prometheus-k8s
subjects:
- kind: ServiceAccount
name: prometheus-k8s
namespace: <user-namespace>        # --> changed
```
This is done here …

Do not inject namespace to additional resources using Manifestival's namespace injection

---

test/e2e_new/tracing_test.go

This test is a little flaky. In my latest run I got 5 events received out of 10 expected. The error is below. I think this test should wait for both triggers to be ready as it seems only one of them was able to deliver events.
```
=== CONT  TestTracingHeaders/TracingHeadersUsingUnorderedDeliveryWithMultipleTriggers/Assert/[Stable/MUST]received_event_has_traceparent_header
event_info_store.go:160: Timeout waiting for at least 10 matches.
Error: FAIL MATCHING: saw 5/10 matching events.
- Store-
Pod 'sink-hwkfchsi' in namespace 'test-ganihgga'
- Recent events -
5 events seen, last 5 events (total events seen 35, events ignored 30):
-- EventInfo --
--- Kind: Received ---
--- Event ---
Context Attributes,
specversion: 1.0
type: com.example.FullEvent
source: http://example.com/source
subject: …
```

TracingHeaders test waits for both triggers to be ready

---

control-plane/pkg/contract/subscriptionsapi.go
control-plane/pkg/contract/subscriptionsapi_test.go

Fixes #2942
instead of passing `f.any` filter as argument in `newAnyFilter()` it was passing `f.all` which was causing this issue
- passing required arguments to create a proper `Any` filter.
- put the test to check if `any` filter gets its format or not

Fix: Experemental filters `Any`Filter working bug

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManagerTest.java

Fixes broken initial offset on reset on a non64 bit boundary
- Take the `relativeOffset`/`wordSize` remainder into account when resetting `initialOffset`
@hadriansecurity

Fix broken initial offset on reset on a non64 bit boundary

---

control-plane/pkg/reconciler/channel/resources/service.go
control-plane/pkg/reconciler/testing/objects_channel.go

By not having the port defined on the KafkaChannel's external
name service, istio (actually Envoy) can't find a matching route
for requests to the channel's service without any port, see [1]
[1] https://www.envoyproxy.io/docs/envoy/latest/faq/debugging/why_is_my_route_not_found
- Add ports to KafkaChannel's external name service
```release-note
Add ports to KafkaChannel's externalName services
```
**Docs**
N/A

Don't override ports for KafkaChannel's service

---

go.mod

- using go 1.19, since some vendor'ed deps are using `atomic.Bool`:
```
Error: vendor/knative.dev/eventing/pkg/scheduler/statefulset/autoscaler.go:79:18: undefined: atomic.Bool
Error: vendor/knative.dev/eventing/pkg/scheduler/statefulset/autoscaler.go:115:29: undefined: atomic.Bool
note: module requires Go 1.19
```
which was introduced in [1.19](https://pkg.go.dev/sync/atomic#Bool)
See: https://github.com/knative/eventing/actions/runs/4741242354/jobs/8418053369?pr=6868
```release-note
```
**Docs**

Go 1.19 usage

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManagerTest.java

Before this patch, we were caching the new offset before committing to Kafka the offset, causing the offset to not be stored until a new record is successfully processed.

Retry offset commit

---

control-plane/pkg/reconciler/source/source.go
control-plane/pkg/reconciler/source/source_test.go

Fixes #3070 
- Add empty definition for `FinalizeKind` to ensure that deleting a source does not hang if it has a finalizer
```release-note
Fixed bug where deleting sources created before the sourcev2 upgrade caused the source to hang on finalization.
```

Added empty FinalizeKind definition to prevent delete sources from hanging

---

control-plane/pkg/reconciler/source/source.go
control-plane/pkg/reconciler/source/source_test.go

- Cherry pick commit https://github.com/knative-sandbox/eventing-kafka-broker/commit/e45c5fec51f1e4af193afdede8efa10d780b0fae to version 1.9

Cherry pick sourcev2 upgrade fix to 1.9

---

data-plane/config/broker-tls/broker-ingress-tls-certificate.yaml
data-plane/config/channel-tls/channel-ingress-tls-certificate.yaml
data-plane/config/sink-tls/sink-ingress-tls-certificate.yaml

Fixes #3107 
- Add Cert-Manager resources for kafka-broker-receiver, kafka-channel-receiver, and kafka-sink-receiver
```release-note
Added Cert-Manager resources for the kafka-broker-receiver, kafka-channel-receiver, and kafka-sink-receiver.
```

Create cert manager resources for ekb components

---

test/e2e_new/broker_conformance_test.go

This test can run multiple times for different implementations and also in a common namespace. The name must be unique for each run.
-
-
-
```release-note
```
**Docs**

Unique broker name in broker conformance tests

---

control-plane/pkg/prober/async_prober.go
control-plane/pkg/prober/async_prober_test.go

Fixes #3128 
- Add a new constructor for the async prober so that it can support TLS, allowing us to probe even when the address uses https
```release-note
Added TLS support to the prober.
```

Support TLS in prober

---

data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java

`new LoggingSpanExporter()` was deprecated.
- Replace it with `LoggingSpanExporter.create()` the preferred method.

LoggingSpanExporter constructor was Deprecated replace it with prefered `create()`

---

test/e2e-tests.sh

When trying to run the e2e tests by following the guide provided in `DEVELOPMENT.md`, I was shown the following error: `ERROR: Broker class is not defined. Specify it with 'BROKER_CLASS' env var`.
- Set a default value for `BROKER_CLASS` if it is undefined when running the e2e tests.

Update e2e tests to have default value for BROKER_CLASS

---

control-plane/pkg/prober/async_prober.go
control-plane/pkg/prober/async_prober_test.go
control-plane/pkg/prober/prober.go

Fixes #3140 
- Provide a method to rotate the ca certs for a given prober, which can be called as appropriate by a given controller
```release-note
Probers now support rotating CA certificates
```

Support rotating CA certs in prober

---

control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-features.yaml
control-plane/pkg/apis/config/features.go
control-plane/pkg/apis/config/features_test.go
control-plane/pkg/apis/config/testdata/config-kafka-features.yaml
test/config/100-config-kafka-features.yaml

As part of #3153 we need to be able to add broker and channel topic prefixes.
- Update the kafka features to support broker topic template and channel topic template

Allow defining topic prefixes

---

control-plane/pkg/prober/async_prober_test.go

Fixes #3143 
From the test logs we can see that the probe requests are taking over 100ms to return:
```
RUN   TestAsyncProberRotateCACerts
logger.go:130: 2023-06-20T13:19:10.395Z	DEBUG	prober/prober.go:72	Sending probe request	{"scope": "prober", "IP": "127.0.0.1", "address": "https://127.0.0.1:39683/b1/b1"}
logger.go:130: 2023-06-20T13:19:10.509Z	DEBUG	prober/async_prober.go:148	Probe status	{"scope": "prober", "IP": "127.0.0.1", "address": "https://127.0.0.1:39683/b1/b1", "status": "Ready"} 
```
This is causing test flakiness, as we are currently probing every 100ms and checking the number of times the probes have been done.
- Increase the tick time in the prober tests so that they have enough time to run

Increased tick time to improve test flakiness

---

data-plane/dispatcher-vertx/src/main/java/dev/knative/eventing/kafka/broker/dispatchervertx/VertxConsumerFactory.java
data-plane/dispatcher-vertx/src/main/java/dev/knative/eventing/kafka/broker/dispatchervertx/VertxKafkaConsumer.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ReactiveConsumerFactory.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ReactiveKafkaConsumer.java

Progress on #2928 
- Identifies all the Consumer functions used and needs to be implemented in specialised modules.
- Implement all of these methods in the dispatcher vertx module with vertx implementation.
It may require some additional changes while migrating the base dispatcher to use `ReactiveKafkaConsumer`

`ReactiveKafkaConsumer` Interface and it's Vert.x Implementation

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java

When running MT components [1] in mesh mode with Istio, 
we lose the ability to define fine grained policies since we
don't know the resource namespace that originated such
request, therefore, by having a `Kn-Namespace` header, 
in mesh mode, users case define fine-grained policies and
isolate namespaces.
[1] KafkaSource, Kafka Broker, and KafkaChannel
Related to https://github.com/knative/eventing/pull/7048

Send namespace header in MT components

---

.github/workflows/build-dependabot-pr.yaml
.github/workflows/knative-java-test.yaml
.github/workflows/knative-profile-data-plane.yaml

As we are planning to build the receiver and dispatcher with loom virtual thread through #2928  the workflow needs to upgrade to 20+ JAVA version.
- Update the `knative-java-test` and `knative-profile-data-plane` to use JAVA 20. 
- Update the `dependent-bot` java version to 17 the current LTS.

Upgrade workflow's java version to 20

---

DEVELOPMENT.md

Fixes #3166 
- Added the documentation for now to use the spotless formatter and go fmt
```release-note
Added the documentation support for spotless and go fmt
```

Update the document to include the code formatter

---

test/e2e_new/broker_conformance_test.go

It might take longer than default 2 minutes to finish the tests and since all the steps run in parallel now the time starts to tick earlier.
The new PollTimeout is 4 minutes.
Fixes #
-
-
-
```release-note
```
**Docs**

Increase PollTimings for TestBrokerConformance

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/ConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleBuilder.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleContext.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/AbstractConsumerVerticleTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticleTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/main/FakeConsumerVerticleContext.java

A clean conflict-free PR of #3195
- Put the `ConsumerRebalanceListener` into `ConsumerVerticle`

Remove `ConsumerRebalanceListener` from `ConsumerVerticleContext`

---

control-plane/pkg/prober/async_prober.go

Per conversation with @pierDipi the async prober code can be confusing when it asynchronously aggregates the status of the different IPs for each pod.
- Add more context to the comments/update outdated comments to provide more context in the async prober

Updated comments explaining how the async prober works

---

data-plane/dispatcher-vertx/pom.xml
data-plane/receiver-vertx/pom.xml

Currently the fabric8 Kubernetes Client loads the Client Implementation class dynamically: https://github.com/fabric8io/kubernetes-client/blob/587657dc1bdd244cd4da5352ab97cd5668081696/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientBuilder.java#L53
This can lead to a ClassNotFoundException, when using the maven-shade plugin to package an "uber jar" as the class is not directly referenced.
This PR addresses it and explicitly includes the kubernetes-client classes.

Include io.fabric8 kubernetes-client in maven-shade-plugin to prevent ClassNotFoundException

---

test/e2e-common.sh

Fixes #3182 
Previously : E2E common setup does not wait for cert manager to become ready.
Now : E2E common setup wait for cert manager to become ready. Now its wait for all cert-manager pods to up and running.
```
wait_until_pods_running
```
**Output**

Fix E2E common setup does not wait for cert manager

---

data-plane/config/broker-tls/broker-ingress-tls-certificate.yaml
data-plane/config/channel-tls/channel-ingress-tls-certificate.yaml
data-plane/config/sink-tls/sink-ingress-tls-certificate.yaml

As per title, without this configuration the private key is not rotated

Eventing TLS: Configure certificates to force rotate private keys

---

README.md

Though the slack channel is now under CNCF slack it was not updated here and still pointing to the old slack channel.

Replace the old slack channel link with the new proper one

---

control-plane/pkg/prober/composite_prober.go

Fixes #3262
- Fix the status accumulation logic
```release-note
fixed the prober logic for addresses which could be http or https
```

Fixed composite prober logic

---

control-plane/pkg/reconciler/broker/broker.go

The broker finalizeKind probe should have the address in the `NewProber.Addresses` field as well, because the composite prober only probes addresses in that list.
- Add the address to the `Addresses` field

Add missing addresses field to broker finalizer

---

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_types.go

This will prevent writing SecretSpec with null value and the webhook will rather omit the element. 
```
spec:
auth:
SecretSpec: null
```
Having the element there with null value can also caus problems during downgrades when the element was not there yet (it's a few versions back though)
-
-
-
```release-note
```
**Docs**

Make SecretSpec field of consumers Auth omitempty

---

hack/create-kind-cluster.sh

During https://github.com/knative/eventing/pull/7140 I saw, that the ClusterConfiguration is not used correctly (e.g. the cluster domain not set correctly). This is due to an old apiVersion field, which (according to https://github.com/kubernetes-sigs/kind/issues/1466#issuecomment-675664846) can be dropped.
Also the `metadata.name` field can be dropped ([kind docu: kubeadm-config-patches](https://kind.sigs.k8s.io/docs/user/configuration/#kubeadm-config-patches)).
With this fix, configs, like the CLUSTER_SUFFIX will be propagated correctly to kubeadm again.

Propagate ClusterConfiguration in kind correctly

---

.gitignore
DEVELOPMENT.md
data-plane/benchmarks/resources/config-logging.xml
data-plane/benchmarks/resources/filter-class-list.txt
data-plane/benchmarks/run.sh
hack/run.sh

Fixes #3270 
- Add `run.sh` script in the benchmark project to run the benchmarks
- Make the `run.sh` script runnable from `hack/run.sh`
- Add documentation to `DEVELOPMENT.md` on how to run the script

Add benchmark filter run script

---

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_lifecycle.go
control-plane/pkg/reconciler/consumergroup/consumergroup_test.go

In [1], we return an error, however, that method is called in the consumer group reconciler when a consumer is not ready which is a normal state at the beginning when consumers have been just created, so we shouldn't return an error because that causes the consumer group to be reconciled again with an exponentially increasing delay causing slow time to ready.
This is especially evident when scaling up with a high load = (therefore when dispatcher pod is slow to become ready).
[1] https://github.com/knative-sandbox/eventing-kafka-broker/blob/5cda5463aa2fa060179674fe7b3237abb836ee06/control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_lifecycle.go#L57-L65
Fixes #3046 
- Fix slow consumergroup reconciliation under load
```release-note
Fix slow …
```

Fix slow consumergroup reconciliation under load

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java

Current Loom Dispatcher was not working properly and there is no events retrieving on that side.
The Problem we find is that when we are using loom modules the ConsumerTracer (which is using vertx opentelemetry), is a `NullPointerException` occurring and it's discarding the records.
```sh
"stack_trace":"java.lang.NullPointerException": 
Cannot invoke "io.vertx.core.Context.getLocal(Object)" because "vertxCtx" is null
at io.vertx.tracing.opentelemetry.VertxContextStorageProvider$VertxContextStorage.attach(VertxContextStorageProvider.java:27)
at io.vertx.tracing.opentelemetry.OpenTelemetryTracer.receiveRequest(OpenTelemetryTracer.java:70)
at io.vertx.tracing.opentelemetry.OpenTelemetryTracer.receiveRequest(OpenTelemetryTracer.java:31)
at …
```

Fixing: `NullPointerException` occurring and it's discarding the records while tracing for Loom deployment

---

data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java

Fixes #3302
The name should be etc/receiver-tls-secret instead of /etc/receiver-secret-volume

Change the name of the secretVolumePath

---

data-plane/config/broker/500-receiver.yaml

Expose tls port for broker

---

control-plane/pkg/reconciler/sink/controller.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/sink/kafka_sink_test.go

Fixes #3189 
- Update the Kafka_sink controller to use the prober with tls if the transport encryption flag is set to strict.
```release-note
The Kafka_sink now uses a tls-enabled prober if the transport encryption flag is set to strict.
```
**Docs**

Using the composite prober for the sink

---

OWNERS

- Add `eventing-kafka-broker-reviewers` role as reviewer to repository

Add eventing kafka broke reviewers role

---

data-plane/dispatcher-loom/src/main/java/dev/knative/eventing/kafka/broker/dispatcherloom/LoomKafkaConsumer.java

Fixes #3309
From my inspection what might happening here is that After we are close the consumer, though we are failing the corresponding task promise still taskRunnerThread is still taking the task as we are not returning from the function.
https://github.com/knative-extensions/eventing-kafka-broker/blob/1e369784b4161dfb9a35eabe96b0db618991213b/data-plane/dispatcher-loom/src/main/java/dev/knative/eventing/kafka/broker/dispatcherloom/LoomKafkaConsumer.java#L55-L59
Other than that I also saw a exception while we are trying close the consumer. Though it is the Interrupted exception that is expected, but there is a possibility that the `consumer.close()` method fail. and we try to complete it again while we stop taskRunnerThread here …

Fix multiple time Promise complete problem

---

data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java

Fixes #3336 
Now:
```
PemKeyCertOptions keyCertOptions = new PemKeyCertOptions()
.setCertValue(Buffer.buffer(java.nio.file.Files.readString(tlsCrtFile.toPath())))
.setKeyValue(Buffer.buffer(java.nio.file.Files.readString(tlsKeyFile.toPath())));
```
Past:
```
PemKeyCertOptions keyCertOptions =
new PemKeyCertOptions().setKeyPath(tlsKeyFile.getPath()).setCertPath(tlsCrtFile.getPath());
```
```release-note
```
**Docs**

Update the updateServerConfig function to pass in the cert value diectly

---

hack/run.sh

Currently, spotless formatting is triggered either when someone runs ./hack/update-codegen.sh or manually uses spotless. To simplify the process for contributors, this commit abstracts the formatting step away from contributors and enables them to run ./hack/run.sh format-java to automatically format all Java code.
#3331

Added Spotless Script to hack/run.sh

---

control-plane/pkg/reconciler/consumergroup/consumergroup.go
control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
control-plane/pkg/reconciler/consumergroup/controller.go

When there is high load and multiple consumer group schedule calls,
we get many `dial tcp 10.130.4.8:9092: i/o timeout` errors when
trying to connect to Kafka.
This leads to increased "time to readiness" for consumer groups.
The downside of caching is that, in the case, partitions
increase while the result is cached we won't initialize
the offsets of the new partitions.
- Cache init offsets results in the consumer group reconciler 
```release-note
When there is high load and multiple consumer group schedule calls, we get many `dial tcp 10.130.4.8:9092: i/o timeout` errors when trying to connect to Kafka. This leads to increased "time to readiness" for consumer groups.
The downside of caching is that, in the case, partitions increase while the result is cached we won't …
```

Cache init offsets results in the consumer group reconciler (#817)

---

data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/AnyFilterBenchmark.java
data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/ExactFilterBenchmark.java
data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/FilterBenchmark.java
data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/SampleEvent.java

Fixes #3235
- Add any filter benchmarks which mirror the cases in eventing core (as well as those added in https://github.com/knative/eventing/pull/7205)

Added any filter benchmarks which mirror those in eventing core

---

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types.go
control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
control-plane/pkg/reconciler/source/source.go
control-plane/pkg/reconciler/source/source_test.go
control-plane/pkg/reconciler/testing/objects_consumer.go
control-plane/pkg/reconciler/testing/objects_consumergroup.go

This is a mitigation for https://github.com/knative/pkg/issues/2828
Before this patch, it was possible that a deleted consumer or 
consumergroup might be reconciled and never finalized when
they are deleted before the finalizer is set.
This happens because the Knative generated reconciler uses
patch (as opposed to using update) for setting the finalizer
and patch doesn't have any optimistic concurrency controls.
- Set consumer and consumergroups finalizers when creating them
```release-note
Before this patch, it was possible that a deleted consumer or 
consumergroup might be reconciled and never finalized when
they are deleted before the finalizer is set.
This happens because the Knative generated reconciler uses …
```

Set consumer and consumergroups finalizers when creating them

---

data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/AllFilterBenchmark.java
data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/ExactFilterBenchmark.java
data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/FilterBenchmark.java
data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/SampleEvent.java

Fixes #3236 
- Add benchmarks for the all filter, mirroring many of those in eventing core

Added benchmarks for the all filter, mirroring those in eventing core

---

control-plane/pkg/autoscaler/keda/keda.go

Instead of listing a potentially large number of ScaledObjects, we can limit this number to the smallest number: 1.

Improve KEDA installed check efficiency

---

test/e2e_new/new_trigger_filters_test.go

Fixes #3356 
- Move new events filter tests from experimental to e2e_new
- Port in the new tests from eventing core

Moved new trigger tests to e2e_new, added new tests

---

test/kafka/kafka-ephemeral.yaml
test/kafka/strimzi-cluster-operator.yaml

As per title. Doing bumps
- latest Strimzi upstream operator
- latest Apache Kafka version, available in the Strimzi operator
```release-note
```
**Docs**

Bump strimzi 0.38.0 and apache kafka 3.6.0

---

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_lifecycle.go
control-plane/pkg/reconciler/consumergroup/consumergroup.go
control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
control-plane/pkg/reconciler/testing/objects_consumergroup.go

This will make sure that we report finalization issues up to the KafkaSource resource.

Update ConsumerGroup status on finalization for better error reporing

---

control-plane/pkg/reconciler/consumergroup/consumergroup.go

Understanding how KEDA scales up and down Knative Kafka
resources is critical to debugging any performance problem
that the autoscaler might introduce, so we need to expose new
metrics that record mutations to Knative resources done by KEDA.
This is the table representation of the new metrics
<b style="font-weight:normal;" id="docs-internal-guid-18063e0a-7fff-7177-b469-7a67222d8f72"><div dir="ltr" style="margin-left:-12.75pt;" align="left">
Metric | Description | Type | Tags | Unit
-- | -- | -- | -- | --
kafka_controller_consumer_group_expected_replicas | Number of expected replicas for a given Kafka consumer group resource | Gauge | consumer_name (resource name) namespace_name (resource namespace) consumer_kind (resource Kind, enum: KafkaSource, Trigger, Subscription) | Dimensionless …

Add metrics to monitor the ConsumerGroup replicas changes

---

control-plane/pkg/prober/async_prober.go
control-plane/pkg/prober/async_prober_test.go
control-plane/pkg/prober/composite_prober.go
control-plane/pkg/prober/composite_prober_test.go
control-plane/pkg/prober/prober.go
control-plane/pkg/prober/prober_test.go
control-plane/pkg/prober/probertesting/mock_prober.go
control-plane/pkg/prober/probertesting/mock_prober_test.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/v2/channelv2.go
control-plane/pkg/reconciler/sink/kafka_sink.go

Fixes #3190
Fixes #3141 
- Make the async prober private, since we should only use the composite prober now that TLS is supported

Made the async prober private

---

DEVELOPMENT.md

Fixes #3297 
**Docs**
This is Docs  PR , added instruction for rekt based test and its parameters.

Add the instruction on how to run single rekt test

---

data-plane/THIRD-PARTY.txt
data-plane/core/pom.xml
data-plane/pom.xml

This PR changes the fabric8io/kubernetes-client HTTP client from okhttp to the core HTTP client and will reduce the number of transitive dependencies while also supporting IPv6 clusters (To be tested)
Related to https://github.com/knative-extensions/eventing-kafka-broker/issues/3005

Change fabric8io HTTP client from okhttp to the core HTTP client to support IPv6 clusters

---

control-plane/pkg/autoscaler/config.go
control-plane/pkg/autoscaler/keda/keda.go

Fixes Kafka source tests when KEDA is enabled (hopefully).
From discussion [here](https://github.com/kedacore/keda/discussions/4466), we shouldn't be using `activationLagThreshold` unless we want to initially scale form 0 to n>1. Hence, our scaling 0 -> 1 was not working.
- Remove activationLagThreshold parameter (letting it default to 0)
-
-
```release-note
```
**Docs**

Remove activationLagThreshold to fix 0->1 scaling

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleBuilder.java

Fixes #
- as per title: making argument final
```release-note
```
**Docs**

clean up: making argument final

---

control-plane/config/eventing-kafka-broker/100-channel/100-kafka-channel.yaml
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/channel_test.go
control-plane/pkg/reconciler/channel/controller.go
control-plane/pkg/reconciler/channel/controller_test.go
control-plane/pkg/reconciler/channel/resources/service.go
control-plane/pkg/reconciler/channel/v2/channelv2.go
control-plane/pkg/reconciler/channel/v2/channelv2_test.go
control-plane/pkg/reconciler/channel/v2/controllerv2.go
control-plane/pkg/reconciler/testing/objects_channel.go
test/e2e_new/channel_eventing_tls_test.go
test/rekt/features/channel_tls.go
test/rekt/resources/kafkachannel/kafkachannel.go

Cherry-pick https://github.com/knative-extensions/eventing-kafka-broker/pull/3406/files

[release-1.11] Cherry-pick E2E tests for channel: TLS key pair rotation #3406

---

test/e2e_new/new_trigger_filters_test.go

Follow up on https://github.com/knative-extensions/eventing-kafka-broker/pull/3505/commits/4aea9837767a0a9371106a84700cf67fc6b1533b#r1415739180
/cc @Cali0707

Cleanup NewTriggerFilters e2e test

---

control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-features.yaml
control-plane/pkg/apis/config/features.go

Fixes #3509 
- Rename config-kafka-features feature flags to be consistent with eventing core feature flag names
```release-note 
Align config-kafka-features flags to eventing core feature flags.  
```

 Rename config-kafka-features feature flags to be consistent with eventing core feature flag names

---

hack/create-kind-cluster.sh

Similar to https://github.com/knative/eventing/pull/7315/commits/243c52e6cb2f6819e51b35ed45ca7d8d86489117 to use a valid service account issuer.

Fix KinD setup with valid service account issuer

---

control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/v2/channelv2.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/testing/objects_broker.go
control-plane/pkg/reconciler/testing/objects_channel.go
control-plane/pkg/reconciler/testing/objects_sink.go
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventbus/ContractPublisher.java

With the contract now including fields to ET owner references (needed for autocreate), we should pass those values to the data plane.
- Pass the owner reference info to the data plane.

Pass event type owner references to the data plane

---

hack/control-plane.sh

Fixes #3316
- The provided [yaml](https://github.com/knative-extensions/eventing-kafka-broker/releases/download/knative-v1.12.1/eventing-kafka-post-install.yaml) on the release page has all k8s resources twice. Terraform does not like that. This PR fixes that.
```release-note
```
**Docs**

changed '>>' to '>' in order to avoid duplicated k8s resources in yamls

---

docs/channel/README.md

Fixes #3525
- Update README to remove references of old (consolidated and distributed) KafkaChannels that are not supported anymore by knative.
<!--
If this change has user-visible impact, follow the instructions below.
Examples include:
- :gift: Add new feature
- :bug: Fix bug
- :broom: Update or clean up current behavior
- :wastebasket: Remove feature or internal logic

Remove reference for consolidated KafkaChannel and distributed KafkaChannel in README

---

test/e2e_new/dls_extensions_test.go
test/e2e_new/new_trigger_filters_test.go
test/e2e_new/ordered_test.go
test/e2e_new/single_partition_config/install.go

Some tests have recently been failing in a flaky manner with errors as follows:
```
install.go:36: failed to create resource configmaps "single-partition-kafka-broker-config" already exists - Resource:
apiVersion: v1
data:
bootstrap.servers: my-cluster-kafka-bootstrap.kafka:9092
default.topic.partitions: "1"
default.topic.replication.factor: "1"
kind: ConfigMap
metadata:
name: single-partition-kafka-broker-config
namespace: test-dsvwxqja
```
- Use a randomized configmap name so that the names don't conflict

Fix flaky test failures because of single partition configmaps having the same name

---

hack/update-codegen.sh

The script already starts with a shebang that requires "bash". It is more explicit to call "bash <script>" instead of just "<script>" and doesn't require the file to be executable.
Bash needs to be available in both cases otherwise calling the script will fail.
Fixes #
- Call script by "bash <script>"
- Avoid calling chmod as this operation might not be allowed when running in a container with a specific non-root user
```release-note
```
**Docs**

Execute update-cert-manager.sh by calling bash directly

---

data-plane/benchmarks/run.sh

To better measure filter benchmarks, we should also profile gc
- Add gc profiling to the benchmarks so we can see how memory usage changes

Add gc profiling to the benchmarks

---

test/e2e_new/broker_config_test.go

skips TestBrokerWithConfig because of  https://github.com/knative-extensions/eventing-kafka-broker/issues/3592
- :broom: skip TestBrokerWithConfig to not rely on the obsolete Strimzi "Bidirectional Topic Operator"

skip TestBrokerWithConfig

---

control-plane/pkg/reconciler/source/source.go

This helps debugging issues of slow deletions

Propagate ConsumerGroup status on KafkaSource deletion

---

control-plane/pkg/reconciler/testing/factory.go
control-plane/pkg/reconciler/trigger/trigger_test.go

Currently we ignore a TableTests row.Ctx value in `NewFactory`.
This PR addresses it and takes a `Ctx` from a TableRow into account, when setting up the constructor via `NewFactory`

Don't ignore Context from TableRow in `NewFactory()`

---

hack/data-plane.sh

This ensures that even in local development when running `./hack/run.sh deploy` without a new Git commit the deployments are updated with the new image, besides the other benefits of using digests.

Use image digests for data plane images

---

data-plane/THIRD-PARTY.txt
data-plane/core/pom.xml
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/oidc/OIDCDiscoveryConfig.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/oidc/OIDCInfo.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/oidc/TokenVerifier.java
data-plane/pom.xml

Fixes partially #3573
- :gift: Adds a helper to verify JWT tokens and OIDC discovery.
An "in action example" of the setup and configuration can be seen at:
https://github.com/knative-extensions/eventing-kafka-broker/blob/9aafcece35118fb1290734dd9a98cb3557764d66/data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java#L150-L153

Add OIDC TokenVerifier

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/oidc/TokenVerifier.java

Currently we have a log line, which logs the JWT. This should not be logged.
/cc @pierDipi @Cali0707 @Leo6Leo

Remove sensitive logs from TokenVerifier

---

test/rekt/features/kafka_source.go

As per title. Otherwise we have issues with eventing-istio e2e tests
/cc @pierDipi

Skip KafkaSource TLS tests on Istio

---

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types.go
control-plane/pkg/reconciler/consumer/consumer.go

Maybe helps fix the errors we are seeing with consumer/consumergroups
- Check if the pointer fields on consumer/consumergroups are not nil before dereferencing them

Fix possible nil pointer dereferences on Consumer/ConsumerGroup

---

data-plane/pom.xml

Signed-off-by: Valen Mascarenhas [Valen.Mascarenhas@ibm.com](mailto:Valen.Mascarenhas@ibm.com)
Fixes https://github.com/knative-extensions/eventing-kafka-broker/issues/3643
Proposed Changes
This PR enables the Docker image build for the dataplane components (including receiver and dispatcher) for the ppc64le architecture. For this it leverages jib's multi-arch Docker image build capabilities.
Release Note
`Add support ppc64le architecture.`

Added architecture ppc64le to jib maven build task

---

test/e2e-common.sh

Currently we miss to include the TLS resources in the release test setup

Include TLS resources in release test setup

---

data-plane/pom.xml

Signed-off-by: Valen Mascarenhas [Valen.Mascarenhas@ibm.com](mailto:Valen.Mascarenhas@ibm.com)
**Fixes** 
https://github.com/knative-extensions/eventing-kafka-broker/issues/3643
**Proposed Changes**
This PR enables the Docker image build for the dataplane components (including receiver and dispatcher) for the ppc64le architecture. For this it leverages jib's multi-arch Docker image build capabilities.
`Add support ppc64le architecture.`

[release-1.12] Enable receiver and dispatcher Docker images for ppc64le architecture

---

data-plane/pom.xml

Signed-off-by: Valen Mascarenhas [Valen.Mascarenhas@ibm.com](mailto:Valen.Mascarenhas@ibm.com)
**Fixes** 
https://github.com/knative-extensions/eventing-kafka-broker/issues/3643
**Proposed Changes**
This PR enables the Docker image build for the dataplane components (including receiver and dispatcher) for the ppc64le architecture. For this it leverages jib's multi-arch Docker image build capabilities.
`Add support ppc64le architecture.`

[release-1.13] Enable receiver and dispatcher Docker images for ppc64le architecture

---

control-plane/pkg/apis/sources/v1beta1/kafka_lifecycle.go
control-plane/pkg/reconciler/source/controller.go
control-plane/pkg/reconciler/source/controller_test.go
control-plane/pkg/reconciler/source/source.go
control-plane/pkg/reconciler/source/source_test.go
control-plane/pkg/reconciler/testing/objects_source.go

Fixes #3658
- :gift: Create KafkaSources OIDC service account and expose in its status
```release-note
Create KafkaSources OIDC service account and expose in its status
```

Create KafkaSources OIDC service account and expose in its status

---

control-plane/config/eventing-kafka-broker/200-webhook/500-webhook.yaml

Fixes #
Merge keys are not officially supported in YAML according to its specifications. These keys are associated with an older version of YAML (1.1), which is now considered obsolete. Additionally, these merge keys haven't been updated or included in the current YAML version (1.2), so there's no guarantee that they will function as expected or be supported. In summary, using merge keys in YAML might not work reliably and is not recommended due to these limitations and lack of support in the latest YAML version.
I attempted to install the YAML mentioned using Kustomize, but the installation failed because Kustomize couldn't properly interpret or render the YAML file.
- I suggest that we avoid utilizing merge tags to ensure compliance with YAML specifications, particularly in the latest …

feat: remove yaml merge tag

---

data-plane/pom.xml

Signed-off-by: Valen Mascarenhas [Valen.Mascarenhas@ibm.com](mailto:Valen.Mascarenhas@ibm.com)
Fixes 
https://github.com/knative-extensions/eventing-kafka-broker/issues/3643
**Proposed Changes**
This PR enables the Docker image build for the dataplane components (including receiver and dispatcher) for the ppc64le architecture. For this it leverages jib's multi-arch Docker image build capabilities.
`Add support ppc64le architecture.`

[release-1.11] Enable receiver and dispatcher Docker images for ppc64le architecture

---

control-plane/pkg/reconciler/trigger/controller.go

The current global resync accidently queues triggers that aren't associated with our brokers.
This fixes flakes like 
```
TestTriggerNoFinalizer/0/Unknown_Broker_Class_-_Unknown/Assert/eventually_trigger_has_no_finalizer
```
in https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/3671/reconciler-tests_eventing-kafka-broker_main/1755226033222586368

Use filtered global resync for triggers

---

control-plane/config/eventing-kafka-broker/200-controller/200-controller-cluster-role.yaml
data-plane/config/broker/200-broker-data-plane-cluster-role.yaml
data-plane/config/channel/200-channel-data-plane-cluster-role.yaml
data-plane/config/source/200-source-data-plane-cluster-role.yaml
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/oidc/TokenProvider.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleBuilder.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java
test/e2e_new_channel/kafka_channel_test.go

Fixes #3578
- :gift: Add OIDC token to requests, when target (subscriber/reply/DLS) has an audience set
```release-note
Authenticate requests in case target has an OIDC audience set
```

Dispatcher authenticate requests

---

control-plane/pkg/kafka/topic.go
control-plane/pkg/kafka/topic_test.go

Fixes #1638 
- Parse all configmap values with prefix `default.topic.config.` into the topic config entries
This approach allows us to support any future changes to the kafka topic config options automatically. The user will still get a message when they provide an incorrect config option as the kafka server will reject the create topic request telling them what went wrong:
```
lastTransitionTime: "2024-02-05T21:25:12Z"
message: 'kafka server: Configuration is invalid - Unknown topic config name: unknown-config'
reason: 'Failed to create topic: knative-broker-default-broker-3'
status: "False"
type: Ready
```
```release-note
Auto created topics by brokers now support the full set of topic config options, set them by using the prefix `default.topic.config.` in your …
```

feat: kafka broker now supports all kafka topic config options

---

control-plane/config/eventing-kafka-broker/100-kafka-internal/100-consumergroup.yaml
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types.go
control-plane/pkg/reconciler/consumergroup/consumergroup.go
control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
control-plane/pkg/reconciler/testing/objects_consumergroup.go

Currently, we don't define the scale subresource correctly on the consumergroup, as we say that the `labelSelectorPath` is `.status.selector`, while we set `.spec.selector` instead. See the code here: https://github.com/knative-extensions/eventing-kafka-broker/blob/6012e1b19b407b20286c6b7c553f7acf4ec071a0/control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_defaults.go#L41-L43
I believe this should fix the "SelectorRequired" warnings we see on the scaled objects reported in https://github.com/knative/eventing/issues/7655
- Set the .status.selector json path with the required values
-
-
```release-note
:bug: the scale subresource is now correctly defined for consumergroups
```
**Docs**

fix selector path for cg scale subresource

---

control-plane/pkg/reconciler/consumergroup/controller.go

This should help with reducing API server calls

Only global resync when the replicas of the STS change

---

test/e2e_new/broker_test.go
test/e2e_new/templates/kafka-broker/broker.yaml

Fixes #3684
- :gift: Add OIDC e2e tests for Broker
The call in reconciler-tests.sh to run the OIDC tests was added in #3675 already:
https://github.com/knative-extensions/eventing-kafka-broker/blob/d6a383fff58047078c232f83bdcbe9e88d402891/test/reconciler-tests.sh#L57-L61

Add broker OIDC e2e tests

---

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_lifecycle.go
control-plane/pkg/reconciler/consumer/consumer.go
control-plane/pkg/reconciler/consumer/consumer_test.go

This will make clear the reasons for BindInProgress status, especially when pods cannot be scheduled when there are not enough resources

Expose reasons for BindInProgress by adding pod status summary

---

control-plane/pkg/reconciler/broker/broker.go

Fixes #2914
- Stash only relevant broker config keys on the broker status
- 
```release-note
```
**Docs**

Stash only relevant broker config keys on the broker status

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/oidc/OIDCDiscoveryConfig.java

Fixes #3674 
- :bug: Check status code of response of OIDC discovery before setting up OIDC info to prevent JSON parse exception

Check status code of OIDC discovery response

---

control-plane/pkg/core/config/utils.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/consumer/consumer.go
control-plane/pkg/reconciler/sink/kafka_sink.go

As per title
This will be E2E tested with tests in https://github.com/knative/eventing/pull/7726

Detect trust bundles changes

---

go.mod
go.sum
vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
vendor/modules.txt

- lastest of Go-Sdk
```release-note
Using 2.15.2 of Go-sdk for CloudEvents
```
**Docs**

Bump CloudEvents GO-SDK to 2.15.2

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventbus/ContractPublisher.java

As per title to have this issue not missed.

Use error log level when contract parsing fails

---

test/e2e_new/main_test.go
test/pkg/logging/logging.go

Currently, the e2e tests just use `kubectl logs -f ...` to collect logs. This leads to issues if the pod goes away, as no more logs are collected. We have been seeing this in CI recently with the logs from the kafka-controller only including about 5 minutes worth of logs.
- Use a go based logging solution that picks up on any new pods and starts gathering those logs too.
- Put this into a separate directory so that we can ensure that this works before fully switching the logging solution used in CI

Replace bash script log collector with a more resilient go based log collector

---

go.mod
go.sum
vendor/modules.txt

- Unpin CE kafka protocol from oder version, and use latest
```release-note
:broom: Unpin CE kafka protocol from oder version, and use latest
```
**Docs**

Unpin CE Kafka protocol version from older version

---

test/pkg/logging/logging.go

On #3735 we discussed adding timestamps to the names for log files so that it is easy to see when the log collection started
- Add timestamp to the log file names

Add timestamp to filename for logs

---

go.mod
go.sum
vendor/modules.txt

Same as #3754 - but for 1.13 
```release-note
:broom: Unpin CE kafka protocol from oder version, and use latest
```
**Docs**

[release-1.13] Unpin CE Kafka protocol version from older version

---

test/e2e_new/broker_sasl_ssl_test.go
test/kafka/kafka_setup.sh
test/kafka/user-sasl-scram-512-restricted.yaml
test/pkg/run.go
test/rekt/features/broker_auth.go
test/rekt/resources/kafkaauthsecret/kafkaauthsecret.go

https://github.com/knative-extensions/eventing-kafka-broker/issues/3328 has a unit test, but we don't have an e2e test that would verify that it is indeed possible to configure Kafka ACLs that would allow only topic and consumer IDs with the defined prefixes. 
- An e2e test for https://github.com/knative-extensions/eventing-kafka-broker/issues/3328

[e2e test] for broker topic and trigger consumer id templates being used

---

data-plane/dispatcher-loom/pom.xml
data-plane/receiver-loom/pom.xml

Fixes #
#3776 
This PR enables the Docker image build for the dataplane components receiver-loom and dispatcher-loom for the s390x and ppc64le architecture. For this it leverages jib's multi-arch Docker image build capabilities.

adding s390x and ppc64le platform for loom based builds

---

control-plane/pkg/kafka/clientpool/client_test.go
control-plane/pkg/kafka/clientpool/clientpool.go
control-plane/pkg/kafka/clientpool/clusteradmin.go
control-plane/pkg/kafka/clientpool/clusteradmin_test.go
control-plane/pkg/kafka/testing/admin_mock.go
control-plane/pkg/kafka/testing/client_mock.go

Fixes #3780 
- Add a proxy for the cluster admin so that fatal errors are recovered from properly there too
- Add regression tests to make sure that the client and cluster admin proxies

Add cluster admin proxy

---

test/e2e_new/broker_test.go
test/rekt/features/kafka_source.go
test/rekt/features/keda_scaling.go

Fixes #3238
- Refactor consumergroup scale checks to be more generic
- Add a test that verifies that triggers scale up and down
```release-note
The kafka-broker-dispatcher StatefulSet now scales with KEDA if you enable the controller-autoscaler-keda feature flag
```
**Docs**

test: triggers scale with KEDA

---

control-plane/pkg/reconciler/consumergroup/evictor.go
control-plane/pkg/reconciler/consumergroup/evictor_test.go

Fixes bug where kafka controller panics due to the evictor accessing properties on a nil pod.
- Don't use the pod variable, as we only use it to decorate the logger currently.
- Add a unit test to catch regressions

fix: evictor no longer has NPE when called with nil pod

---

control-plane/config/eventing-kafka-broker/100-channel/100-kafka-channel.yaml

In https://github.com/knative/eventing/pull/7733 we added the `.spec.subscribers[].name` field for Channels. This PR adjusts the KafkaChannel to support this field too.
This helps with tests issues from https://github.com/knative-extensions/eventing-kafka-broker/pull/3770

Add `.spec.subscribers[].name` field in KafkaChannel to align with eventing-core channel definition

---

test/e2e-common.sh
test/upgrade/installation/githead.go

Currently, the scripts we use to install eventing and eventing kafka broker components in the upgrade tests do not install a previous release of eventing when installing the previous release of eventing kafka broker. This can cause some test failures due to incompatible versioning.
- Install the previous eventing release along with the previous eventing kafka broker release
- Install the latest eventing nightly when upgrading to the newer eventing kafka broker code

Upgrade tests install eventing core from release

---

.github/workflows/knative-profile-data-plane.yaml
data-plane/dispatcher-loom/pom.xml
data-plane/dispatcher-loom/src/main/java/dev/knative/eventing/kafka/broker/dispatcherloom/LoomKafkaConsumer.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/Main.java
data-plane/profiler/resources/config-logging.xml
data-plane/profiler/run.sh
data-plane/receiver-loom/pom.xml
data-plane/receiver-loom/src/main/java/dev/knative/eventing/kafka/broker/receiverloom/LoomKafkaProducer.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java

As per title
- Introduce a `ENABLE_VIRTUAL_THREADS` env variable to enable virtual threads, default to real threads for now
- Add shade plugin to create an uber jar file
-  Define empty features config path
- Catch `Exception` and not only `ExecutionException` when missing  features config path
- Use normal threads until we stress test loom threads more
- Fix profiler job

Introduce a `ENABLE_VIRTUAL_THREADS` env variable to enable virtual threads, default to real threads for now

---

control-plane/cmd/post-install/kafka_namespaced_broker_deployment_deleter.go
control-plane/cmd/post-install/main.go
control-plane/config/post-install/200-controller-cluster-role.yaml

We currently only delete broker deployments in the system namespace. However, namespaced brokers could have deployments in any namespace. 
Fixes [#3815](https://github.com/knative-extensions/eventing-kafka-broker/issues/3815)

Add post install logic for namespaced brokers

---

control-plane/cmd/post-install/kafka_namespaced_broker_deployment_deleter.go
control-plane/config/post-install/200-controller-cluster-role.yaml

Backport for https://github.com/knative-extensions/eventing-kafka-broker/pull/3889

[release-1.14] Add post install logic for namespaced brokers (#3889)

---

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/register.go
control-plane/pkg/reconciler/consumer/controller.go
control-plane/pkg/reconciler/consumergroup/controller.go

Fixes #3824 
- Check the owner kind for the consumergroup and only requeue it if necessary for a given statefulset change

only requeue consumergroups from appropriate statefulset on change

---

control-plane/pkg/reconciler/consumergroup/consumergroup.go

Fixes #3669 
Remove Keda objects during reconciliation if [configmap] **config-kafka-features/controller-autoscaler-keda** is set to `disabled`.
```release-note
- remove Keda objects during reconciliation
```
* early feedback welcome / will add unit tests before marking it as ready

feat: remove keda objects during reconciliation

---

control-plane/pkg/contract/extensions.go
control-plane/pkg/core/config/egress.go
control-plane/pkg/core/config/egress_test.go
control-plane/pkg/core/config/resource.go
control-plane/pkg/core/config/resource_test.go
control-plane/pkg/reconciler/base/reconciler.go
control-plane/pkg/reconciler/base/reconciler_test.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/v2/channelv2.go
control-plane/pkg/reconciler/consumer/consumer.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/trigger/trigger.go
control-plane/pkg/reconciler/trigger/trigger_test.go

This guards and discard contract ConfigMap updates when only `generation`
changes.
While this approach is technically slightly slower, the latency is negligible,
and it is more robust and easier to maintain.
- guards and discard contract ConfigMap updates when only `generation`
changes
- move change detection to the shared library
```release-note
Prevent unnecessary ConfigMap updates and reduce API server load
```
**Docs**

Prevent generation only updates

---

test/e2e_new/broker_not_ready_test.go

This is limiting our ability to merge PRs, skipping for now

Skip flaky TestBrokerNotReadyAfterBeingReady test for namespaced Broker

---

control-plane/pkg/autoscaler/keda/keda.go

Fixes #3939 
- Only add the authentication ref to the scaled object if there is something to reference
```release-note
:bug: KEDA ScaledObjects are now only created with an authentication ref if there is a trigger authentication object to reference
```

fix: only add authentication ref to scaled objects when there is an actual value to reference

---

test/e2e_new/kafka_source_test.go
test/rekt/features/keda_scaling.go

As a follow up on #3939 this PR adds a regression test to prevent this issue from coming back
- Verify that the scaledobject created by a KafkaSource's consumergroup does not have an authentication ref unless it needs to

test: verify that scaledobjects have no authenticationref when it is empty

---

go.mod

Fixes issues with `go mod tidy` resulting from an incorrect go mod file. See https://github.com/golang/go/issues/62278#issuecomment-1693538776 for more info
- Move from `go 1.22` to explicit `go 1.22.3`

fix: go version in go mod is correct now

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeCreatorImpl.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeListerFactory.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeCreatorImplTest.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactoryTest.java

Currently, there are some error logs in the namespaced broker data plane stating that "the data-plane does not have sufficient permissions to list/watch eventtypes"
- Use namespaced listers instead of a global lister
```release-note
:bug: The namespaced broker receiver only tries to list eventtypes in it's own namespace
```

Move to using namespaced listers for eventtypes in data plane

---

data-plane/dispatcher-loom/src/main/java/dev/knative/eventing/kafka/broker/dispatcherloom/LoomKafkaConsumer.java

Seeing quite a lot of InterruptedExceptions when deleting triggers, 
```
{"@timestamp":"2024-06-27T12:26:59.548Z","@version":"1","message":"[Consumer clientId=consumer-knative-trigger-kb-newsubs-k8s-0-connection0-363-1179, groupId=knative-trigger-kb-newsubs-k8s-0-connection0-363] Failed to close coordinator","logger_name":"org.apache.kafka.clients.consumer.KafkaConsumer","thread_name":"","level":"ERROR","level_value":40000,"stack_trace":"org.apache.kafka.common.errors.InterruptException: java.lang.InterruptedException\n\tat org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeThrowInterruptException(ConsumerNetworkClient.java:535)\n\tat org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:296)\n\tat …
```

LoomKafkaConsumer::close let closing task finish before interrupting

---

go.mod

Reverts knative-extensions/eventing-kafka-broker#3950
I think if everything and us start using 1.22 installations, we wouldn't need this

Revert "fix: go version in go mod is correct now"

---

data-plane/THIRD-PARTY.txt
data-plane/core/pom.xml

Remove unused vertx-kafka-client from dependencies

---

control-plane/pkg/reconciler/consumer/consumer.go
control-plane/pkg/reconciler/trigger/trigger.go
control-plane/pkg/reconciler/trigger/trigger_test.go
test/experimental/features_config/features.yaml

As part of moving the new trigger filters feature to GA, this PR removes the feature flag
- Remove the feature flag
```release-note
The new-trigger-filters feature flag has been removed, and the feature is now GA.
```
**Docs**

feat: removed new trigger filters feature flag

---

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_validation.go
control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_validation_test.go
control-plane/pkg/reconciler/consumergroup/consumergroup.go

Fixes #3935
- Only defer closing the cluster admin if it is not nil
- Check that the configs map exists before accessing a value in it
```release-note
The kafka controller does not panic on invalid kafka client configmaps anymore
```

fix: kafka controller does not panic on invalid kafka client config

---

control-plane/pkg/security/secrets_provider_net_spec.go
control-plane/pkg/security/secrets_provider_net_spec_test.go

In the clientpool code, we use the name and namespace of a secret along with the bootstrap servers to uniquely identify the connections being created. However, the virtual secrets created from the net spec did not have these fields set.
- Create a name for the virtual secret by concatenating all secret names
- Create a namespace for the virtual secret by concatentatinf all secret namespaces

fix: virtual secrets created from netspec have name and namespace

---

control-plane/pkg/kafka/clientpool/clientpool.go
control-plane/pkg/kafka/clientpool/clientpool_test.go
control-plane/pkg/kafka/clientpool/clusteradmin.go
control-plane/pkg/kafka/testing/admin_mock.go
control-plane/pkg/kafka/testing/client_mock.go

Fixes #3999
Currently, when creating a cluster admin from a client, we increment the client wait group once, but this causes the group to be incremented twice as it was already incremented once when retrieving the client from the clientpool. This leads to the client not being able to be closed.
- Increment the wait group once for client, once for clusteradmin rather than twice in the latter case.

fix: do not double increment clientpool wg

---

control-plane/config/post-install/200-controller-cluster-role.yaml

Fixes #4000 
- Add the missing rbac verb for the post install to work properly

fix: correct clusterrole permissions for post install job

---

control-plane/pkg/kafka/clientpool/clientpool_test.go

Fixes https://github.com/knative-extensions/eventing-kafka-broker/issues/4023
Tested with
```
$ go test -run TestClientCloses -count=42 -parallel=42 ./control-plane/pkg/kafka/clientpool/
ok      knative.dev/eventing-kafka-broker/control-plane/pkg/kafka/clientpool    98.083s
```
- Do not use sleep and instead use eventually with a longer timeout
```release-note
```
**Docs**

TestClientCloses consistently passes

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeCreator.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeCreatorImpl.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeListerFactory.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeCreatorImplTest.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/IngressProducer.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStore.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/IngressRequestHandlerImpl.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStoreTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/AuthenticationHandlerTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/IngressRequestHandlerImplTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactoryTest.java
data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/AbstractDataPlaneTest.java

Fixes continued bugs with the EventType lister/indexer failing to watch EventTypes at the cluster scope.
- Use namespaced indexers as well as listers
- Create indexer/lister in the IngressProducerReconcilableStore instead of on the request path to make autocreate faster
-
```release-note
Fixed bug where EventTypes are watched at the cluster scope
```

feat: use namespaced indexers for eventtypes in receiver

---

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java
data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/file/FileWatcherTest.java

Filesystem notifications might be triggered more times than expected so check for greater or equal to.

FileWatcherTest consistently pass

---

control-plane/pkg/prober/async_prober.go
control-plane/pkg/prober/cache.go
control-plane/pkg/prober/cache_test.go

Fixes #4012
- Add a way to specify the default return value of a cache
- Specify the default return value for the prober cache

fix: prober cache returns StatusUnknown by default

---

control-plane/pkg/reconciler/base/reconciler.go
control-plane/pkg/reconciler/base/reconciler_test.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/controller.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/controller.go
control-plane/pkg/reconciler/channel/v2/channelv2.go
control-plane/pkg/reconciler/consumer/consumer.go
control-plane/pkg/reconciler/sink/controller.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/trigger/trigger.go
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/oidc/OIDCDiscoveryConfigListener.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactoryTest.java
data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/AbstractDataPlaneTest.java

Manual cherry pick of #4021 so that we only rebuild the OIDC Discovery config when needed

[release-1.14] fix: do not build OIDC config unless enabled (#4021)

---

control-plane/pkg/reconciler/base/reconciler.go
control-plane/pkg/reconciler/base/reconciler_test.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/controller.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/controller.go
control-plane/pkg/reconciler/consumer/consumer.go
control-plane/pkg/reconciler/sink/controller.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/trigger/trigger.go
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/oidc/OIDCDiscoveryConfigListener.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java
data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactoryTest.java
data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/AbstractDataPlaneTest.java

This is a cherry pick of #4021 so that the OIDC config is only built when needed

[release-1.15] fix: do not build OIDC config unless enabled (#4021)

---

control-plane/config/eventing-kafka-broker/100-channel/100-kafka-channel.yaml
control-plane/config/eventing-kafka-broker/100-sink/100-kafka-sink.yaml
control-plane/pkg/apis/eventing/v1alpha1/kafka_sink_types.go
control-plane/pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go

Fixes #4069 
- Adding the AppliedEventPoliciesStatus to the KafkaSink type and CRD
- Adding the AppliedEventPoliciesStatus to the KafkaChannel (in the go type it is already available through the ChannelableStatus, but not in the YAML CRD)

Update KafkaSink and KafkaChannel to have AppliedEventPoliciesStatus

---

control-plane/pkg/contract/contract.pb.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/sink/kafka_sink_test.go
test/e2e_new/sink_auth_test.go
test/rekt/resources/kafkasink/kafkasink.go
test/rekt/resources/kafkatopic/topic.go

- Provision a KafkaSinks `.status.address.audience` and `.status.addresses[*].audience` field
/cherry-pick release-1.15
/cherry-pick release-1.14

Expose OIDC audience of KafkaSink in its status

---

control-plane/pkg/contract/contract.pb.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/sink/kafka_sink_test.go
test/e2e_new/sink_auth_test.go
test/rekt/resources/kafkasink/kafkasink.go
test/rekt/resources/kafkatopic/topic.go

Cherry-pick of #4067
Same as #4071 but fixes build issues
/cherry-pick release-1.14

[release-1.15] Expose OIDC audience of KafkaSink in its status

---

control-plane/pkg/apis/eventing/v1alpha1/kafka_sink_lifecycle.go
control-plane/pkg/core/config/utils.go
control-plane/pkg/core/config/utils_test.go
control-plane/pkg/reconciler/broker/broker.go
control-plane/pkg/reconciler/broker/broker_test.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/sink/controller.go
control-plane/pkg/reconciler/sink/kafka_sink.go
control-plane/pkg/reconciler/sink/kafka_sink_test.go
control-plane/pkg/reconciler/testing/objects_sink.go

Fixes #4039 
- :gift: List applying EventPolicies in KafkaSink
```release-note
List applying EventPolicies in KafkaSink
```

List applying EventPolicies in KafkaSink

---

test/e2e_new/broker_test.go
test/e2e_new/sink_auth_test.go
test/e2e_new_channel/kafka_channel_test.go

Fixes #4068
- :gift: Enable AuthZ e2e tests for KafkaSink
- :gift: Enable AuthZ e2e tests for KafkaChannel
Hint: AuthZ test for Broker were already enabled in https://github.com/knative-extensions/eventing-kafka-broker/pull/4086/commits/99f3b33e15ee5608726ed22aec020856c6112f2f
requires:
* #4038 
* #4039

Enable AuthZ e2e tests

---

data-plane/dispatcher-loom/src/main/java/dev/knative/eventing/kafka/broker/dispatcherloom/LoomKafkaConsumer.java
data-plane/receiver-loom/src/main/java/dev/knative/eventing/kafka/broker/receiverloom/LoomKafkaProducer.java

Follows up to https://github.com/knative-extensions/eventing-kafka-broker/pull/3957  , but for LoomKafkaProducer, and unifies the approach
Instead of interrupting the `BlockingQueue::take`, we just use `poll` in the background thread, so we don't have to deal with interrupting the thread, so we now don't accidentally interrupt the actual processing of the queued tasks.
Instead of waiting for the Thread to be marked as "finished", we just wait by `Thread::join`. The only way it would block forever, is if the processing of the task would wait forever.
- :broom: LoomKafkaProducer|Consumer let the background thread finish itself

LoomKafkaProducer|Consumer let the background thread finish itself

---

control-plane/pkg/reconciler/channel/controller.go

Fix for panic
```
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1f9a4c0, 0x3a9fbb0})
/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000ec6380?})
/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x1f9a4c0?, 0x3a9fbb0?})
/usr/lib/golang/src/runtime/panic.go:770 +0x132
knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/channel.NewController.HandleAll.PassNew.func12({0x4?, 0x23?}, {0x22c8200?, 0xc0033a2000?})
/go/src/github.com/openshift/origin/vendor/knative.dev/pkg/controller/controller.go:76 +0x1c
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...) …
```

Set globalResync function for KafkaChannel reconciler

---

control-plane/cmd/kafka-controller/main.go
control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml
control-plane/pkg/kafka/clientpool/clientpool.go
control-plane/pkg/reconciler/broker/controller.go
control-plane/pkg/reconciler/broker/namespaced_controller.go
control-plane/pkg/reconciler/channel/controller.go
control-plane/pkg/reconciler/consumergroup/controller.go
control-plane/pkg/reconciler/sink/controller.go
control-plane/pkg/reconciler/trigger/controller.go
control-plane/pkg/reconciler/trigger/namespaced_controller.go

Add 3 new environment variables:
```
ENABLE_SARAMA_LOGGER       (default: false)
ENABLE_SARAMA_DEBUG_LOGGER (default: false)
ENABLE_SARAMA_CLIENT_POOL  (default: true)
```
I want to see if these help with giving more information to debug this issue: https://github.com/knative-extensions/eventing-kafka-broker/issues/4091

Allow enabling sarama logging and disabling client pool

---

control-plane/pkg/reconciler/consumergroup/consumergroup.go
control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
control-plane/pkg/reconciler/testing/objects_broker.go
control-plane/pkg/reconciler/testing/objects_channel.go
control-plane/pkg/reconciler/testing/objects_common.go
control-plane/pkg/reconciler/testing/objects_source.go

This ensures that our `consumergroup` controller only match v2-specific pods and won't try to reconcile pods that belong to the previous deployment.
Seen here https://github.com/knative-extensions/eventing-kafka-broker/issues/4091 with
```
failed to schedule consumers: failed to get data plane volume kafka-resources
in pod knative-eventing/kafka-broker-dispatcher-6b6855d6c5-7nhtw
```
so the consumergroup controller is trying to reconcile a pod that is not of the statefulset but for the "old" deployment

Use v2 specific label to avoid matching previous deployment-based dispatchers

---

control-plane/cmd/kafka-controller/main.go
control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml
control-plane/pkg/kafka/clientpool/clientpool.go
control-plane/pkg/reconciler/broker/controller.go
control-plane/pkg/reconciler/broker/namespaced_controller.go
control-plane/pkg/reconciler/channel/controller.go
control-plane/pkg/reconciler/consumergroup/controller.go
control-plane/pkg/reconciler/sink/controller.go
control-plane/pkg/reconciler/trigger/controller.go
control-plane/pkg/reconciler/trigger/namespaced_controller.go

Backport of https://github.com/knative-extensions/eventing-kafka-broker/pull/4103

[release-1.15] Allow enabling sarama logging and disabling client pool (#4103)

---

control-plane/cmd/kafka-controller/main.go
control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml
control-plane/pkg/kafka/clientpool/clientpool.go
control-plane/pkg/reconciler/broker/controller.go
control-plane/pkg/reconciler/broker/namespaced_controller.go
control-plane/pkg/reconciler/channel/controller.go
control-plane/pkg/reconciler/consumergroup/controller.go
control-plane/pkg/reconciler/sink/controller.go
control-plane/pkg/reconciler/trigger/controller.go
control-plane/pkg/reconciler/trigger/namespaced_controller.go

Backport of https://github.com/knative-extensions/eventing-kafka-broker/pull/4103

[release-1.14] Allow enabling sarama logging and disabling client pool (#4103)

---

control-plane/pkg/reconciler/consumergroup/consumergroup.go
control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
control-plane/pkg/reconciler/consumergroup/controller.go
go.mod
go.sum
vendor/knative.dev/eventing/pkg/scheduler/scheduler.go
vendor/knative.dev/eventing/pkg/scheduler/state/helpers.go
vendor/knative.dev/eventing/pkg/scheduler/state/state.go
vendor/knative.dev/eventing/pkg/scheduler/statefulset/autoscaler.go
vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
vendor/modules.txt

Bring https://github.com/knative/eventing/pull/8202 here

Upgrade knative.dev/eventing to latest 1.15

---

control-plane/pkg/reconciler/consumergroup/consumergroup.go
control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
control-plane/pkg/reconciler/consumergroup/controller.go
go.mod
go.sum
vendor/knative.dev/eventing/pkg/apis/feature/features.go
vendor/knative.dev/eventing/pkg/apis/sources/v1/container_lifecycle.go
vendor/knative.dev/eventing/pkg/auth/serviceaccount.go
vendor/knative.dev/eventing/pkg/kncloudevents/event_dispatcher.go
vendor/knative.dev/eventing/pkg/reconciler/testing/v1/containersource.go
vendor/knative.dev/eventing/pkg/scheduler/scheduler.go
vendor/knative.dev/eventing/pkg/scheduler/state/helpers.go
vendor/knative.dev/eventing/pkg/scheduler/state/state.go
vendor/knative.dev/eventing/pkg/scheduler/statefulset/autoscaler.go
vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
vendor/knative.dev/eventing/test/rekt/features/trigger/feature.go
vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.go
vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.yaml
vendor/modules.txt

Bring https://github.com/knative/eventing/pull/8203 here

[release-1.14] Upgrade knative.dev/eventing to latest 1.14 

---

control-plane/pkg/apis/eventing/v1alpha1/implements_test.go
control-plane/pkg/apis/sources/v1beta1/implements_test.go

Fixes #
- adding tests similar to eventing core counterparts 
```release-note
```
**Docs**

KafkaSource/Sink: Adding interface implementation test

---

data-plane/contract/pom.xml
data-plane/pom.xml
data-plane/profiler/run.sh

We use spotless to reformat Java code and editor config is not used anymore.

Remove unused editor config Java plugin

---

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types.go
control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/channel/channel_test.go
control-plane/pkg/reconciler/consumer/consumer.go
control-plane/pkg/reconciler/testing/objects_consumergroup.go
control-plane/pkg/reconciler/trigger/v2/triggerv2.go
control-plane/pkg/reconciler/trigger/v2/triggerv2_test.go

Previously to v2, we were setting `name` to the Broker or Channel name of the resource.

Set the `name` value for metrics tags to the correct top-level resource

---

control-plane/pkg/reconciler/consumergroup/auth.go
control-plane/pkg/reconciler/consumergroup/consumergroup.go

The `consumergroup` reconciler was using the legacy secret format resolver to configure the Sarama client even in the Kafka Broker case.
We can't really add a E2E regression test as strimzi doesn't support `SASL/PLAIN`: see `strimzi/strimzi-kafka-operator/issues/2221`
Fixes #4091
-
-
-
```release-note
Fix `EOF` errors when using `SASL_SSL` `PLAIN` to connect to Apache Kafka cluster.
```
**Docs**

[release-1.14] Fix EOF errors when using `SASL_SSL` `PLAIN`

---

control-plane/pkg/reconciler/channel/channel.go
control-plane/pkg/reconciler/consumer/consumer.go
control-plane/pkg/security/secrets_provider_legacy_channel_secret.go
control-plane/pkg/security/secrets_provider_net_spec.go
test/e2e-common.sh
test/rekt/features/kafka_source.go
test/rekt/features/kafka_source_create_secrets_after.go

KafkaChannel has historically used the "legacy" secret format,
however, it has limitations as not having the explicit protocol
configuration, we're left with guessing the protocol.
We will continue supporting the "legacy" format, however,
we will encourage users to use the new secret format, so that
it can also be used for Kafka Broker, KafkaChannel and KafkaSink.
Fixes #4123
Fixes #2231
- Support explicit protocol configuration in KafkaChannel secret to align Broker, KafkaChannel and KafkaSink
```release-note
Support explicit protocol configuration in KafkaChannel secret so that the same format as Kafka Broker secrets can be used for KafkaChannel authentication configuration.
```
**Docs**

Support explicit protocol configuration in KafkaChannel secret 

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherMutatorChain.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/CloudEventOverridesMutator.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherMutatorChainTest.java
data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/CloudEventOverridesMutatorTest.java

Invalid records shouldn't block consuming events.
The record will eventually end up here and discarded: 
https://github.com/knative-extensions/eventing-kafka-broker/blob/main/data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java#L168-L177
Fixes #4129
- Discard invalid consumer records

Discard invalid consumer records

---

test/e2e-common.sh

Describe sacura resources when they don't become ready

---

control-plane/config/eventing-kafka-broker/200-controller/200-controller-cluster-role.yaml

This is required otherwise KafkaBroker and KafkaSource can't forward events to JobSink. This type of error is thrown on Kafka Broker status:
```
failed to reconcile contract: failed to reconcile egress: failed to resolve subscriber: failed to get lister for sinks.knative.dev/v1alpha1, Resource=jobsinks: jobsinks.sinks.knative.dev is forbidden: User "system:serviceaccount:knative-eventing:kafka-controller" cannot list resource "jobsinks" in API group "sinks.knative.dev" at the cluster scope
```
I have also created a test for KafkaBroker forwarding events to JobSink to verify the fix. But it's probably not necessary to include it. Anyway, it's available here: https://github.com/mgencur/eventing-kafka-broker/commit/57dbb533751c825762d94ca51b10d66e1d8a5439
Fixes #
- …

Allow kafka-controller to list JobSinks

---

data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/auth/OIDCDiscoveryConfigListener.java

- using `ConcurrentHashMap`, `AtomicRef` and `AtomicInt` for improving thread safeness
```release-note
```
**Docs**

Thread safe improvements on OIDCDiscoveryConfigListener

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/ConsumerVerticle.java

Completing the stop promise before the dependencies (dispatcher, client, etc) before will cause the WebClient to be closed.
Fixes #
- Complete Consumer verticle stop promise only after closing dependencies
-
-
```release-note
Complete Consumer verticle stop promise only after closing dependencies
```
**Docs**

Complete Consumer verticle stop promise only after closing dependencies

---

control-plane/pkg/apis/internalskafkaeventing/v1alpha1/consumer_group_types.go
control-plane/pkg/client/clientset/versioned/typed/internalskafkaeventing/v1alpha1/consumergroup.go
control-plane/pkg/client/clientset/versioned/typed/internalskafkaeventing/v1alpha1/fake/fake_consumergroup.go

Similar to https://github.com/knative-extensions/eventing-kafka-broker/pull/3976 but for the consumergroup client. This is useful since we currently do not expose the scale subresource for the triggers, so this will enable scaling the consumergroups directly
- Add UpdateScale method to consumergroup generated client
```release-note
the consumergroup client now supports UpdateScale methods
```

feat: add updatescale method to generated clients for consumergroups

---

.github/workflows/build-dependabot-pr.yaml

Fixes 
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
``` 
e.g in https://github.com/knative-extensions/eventing-kafka-broker/actions/runs/12588648354/job/35086964011

Update upload-artifact action to v4

---

data-plane/THIRD-PARTY.txt
data-plane/pom.xml
data-plane/profiler/run.sh

Update logback and logstash dependencies

---

data-plane/dispatcher-loom/pom.xml
data-plane/receiver-loom/pom.xml

Fixes #
- as per title
-
-
```release-note
```
**Docs**

Use rhel/ubi9-openjdk21 runtime image for data plane containers

---

test/upload-test-images.sh

Fixes #
- Fix test image upload
This is on pair with Eventing core repository script. We are now exporting KO_FLAGS from knative.dev/hack. However, the default is `KO_FLAGS=-P --platform=all`. The `-P` option is a culprit in this case of building test images, because it preservers import path. Therefore we see image pull errors in release job. Because of the fact that expected image URLs are different, affected by `KO_FLAGS`.
```
➜  eventing-kafka-broker git:(pr/fix-test-images) ko resolve --tags latest -RBf vendor/knative.dev/eventing/test/test_images/recordevents
2025/01/23 22:44:39 Using base gcr.io/distroless/static:nonroot@sha256:6ec5aa99dc335666e79dc64e4a6c8b89c33a543a1967f20d360922a80dd21f02 for knative.dev/eventing/test/test_images/recordevents
2025/01/23 22:44:41 Building …
```

Fix test image upload

---

test/upload-test-images.sh

Fixes #
- Fix test image upload
This is a cherry-pick of #4228

[release-1.17] Fix test image upload

---

.github/workflows/update-dependabot-pr.yaml

Running ./hack/update-codegen.sh on dependabot PRs currently fails (see for example https://github.com/knative-extensions/eventing-kafka-broker/pull/4280/files and https://github.com/knative-extensions/eventing-kafka-broker/actions/runs/13684783409).
This PR addresses it and simplifies running ./hack/update-codegen.sh on dependabot PRs

Run `./hack/update-codegen.sh` on dependabot PRs

---

.github/workflows/knative-java-test.yaml

As per title
Java Unit tests fail currently on setup-java step (e.g. in https://github.com/knative-extensions/eventing-kafka-broker/actions/runs/14518216315/job/40732376258?pr=4336)

Update setup-java GH action to v4

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleBuilder.java

Fixes #4357
- Adding a bit of defense coding here, since the consumer is set during the `build()` method, I have changed the initializer to  complete the `Promise` after `build()` has fully finished. Trying to avoid a potential race when the `start()` might use the consumer it was set.
```release-note
```
**Docs**

Change initializer to catch issues with setting consumer during build() function

---

control-plane/pkg/reconciler/trigger/v2/triggerv2.go

As per title, just to be consistent and propose this information in the triggers status too as we do for other resources.

:broom: Propagate the CaCerts and Audience of the ConsumerGroups Subscribers and DLS in the Triggers status too

---

control-plane/config/eventing-kafka-broker/200-controller/200-controller-cluster-role.yaml

This reverts commit 1616ec39684f890992aa53fedd91b63464d019ef.
The `jobsinks` rbac are already in the aggregated role for addressable, hence here is not really needed

Revert "Allow kafka-controller to list JobSinks (#4155)"

---

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java

Fixes #4460
- :bug: Fix OffsetManager partitionRevokedHandler, synchronously commit available offsets from the revoked partitions
The ConsumerRebalanceListener::onPartitionsRevoked is invoked from within the `poll` invocation, and it is expected the last commit calls before the partition is revoked should be done within that invocation, so these cannot be async using the Consumer task queue. 
This fix seems to resolve the offset commits within the partitionRevokedHandler. 
We might also consider refactoring of the PartitionRevokedHandler to not return a Future, as they are now all synchronous.

[data-plane] fix OffsetManager partitionRevokedHandler offset commit

---

test/keda-reconciler-tests.sh
test/rekt/features/keda_scaling.go

Currently the `TriggerSSLScalesToZeroWithKeda` and `TriggerSASLScalesToZeroWithKeda` tests try to install the broker two times. This PR cleans it up and installs it only once.
Also enables to run all tests containing "Keda" in their name from the e2e_new folder as part of the keda-rekt-test suite

Fix Keda Trigger SSL & SASL test to install broker only once

---

data-plane/config/source/100-config-kafka-source-data-plane.yaml
data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/CloudEventOverridesMutator.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetSkippingCloudEvent.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java
test/e2e_source/helpers/kafka_helper.go
test/e2e_source/helpers/kafka_source.go
test/pkg/kafka/verify_committed_offset.go
test/test_images/committed-offset/admin.go

Fixes #4451
- introduce OffsetSkippingCloudEvent to represent a "skipped offset"
- make RecordDispatcher discard OffsetSkippingCloudEvents
- add a kafka_source test variant with transactional id to verify KafkaSource behavior with a topic in which events are produced with Kafka transactions.
```release-note
Fixes a KafkaSource issue, where the kafka-source-dispatcher would stop committing offsets if the events were produced by a producer using Kafka transactions. 
```
**Docs**

treat offsets skipped due to kafka transactions as comitted

---

data-plane/config/broker/500-dispatcher.yaml
data-plane/config/channel/500-dispatcher.yaml
data-plane/config/source/500-dispatcher.yaml

Fixes #4545
- :bug: adding a volume placeholder in the statefulset for the contract-resources volume. The volumes will later be adjusted by the [pod defaulting webhook](https://github.com/knative-extensions/eventing-kafka-broker/blob/4f1d472577fc317aa35b6d8170a422468c14bfc6/control-plane/pkg/apis/core/pod_defaulting.go#L45)
```release-note
Add placeholder for contract-resources volume to make k8s validation webhook happy
```

Add volume template to kafka-*-dispatcher statefulsets for contract-resources volume 
