OWNERS
=> Added myself as owner and pierDipi as reviewer

DEVELOPMENT.md
- Document protobuf code generation
related: https://github.com/knative-sandbox/eventing-kafka-broker/issues/7#issuecomment-649966210
=> Document protobuf code generation

DEVELOPMENT.md
Signed-off-by: Alfusainey Jallow <alf.jallow@gmail.com>
- The developer guide now specifies the versions of the required software for this project. To allow the guide to be in sync with the versions used in the project, we include a link to the sources where the versions are defined.
=> Requirements versions in developer guide

DEVELOPMENT.md, test/kafka/kafka_setup.sh
Fixes #26 
Fixes #12 
- Add documentation to install everything needed from a clean K8s cluster.
- Wait for Strimzi to register resources on installation.
=> Update docs to include installation from scratch

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/broker_test.go, data-plane/README.md, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/CloudEventRequestToRecordMapper.java
Fixes #32 
- Use `knative-broker-` as topic prefix
=> Use `knative-broker-` as topic prefix

control-plane/pkg/reconciler/base/reconciler.go, control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/broker_lifecycle.go, control-plane/pkg/reconciler/broker/broker_test.go
Part of #33, #37 
- Update receiver pods annotation to refresh mounted config map
=> Update receiver pods annotation to refresh mounted config map

control-plane/cmd/kafka-broker-controller/main.go, control-plane/pkg/log/logger.go, control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/broker_test.go, control-plane/pkg/reconciler/testing/objects.go, control-plane/pkg/reconciler/trigger/controller.go, control-plane/pkg/reconciler/trigger/controller_test.go, control-plane/pkg/reconciler/trigger/trigger.go, control-plane/pkg/reconciler/trigger/trigger_lifecycle.go, control-plane/pkg/reconciler/trigger/trigger_test.go
=> Add Trigger reconciler

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/cloudevents/PartitionKey.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/cloudevents/PartitionKeyTest.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandler.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandlerTest.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/CloudEventRequestToRecordMapper.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/integration/ReceiverVerticleTest.java
Fixes #49 
- Add partition key value as Producer record key
=> Add partition key value as Producer record key

control-plane/pkg/reconciler/trigger/trigger.go, control-plane/pkg/reconciler/trigger/trigger_test.go
Fixes #51 
- Add Trigger finalizer
=> Add Trigger finalizer

data-plane/config/100-config-logging.yaml, data-plane/config/template/500-dispatcher.yaml, data-plane/config/template/500-receiver.yaml, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/ObjectsCreator.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/BrokersManager.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandler.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/UnorderedConsumerRecordOffsetStrategy.java, data-plane/pom.xml, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestHandler.java
- Add JSON Structured Logging to data plane components
=> Add JSON Structured Logging to data plane components

control-plane/pkg/reconciler/broker/controller.go, hack/tools.go
Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -path './third_party' -prune -o -name '*.pb.go' -prune -o -type f -name '*.go' -print)`
`goimports -w $(find -name '*.go' | grep -v vendor | grep -v third_party | grep -v .pb.go | grep -v wire_gen.go)`
=> [master] golang format tools

control-plane/pkg/reconciler/base/reconciler.go, control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/broker_lifecycle.go, control-plane/pkg/reconciler/broker/broker_test.go, control-plane/pkg/reconciler/trigger/trigger.go, control-plane/pkg/reconciler/trigger/trigger_lifecycle.go, control-plane/pkg/reconciler/trigger/trigger_test.go, data-plane/config/100-config-kafka-broker-dispatcher.yaml, data-plane/config/100-config-kafka-broker-receiver.yaml, data-plane/config/template/500-dispatcher.yaml, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/BrokerWrapper.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/BrokerWrapperTest.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/TriggerWrapperTest.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandler.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/UnorderedConsumerRecordOffsetStrategy.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerRecordSender.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/BrokersManagerTest.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/UnorderedConsumerRecordOffsetStrategyTest.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/CloudEventRequestToRecordMapper.java, go.mod, test/e2e-tests.sh, test/e2e/conformance/data_plane_conformance_test.go, vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
- Add data plane consumer conformance tests
- Fix bugs control plane conflicting updates and Broker equality
- Remove `reconciledNormal` 
fixes #55
=> Add data plane consumer conformance tests

.gitignore, control-plane/config/100-kafka-broker-configmap.yaml, control-plane/config/200-controller-cluster-role.yaml, control-plane/config/201-controller-cluster-role-binding.yaml, control-plane/config/500-controller.yaml, data-plane/config/100-config-brokers-triggers.yaml, data-plane/config/100-config-kafka-broker-dispatcher.yaml, data-plane/config/100-config-kafka-broker-receiver.yaml, data-plane/config/100-config-logging.yaml, data-plane/config/template/500-dispatcher.yaml, data-plane/config/template/500-receiver.yaml, hack/release.sh, test/control-plane/library.sh, test/data-plane/library.sh, test/e2e-common.sh, test/presubmit-tests.sh
Fixes #54 
- Add release automation
- Add copyright header to all YAML files.
- Simulate a release during the test
=> Add release automation

control-plane/pkg/reconciler/trigger/trigger.go, control-plane/pkg/reconciler/trigger/trigger_test.go, test/e2e/conformance/control_plane_conformance_test.go
- Add control plane conformance test
=> Add control plane conformance test

control-plane/config/500-controller.yaml
Related: knative/pkg#1269
- Add pod anti-affinity to control plane deployment
=> Add anti-affinity to control plane deployment

hack/release.sh
- Fix import path in `./hack/release.sh`
- Refactor `build_release` function
=> Fix import path

go.mod, go.sum, hack/update-deps.sh, vendor/knative.dev/test-infra/scripts/e2e-tests.sh, vendor/knative.dev/test-infra/scripts/library.sh, vendor/modules.txt
- Pin and knative/test-infra to release-0.17.
- In preparation for release-0.17 of knative/eventing in a week.
=> Pin pkg and test-infra to release-0.17 branch

hack/tools.go, test/e2e-common.sh, test/e2e-tests.sh, test/pkg/config/chaos/chaosduck.yaml, vendor/knative.dev/pkg/kflag/doc.go, vendor/knative.dev/pkg/kflag/set.go, vendor/knative.dev/pkg/leaderelection/chaosduck/main.go, vendor/modules.txt
Related https://github.com/knative/eventing/pull/3565
- Run the chaosduck component during our e2e testing
=> Run the chaosduck component during our e2e testing

go.mod, go.sum, hack/update-deps.sh, vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go, vendor/modules.txt
- Pin `knative/eventing` to release-0.17.
```release-note
NONE
```
=> Pin knative/eventing to release-0.17

data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/EventMatcherTest.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/BrokersManager.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandler.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordOffsetStrategyFactory.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/SinkResponseHandler.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerRecordSender.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandler.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/BrokersManagerTest.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandlerTest.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticleTest.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandlerTest.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/ConsumerVerticleFactoryMock.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategyTest.java, data-plane/pom.xml, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/CloudEventRequestToRecordMapper.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/HttpVerticle.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/integration/ProbeHandlerTest.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/integration/ReceiverVerticleTest.java, data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Fixes #136
- Update to cloudevents sdk-java 2.0.0-milestone2
- Update to Vert.x 4
```release-note
Update to Vert.x 4.0.Beta1
Update to cloudevents/sdk-java 2.0.0-milestone2
```
=> Port to Vert.x 4 and sdk-java 2.0.0-milestone2

data-plane/README.md
Produced via:
`prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github | grep -v docs/cmd/)`
=> [master] Format markdown

.golangci.yaml, control-plane/pkg/reconciler/broker/broker_test.go
As per title. Prep work for https://github.com/knative-sandbox/.github/pull/13 to land in sandbox.
=> Add linting config and fix issues.

test/e2e/conformance/data_plane_conformance_test.go
Similar to https://github.com/knative-sandbox/eventing-kafka-broker/pull/143 we're copy-pasting conformance tests which aren't usable for non-channel
based brokers.
- Enable TestBrokerConsumer
=> Enable TestBrokerConsumer

.github/workflows/knative-go-build.yaml
Copied from `https://github.com/knative-sandbox/.github/tree/master/workflow-templates`.
=> [master] Update GitHub Actions

go.mod, test/e2e/broker_trigger_sink_test.go, test/e2e/kafka_sink_test.go, test/pkg/addressable/send.go, vendor/modules.txt
Fixes #164 
```
+---------+     +--------+     +---------+   +---------------------------+
|  Broker +---->+ Trigger+---->+KafkaSink+-->+kafka consumer (test image)|
+----+----+     +--------+     +----+----+   +---------------------------+
|                              ^
|          +--------+          |
+--------->+ Trigger+----------+
+--------+
```
- Add E2E test using Broker, Trigger, and KafkaSink
=> Add E2E test using Broker, Trigger, and KafkaSink

.codecov.yaml, .github/workflows/knative-test.yaml
=> Checking if the fancy codecov works with java too

go.mod, go.sum, vendor/knative.dev/test-infra/scripts/library.sh, vendor/modules.txt
./hack/update-deps.sh --upgrade
=> Auto-update dependencies

.github/workflows/knative-boilerplate.yaml, .github/workflows/knative-donotsubmit.yaml, .github/workflows/knative-go-test.yaml, .github/workflows/knative-style.yaml, .github/workflows/knative-verify.yaml
Produced via:
```shell
cp $(find "${GITHUB_WORKSPACE}/meta/workflow-templates" -type f -name '*.yaml') \
"${GITHUB_WORKSPACE}/main/.github/workflows/"
```
=> [Automated] Update actions

go.mod, go.sum, hack/update-deps.sh, vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go, vendor/knative.dev/pkg/hack/update-deps.sh, vendor/knative.dev/pkg/kmeta/names.go, vendor/knative.dev/pkg/metrics/config.go, vendor/knative.dev/pkg/metrics/exporter.go, vendor/knative.dev/pkg/metrics/opencensus_exporter.go, vendor/knative.dev/pkg/webhook/conversion.go, vendor/knative.dev/pkg/webhook/webhook.go, vendor/modules.txt
Pin upstreams for release 0.18
=> [Release] Pin upstreams for release 0.18

go.mod, go.sum, vendor/knative.dev/eventing/pkg/apis/duck/v1/fuzzer.go, vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types_conversion.go, vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/subscribable_types_conversion.go, vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_validation.go, vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/container_validation.go, vendor/knative.dev/eventing/pkg/tracing/setup.go, vendor/knative.dev/eventing/test/lib/duck/resource_checks.go, vendor/modules.txt
Produced via:
```shell
./hack/update-deps.sh --upgrade
./hack/update-codegen.sh
```
=> [Automated] Upgrade to latest dependencies

.golangci.yaml, control-plane/cmd/webhook-kafka/main.go, control-plane/pkg/apis/eventing/v1alpha1/kafka_sink_validation.go, control-plane/pkg/apis/eventing/v1alpha1/register.go, control-plane/pkg/core/config/utils.go, control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/kafka/broker_class.go, control-plane/pkg/reconciler/testing/objects_broker.go, control-plane/pkg/reconciler/trigger/trigger.go, test/pkg/testing/run.go
- Enable linters and fix linting errors
=> Enable linters and fix linting errors

.codecov.yaml
- Ignore some directories in coverage calculation
=> Ignore some directories in coverage calculation

control-plane/config/sink/500-webhook.yaml
=> [release-0.18] add delay in liveness for webhook (#269)

data-plane/docker/Dockerfile
https://stackoverflow.com/questions/51023312/docker-having-issues-installing-apt-utils/56569081#56569081
=> Fix docker build

go.mod, go.sum, vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_lifecycle.go, vendor/knative.dev/eventing/pkg/apis/sources/v1/container_conversion.go, vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_conversion.go, vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/container_conversion.go, vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go, vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go, vendor/knative.dev/eventing/test/lib/recordevents/observer/observer.go, vendor/knative.dev/eventing/test/lib/recordevents/observer/reply.go, vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/constructor.go, vendor/knative.dev/eventing/test/lib/recordevents/resources.go, vendor/knative.dev/eventing/test/test_images/recordevents/main.go, vendor/knative.dev/pkg/injection/sharedmain/main.go, vendor/modules.txt
Produced via:
```shell
./hack/update-deps.sh --upgrade
./hack/update-codegen.sh
```
=> [master] Upgrade to latest dependencies

test/test_images/kafka-consumer/consumer.go
If the job fails, it's hard to diagnose what went wrong, this
PR adds some more logging to help diagnose errors.
- Improve error messages in the `kafka-consumer` test image
=> Improve error messages in kafka-consumer test image 

README.md
- Add links and badges to the readme
=> Add links and badges to the readme

hack/release-notes.sh
This PR adds a `release-notes.sh` script to generate release notes
and documents how to use it.
- Add release notes generator script
```release-note
🎁 Add new feature
- release leads or contributors can generate release notes using the `./hack/release-notes.sh` script.
```
=> Add release notes generator script

data-plane/config/100-config-kafka-broker-data-plane.yaml, data-plane/config/sink/100-config-kafka-sink-data-plane.yaml, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandler.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandler.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandlerTest.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java, go.sum, test/pkg/config/100-config-logging.yaml
Fixes https://knative.slack.com/archives/C017X0PFC0P/p1603202378101200
- Backport fixes found during continuous testing in https://github.com/knative-sandbox/eventing-kafka-broker/pull/249
=> [0.18] Backport fixes found during continuous testing in #249

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployer.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticleFactory.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployerTest.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
Fixes #331
- ConsumerVerticleFactory doesn't return future anymore
=> ConsumerVerticleFactory doesn't return future anymore

data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/integration/ReceiverVerticleTest.java
=> Fix flaky test

data-plane/docker/test/Dockerfile, test/data-plane/library.sh
- Export data plane tests reports
=> Export data plane tests reports

test/kafka/kafka-ephemeral-single.yaml
=> Test against Kafka 2.6

control-plane/config/100-kafka-broker-configmap.yaml, test/e2e/broker_trigger_test.go
Signed-off-by: sheetalsingala <ssingala@redhat.com>
Fixes #374 
-
-
-
```release-note
```
**Docs**
=> Change default replication factor

.github/pull-request-template.md
- Sync PR template from Eventing
=> Sync PR template from Eventing

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Configurations.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/utils/ConfigurationsTest.java, data-plane/core/src/test/resources/configurations.properties
Fixes #381
- Add tests for Configurations.java
=> Add tests for Configurations.java

.github/workflows/knative-profile-data-plane.yaml, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/TracingSpan.java, data-plane/pom.xml, data-plane/profiler/resources/config-kafka-broker-consumer.properties, data-plane/profiler/resources/config-kafka-broker-httpserver.properties, data-plane/profiler/resources/config-kafka-broker-producer.properties, data-plane/profiler/resources/config-kafka-broker-webclient.properties, data-plane/profiler/resources/config-logging.xml, data-plane/profiler/resources/config-sacura-warmup.yaml, data-plane/profiler/resources/config-sacura.yaml, data-plane/profiler/resources/ingress.json, data-plane/profiler/run.sh
This PR adds a GitHub Action to profile our data plane, and upload
the resulting artifacts so that reviewer can inspect results, and
take actions accordingly.
- Add data plane profiling action
=> Add data plane profiling action

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/OpenTelemetryTracer.java
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>
Fixes #466
- Replace HttpTraceContext with W3CTraceContextPropagator
```release-note
```
**Docs**
=> Replace HttpTraceContext with W3CTraceContextPropagator

data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
We need to wait for all events to be consumed and produced.
=> Fix flaky consumer test

test/config/100-config-logging.yaml, test/e2e-common.sh, test/e2e-tests.sh, test/e2e/sacura_test.go
=> Debug flaky tests

test/kafka/strimzi-cluster-operator.yaml
=> Bump Strimzi to 0.21.1

control-plane/config/sink/100-kafka-sink.yaml
KafkaSink CRD has some copy-pasted description from the Broker CRD.
- Improve status fields description in KafkaSink CRD
```release-note
Improve status fields description in KafkaSink CRD.
```
=> Improve status fields description in KafkaSink CRD

.github/workflows/knative-java-test.yaml, .github/workflows/knative-profile-data-plane.yaml, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/file/FileWatcherTest.java, data-plane/pom.xml, hack/data-plane.sh
Java 14 isn't supported anymore.
- Bump Java from 14 to 15
=> Bump Java from 14 to 15

test/e2e-tests.sh, test/e2e/sacura_test.go
Part of #596
- Execute sacura job in parallel
=> Execute sacura job in parallel

hack/data-plane.sh
We're building the receiver image twice.
Part of #596
- Avoid building receiver twice
=> Avoid building receiver twice

.github/workflows/kind-e2e.yaml
=> Reduce sleep time in GH actions test setup

control-plane/pkg/reconciler/trigger/trigger.go, data-plane/config/100-config-kafka-broker-data-plane.yaml, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticle.java
Part of https://github.com/knative-sandbox/eventing-kafka-broker/issues/556
- Consume topic from the earliest offset
```release-note
:bug: Consume topic from the earliest offset
```
=> Consume topic from the earliest offset

OWNERS
As per title, move my name in OWNERS up.
=> I'm not a TOC member

data-plane/THIRD-PARTY.txt, data-plane/benchmarks/pom.xml, data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/benchmarks/UnorderedOffsetManagerBenchmark.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManager.java, data-plane/docker/Dockerfile, data-plane/pom.xml
- Added a benchmark package and a benchmark for `UnorderdOffsetManager`
=> OffsetManager Benchmark

go.mod, go.sum, vendor/github.com/pierdipi/sacura/cmd/sacura/main.go, vendor/github.com/pierdipi/sacura/state.go, vendor/modules.txt
Part of https://github.com/knative-sandbox/eventing-kafka-broker/issues/556
-
-
-
```release-note
```
**Docs**
/cc pierDipi
=> Debug sacura job

OWNERS
I'd like to start getting more code awareness and assigned some PRs to review.
=> Adding devguyio to reviewers

README.md
- Add KafkaSink docs link to the readme
=> Add KafkaSink docs link to the readme

control-plane/pkg/reconciler/trigger/trigger.go
The reconcileKind method of the Trigger reconciler was below
other minor methods, this PR moves it above, no logic changed.
- Move reconcileKind method of Trigger reconciler
/kind cleanup
=> Move reconcileKind method of Trigger reconciler

.github/CODEOWNERS
Like https://github.com/knative-sandbox/control-protocol/pull/7
=> Fixed codeowners file

.github/workflows/kind-e2e.yaml, test/e2e-common.sh, third_party/eventing-v0.18.6/eventing-core.yaml, third_party/eventing-v0.18.6/eventing-crds.yaml, third_party/eventing-v0.19.4/eventing-core.yaml, third_party/eventing-v0.19.4/eventing-crds.yaml, third_party/eventing-v0.20.1/eventing-core.yaml, third_party/eventing-v0.20.1/eventing-crds.yaml
This PR starts running E2E tests using previous versions of Eventing.
- Add tests for previous versions of eventing
=> Add tests for previous versions of Eventing

go.mod, go.sum, vendor/github.com/pierdipi/sacura/state.go, vendor/modules.txt
- Upgrade sacura to include output improvements
=> Upgrade sacura to include output improvements

data-plane/profiler/run.sh
The profiler was failing due to missing env var and the profiler release has been deleted.
- Fix profiler test runner
=> Fix profiler test runner

go.mod
Bump Go version to 1.15 like Eventing and Serving.
=> Bump Go version to 1.15

.github/workflows/kind-e2e.yaml
We are running out of quota in the Knative sandbox organization, for that reason, this PR reduces periodic job frequency.
- Kind periodic actions every 6 hours
/area test
=> Kind periodic actions every 6 hours

test/pkg/addressable/send.go
There was a data race during a test run:
- https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-sandbox-eventing-kafka-broker-continuous/1370721276309540864
It happens when we call FailNow on `t` in multiple goroutines, since it's
not thread-safe.
The whole suit would have failed anyway but it creates a cascading
failure with an unknown (literally) reason since `gotestsum` gets 
confused when there are unstructured logs.
- Send each event in a sub-test.
=> Fix data race - failed to send events during tests

third_party/eventing-latest/eventing-core.yaml, third_party/eventing-latest/eventing-crds.yaml
As per the title, update eventing nightly artifacts manually since
we don't have yet an automation for this.
- Update Eventing nightly
=> Update Eventing nightly

test/e2e_new/multiple_partition_config/install.go, test/e2e_new/multiple_partition_config/multiple_partition_config.yaml, test/e2e_new/ordered_test.go
Always part of #589. This PR adds an additional test that checks ordering is respected per partition
=> Add another test that checks ordering per keys

data-plane/core/src/test/resources/logback.xml, data-plane/dispatcher/src/test/resources/logback.xml, data-plane/receiver/src/test/resources/logback.xml, data-plane/tests/src/test/resources/logback.xml
Fixes #839
- Added logback test configs
=> Logback test config

control-plane/pkg/security/config.go, data-plane/THIRD-PARTY.txt, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidator.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentials.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidatorTest.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentialsTest.java
Backport #855 and #840
- Allow SASL Mechanism to be equal to "PLAIN"
```release-note
Support SASL mechanism PLAIN.
```
/kind bug
=> [release-0.22] Backport SASL/PLAIN fixes

.github/workflows/build-dependabot-pr.yaml
Fixes #874
I copy pasted too much :)
=> Dependabot PR workflow fix

.github/workflows/build-dependabot-pr.yaml, .github/workflows/update-dependabot-pr.yaml
Complaining about dependabot PRs
=> Fix the Google CLA bot

go.sum
=> Now verify codegen GH action should be happy

control-plane/pkg/reconciler/trigger/controller.go, test/e2e-tests.sh, test/e2e_new/trigger_finalizer_test.go
Skip TestTriggerNoFinalizerOnBrokerNotFound test since it's flaky
=> Skip TestTriggerNoFinalizerOnBrokerNotFound test

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/AuthProvider.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/Credentials.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidator.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KafkaClientsAuth.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesAuthProvider.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentials.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/PlaintextCredentials.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidatorTest.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KafkaClientsAuthTest.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KubernetesAuthProviderTest.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentialsTest.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/testing/CloudEventSerializerMock.java, data-plane/pom.xml, test/e2e_new/trigger_finalizer_test.go
=> Update license plugin

.github/workflows/kind-e2e.yaml, third_party/eventing-v0.21.4/eventing-core.yaml, third_party/eventing-v0.21.4/eventing-crds.yaml, third_party/eventing-v0.22.1/eventing-core.yaml, third_party/eventing-v0.22.1/eventing-crds.yaml, third_party/eventing-v0.23.0/eventing-core.yaml, third_party/eventing-v0.23.0/eventing-crds.yaml
Use for testing:
- Eventing 0.21.4
- Eventing 0.22.1
- Eventing 0.23.0
=> Bump third party files

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcher.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
Another followup of #900
- :broom: Some comments on how tracing works for the kafka consumer side
=> More comments about how tracing works for the consumer

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/TracingConfig.java
=> Removed bad log line

data-plane/README.md
Fixes #
-
-
-
```release-note
```
**Docs**
=> Fix the path to the contract file

data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
The `TODO` made we think a bit, and I added how I was using the `shutdown` a few years ago in some other vertx based project.
We could also move the `kafka shutdown` section _after_ the `undeploy` from vertx
=> Reorganize the shutdown code a bit

.github/workflows/kind-e2e.yaml, hack/tools.go, vendor/knative.dev/eventing/test/test_images/event-library/main.go, vendor/modules.txt
Fixes #872
- Now GH Actions run e2e_new test suite
=> Add e2e_new to gh actions

hack/data-plane.sh
Fixes #
`uuid --hdr` doesn't work on MacOs 🕶️ 
- Added an if/else to run command with different param on MacOS
-
-
```release-note
```
**Docs**
=> Fix build on MacOS

test/e2e_new/tracing_test.go
Hopefully fixes #983
- :bug: Reduced event wait period an number of events for `TracingHeaders` test
=> Faster tracing headers test

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactoryTest.java
- :broom: Cleanup receiver `Main`, added some comments
- :broom: Moved counter creation to `ReceiverVerticleFactory`
=> Better receiver Main code

test/e2e_new/resources/kafkasink/kafkasink.go, test/e2e_new/resources/kafkasink/kafkasink.yaml, test/e2e_new/resources/kafkasink/kafkasink_test.go
Part of #1077
- :gift: Add KafkaSink test resource
=> KafkaSink test resource

test/e2e-tests.sh, test/e2e/delete_cm_test.go, test/e2e_new/broker_delete_config_map_test.go, test/e2e_new/main_test.go, test/e2e_new/resources/configmap/delete.go, test/e2e_new/resources/configmap/log.go, test/e2e_new/resources/configmap/wait.go
Part of #1077
- :broom: Ported broker delete contract CM test to e2e_new
=> Port Broker Delete CM test to e2e_new

control-plane/pkg/apis/messaging/v1beta1/kafka_channel_lifecycle.go, control-plane/pkg/apis/messaging/v1beta1/kafka_channel_lifecycle_test.go
Fixes #
- Implement lifecycle for KafkaChannel
- Mostly taken from distributed ch impl
-
```release-note
```
**Docs**
=> Channel lifecycle

control-plane/pkg/core/config/utils_test.go, control-plane/pkg/reconciler/broker/broker_test.go, control-plane/pkg/reconciler/broker/controller.go, control-plane/pkg/reconciler/trigger/controller.go, control-plane/pkg/reconciler/trigger/trigger_test.go, test/pkg/observability/watch_config_map.go
- :broom: Update or clean up current behavior
/kind cleanup
```release-note
```
**Docs**
=> Use `controller.Impl` tracker and cleanups

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/channel/channel.go, control-plane/pkg/reconciler/sink/kafka_sink.go, control-plane/pkg/reconciler/trigger/trigger.go
we have already sink and some channel POC
Fixes #
- simple renaming
-
-
```release-note
```
**Docs**
=> Lets use a generic kafkalogging, rather than broker

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/sink/kafka_sink.go, control-plane/pkg/security/config.go, control-plane/pkg/security/config_test.go
Fixes #
- Divide `NewOptionFromSecret` into 2 functions that return a single value, from a single function that returns 2 values
- Improve code readability
-
```release-note
```
**Docs**
=> Separate security config function

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/channel/channel.go, control-plane/pkg/reconciler/sink/kafka_sink.go, control-plane/pkg/security/config.go, control-plane/pkg/security/config_test.go
Fixes #
- Use the secret in config-kafka when doing operations on Kafka cluster
-
```release-note
```
**Docs**
=> Channel control plane to use secret

control-plane/pkg/reconciler/channel/channel.go, control-plane/pkg/reconciler/channel/controller.go
Fixes #
- Track config-kafka and the secret
- There will be other stuff to track, but later
-
```release-note
```
**Docs**
=> Channel reconciler to track configmap and secret

control-plane/pkg/reconciler/channel/channel.go
Fixes #
- Channel to use spec details for topic creation
```release-note
```
**Docs**
=> Channel to use spec details for topic creation

control-plane/pkg/reconciler/channel/channel.go
Fixes #
- Handle channel deletion
-
```release-note
```
**Docs**
=> Handle channel deletion

control-plane/pkg/reconciler/channel/channel.go
Fixes #
- Use retention from spec for topic creation
-
```release-note
```
**Docs**
=> Use retention from spec for topic creation

third_party/eventing-kafka-latest/channel-crds.yaml
Fixes #
- Do the same thing as https://github.com/knative-sandbox/eventing-kafka/pull/857
-
```release-note
```
**Docs**
=> Make Channel status.address optional

control-plane/pkg/reconciler/sink/auth_provider.go, control-plane/pkg/security/config.go, control-plane/pkg/security/config_test.go
Fixes #
- Improve test coverage for security.config/TestSecret
-
```release-note
```
**Docs**
=> Improve test coverage for security.config/TestSecret

control-plane/cmd/webhook-kafka/main.go, control-plane/pkg/reconciler/channel/channel.go, control-plane/pkg/reconciler/channel/controller.go
Fixes #
- Inline config.Env in channel reconciler
- Add a TODO about Channel webhook
-
```release-note
```
**Docs**
=> Inline config.Env in channel reconciler

control-plane/pkg/reconciler/channel/controller.go
Fixes #
- Register event listeners in KafkaChannel controller
- Register custom condition set
-
```release-note
```
**Docs**
=> Register event listeners in KafkaChannel controller and register custom condition set

control-plane/pkg/reconciler/base/receiver_condition_set.go, control-plane/pkg/reconciler/broker/broker_test.go, control-plane/pkg/reconciler/broker/controller.go, control-plane/pkg/reconciler/channel/controller.go, control-plane/pkg/reconciler/sink/controller.go, control-plane/pkg/reconciler/sink/kafka_sink_test.go, control-plane/pkg/reconciler/trigger/trigger_test.go
Fixes https://github.com/knative-sandbox/eventing-kafka-broker/pull/1295#discussion_r726077268
- Rename condition set for ingress resources
- Check if `SetAddress` function is set
=> Rename condition set for ingress resources and check if `SetAddress` function is set

data-plane/.mvn/wrapper/maven-wrapper.properties
Fixes #
-
-
-
```release-note
```
**Docs**
=> Bump maven version to the latest release

control-plane/pkg/reconciler/broker/broker.go
Fixes #
- little func rename
-
-
```release-note
```
**Docs**
=> Little rename of func

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/broker_test.go, control-plane/pkg/reconciler/broker/controller.go, control-plane/pkg/reconciler/channel/channel.go, control-plane/pkg/reconciler/channel/controller.go, control-plane/pkg/reconciler/kafka/client.go, control-plane/pkg/reconciler/kafka/topic_test.go, control-plane/pkg/reconciler/sink/controller.go, control-plane/pkg/reconciler/sink/kafka_sink.go, control-plane/pkg/reconciler/sink/kafka_sink_test.go, control-plane/pkg/reconciler/source/controller.go, control-plane/pkg/reconciler/source/source.go, control-plane/pkg/reconciler/source/source_test.go
Fixes #
- as per title
-
```release-note
```
**Docs**
=> Let's use NewKafkaClusterAdminClient as the name to avoid confusion

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/BaseConsumerVerticle.java
The exception handler may be null.
Part of #312
- Check verticle exception handler presence
```release-note
None
```
**Docs**
```
None
```
=> Check verticle exception handler presence

hack/run.sh, test/e2e-common.sh
Fixes #
- have a cleaner separation and moved Strimzi install to separate func.
-
-
```release-note
```
**Docs**
=> Separate step for just launching Kafka cluster (Strimzi)

control-plane/pkg/reconciler/broker/broker_test.go, control-plane/pkg/reconciler/sink/kafka_sink_test.go, control-plane/pkg/reconciler/source/source_test.go, control-plane/pkg/reconciler/testing/factory.go, control-plane/pkg/reconciler/trigger/trigger_test.go
Fixes #
- Separate `DefaultEnv` variables in testing, otherwise it is getting confusing
-
-
```release-note
```
**Docs**
=> Separate default envs in testing

test/kafka/kafka_setup.sh
Fixes #
- as per title
-
-
```release-note
```
**Docs**
=> Replace deprecated dry-run usage arg

control-plane/config/100-source/100-kafka-source.yaml, third_party/eventing-kafka-latest/source-crd.yaml
Fixes #
- as per title
-
-
```release-note
```
**Docs**
=> Adding just the source CRD

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/AsyncCloseable.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherListener.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/BaseConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/AbstractOffsetManagerTest.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/1463
```release-note
Commit offset on consumer close.
```
**Docs**
```
None
```
=> [release-0.26] Commit offset on consumer close (#1463)

control-plane/pkg/reconciler/base/reconciler.go, control-plane/pkg/reconciler/channel/channel_test.go, control-plane/pkg/reconciler/testing/objects_broker.go, control-plane/pkg/reconciler/testing/objects_channel.go, control-plane/pkg/reconciler/testing/objects_common.go
Fixes #
- Going to have all Kafka channel reconciler tests in this PR
- I will do the tests with auth later, once we decide on what to do about the configmap
- Let's keep the TODOs
```release-note
```
**Docs**
=> Kafka channel reconciler tests - except auth cases

.github/workflows/kind-e2e.yaml
Fixes #
-
- as per title
-
```release-note
```
**Docs**
=> Using k8s 1.22.2 version

.github/workflows/knative-java-test.yaml
=> Use Java 17 for GH actions

control-plane/pkg/reconciler/channel/channel.go, control-plane/pkg/reconciler/channel/channel_test.go, control-plane/pkg/reconciler/channel/testdata/ca.crt, control-plane/pkg/reconciler/channel/testdata/user.crt, control-plane/pkg/reconciler/channel/testdata/user.key
Fixes #
- Kafka Ch reconciler tests with auth
-
-
```release-note
```
**Docs**
=> Kafka Ch reconciler tests with auth

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java
As reported in the spec:
https://github.com/knative/specs/blob/c348f501de9eb998b4fd010c54d9127033ee41be/specs/eventing/data-plane.md#event-acknowledgement-and-delivery-retry
Similar to `SelectiveRetry` function in eventing.
- Handle non-retryable HTTP status codes
```release-note
Handle non-retryable HTTP status codes as reported in the spec: 
For more information: https://github.com/knative/specs/blob/c348f501de9eb998b4fd010c54d9127033ee41be/specs/eventing/data-plane.md#event-acknowledgement-and-delivery-retry
```
**Docs**
```
None
```
=> Handle non-retryable HTTP status codes as reported in the spec

test/pkg/broker/broker.go, test/pkg/testing/run.go, third_party/VENDOR-LICENSE/github.com/nxadm/tail/ratelimiter/Licence
Backport of https://github.com/knative-sandbox/eventing-kafka-broker/pull/1591
-
-
-
```release-note
```
**Docs**
=> [release-0.26] Use Broker's own configmap for Kafka

control-plane/cmd/kafka-controller/main.go
Fixes #
- using name main, to be able to disable controllers, based on toggle/choice
```release-note
```
**Docs**
=> using sharedmain.MainNamed for all controllers

control-plane/pkg/reconciler/broker/controller.go, control-plane/pkg/reconciler/trigger/controller.go
Chrry-pick of: https://github.com/knative-sandbox/eventing-kafka-broker/pull/1616
=> Add promote filter function to Broker and Trigger reconciler (#1616)

control-plane/pkg/reconciler/broker/controller.go, control-plane/pkg/reconciler/trigger/controller.go
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/1616
=> [release-0.26] Add promote filter function to Broker and Trigger reconciler

test/e2e-tests.sh
Fixes #
- Store log artifacts for all pods
-
-
```release-note
```
**Docs**
=> Store log artifacts for all pods

test/e2e/channel_single_event_test.go
Fixes #
- Enable basic e2e tests for KafkaChannel
```release-note
```
**Docs**
=> Enable basic e2e tests for KafkaChannel

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
For data plane deployments, we need to be able to secure prometheus
endpoints by using TLS certificates.
Now, the receiver and the dispatcher accept the following env
variables:
- `METRICS_PEM_CERT_PATH`: TLS cert path
- `METRICS_PEM_KEY_PATH`: TLS key path
- `METRICS_HOST`: metrics server host
- Support TLS for the metrics server
```release-note
Support TLS for the metrics server.
Now, the receiver and the dispatcher accept the following env
variables:
- `METRICS_PEM_CERT_PATH`: TLS cert path
- `METRICS_PEM_KEY_PATH`: TLS key path
- `METRICS_HOST`: metrics server host
```
=> Support TLS for the metrics server

DEVELOPMENT.md
Follow-up for https://github.com/knative-sandbox/eventing-kafka-broker/pull/1704#discussion_r782167854
=> Add build-from-source docs for development

test/config/default-ch-webhook.yaml
Fixes #
-
-
-
```release-note
```
**Docs**
=> Make KafkaChannel the default for testing

hack/release.sh
=> Fix bash script import for hack/release.sh

third_party/eventing-kafka-latest/channel-crds.yaml
Get the changes from this one in: https://github.com/knative-sandbox/eventing-kafka/pull/1057
=> Define status.deadLetterSinkUri in KafkaChannel CRD

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
I believe this class needed more comments for easier code
reading.
=> Add more comments to OffsetTracker

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types.go, control-plane/pkg/reconciler/consumergroup/evictor.go, control-plane/pkg/reconciler/consumergroup/evictor_test.go
Part of #1537
- Add Scheduler evictor for ConsumerGroup
=> Add Scheduler evictor for ConsumerGroup

.github/workflows/kind-e2e.yaml, test/reconciler-tests.sh
Fixes #
- Same as https://github.com/knative-sandbox/eventing-kafka-broker/pull/1825 but for 1.2 branch
- 
-
```release-note
:gift: KafkaChannel becomes conformant with spec. Conformance tests are now run with every code change.
```
**Docs**
=> [Release 1.2] Run channel Rekt tests

data-plane/config/sourcev2/500-dispatcher.yaml
As per title.
- Copy `kafka-source-dispatcher` deployment
- Make it a StatefulSet
=> Add KafkaSource dispatcher StatefulSet manifest

control-plane/pkg/reconciler/consumer/controller.go, control-plane/pkg/reconciler/consumer/controller_test.go
Part of #1537
- Adding new Consumer controller
```release-note
```
**Docs**
=> Adding Consumer Controller for for ConsumerGroup scaling

control-plane/pkg/reconciler/base/receiver_condition_set.go, control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/broker_test.go, control-plane/pkg/reconciler/channel/channel.go
Fixes #1810 
- Show error in status when resolving sink fails
```release-note
Show error in Broker and Channel status when resolving sink fails
```
**Docs**
/kind enhancement
=> Show error in Broker and Channel status when resolving sink fails

test/upgrade/postupgrade.go, test/upgrade/preupgrade.go
Test names for KafkaSink were wrong.
=> Fix KafkaSink upgrade test names

control-plane/config/200-controller/100-config-kafka-descheduler.yaml, control-plane/config/200-controller/100-config-kafka-scheduler.yaml
- Use the same configurations used in eventing-kafka
Part of #1537
=> Add scheduler and de-scheduler configuration

control-plane/pkg/reconciler/consumer/consumer.go
=> Use constant in consumer reconciler to get pod's CM name

control-plane/config/200-controller/200-controller-cluster-role.yaml
=> Add permissions to controller for scheduling resources

control-plane/pkg/reconciler/base/reconciler.go
=> Check if ConfigMap.BinaryData is nil in base reconciler

control-plane/pkg/reconciler/consumer/consumer.go
Check if the pod is running after trying to get or create the
associated ConfigMap, since it won't become ready until we have
created the ConfigMap.
Part of #1537
=> Consumer: check if pod is running after creating ConfigMap

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types.go, control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types_test.go, control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_types.go, control-plane/pkg/reconciler/consumergroup/consumergroup.go, control-plane/pkg/reconciler/consumergroup/consumergroup_test.go, control-plane/pkg/reconciler/testing/objects_consumer.go, control-plane/pkg/reconciler/testing/objects_consumergroup.go
Propagate subscriberURI, deadLetterSinkURI,
and ready replica count.
Part of #1537
=> Propagate Consumers status to ConsumerGroup 

control-plane/pkg/reconciler/consumergroup/consumergroup.go, control-plane/pkg/reconciler/consumergroup/consumergroup_test.go, control-plane/pkg/reconciler/source/v2/sourcev2.go, control-plane/pkg/reconciler/source/v2/sourcev2_test.go, control-plane/pkg/reconciler/testing/objects_common.go, control-plane/pkg/reconciler/testing/objects_consumergroup.go, control-plane/pkg/reconciler/testing/objects_source.go
We weren't handling the ConsumerGroup spec update properly.
Part of #1537
- Handle ConsumerGroup spec update
=> Handle ConsumerGroup spec update

data-plane/profiler/run.sh
- Upgrade async-profiler to 2.6
=> Upgrade async-profiler to 2.6

go.mod, go.sum, vendor/knative.dev/eventing-kafka/test/e2e-tests.sh, vendor/knative.dev/pkg/injection/sharedmain/main.go, vendor/modules.txt
Fixes #1893
- apply https://github.com/knative/pkg/pull/2415 
-
-
```release-note
```
**Docs**
=> [release-1.2] Bring PKG fix 2415 in manually

control-plane/pkg/reconciler/consumer/consumer.go, control-plane/pkg/reconciler/consumer/consumer_test.go, control-plane/pkg/reconciler/testing/objects_common.go, control-plane/pkg/reconciler/testing/objects_consumer.go, control-plane/pkg/reconciler/testing/objects_consumergroup.go, control-plane/pkg/reconciler/testing/objects_source.go
Part of #1537 
- Add Consumer reconciler tests
TODO:
- finalizer tests
- more reconciler tests
=> Add Consumer reconciler tests

data-plane/config/brokerv2/500-dispatcher.yaml, data-plane/config/channelv2/500-dispatcher.yaml
=> New statefulset dispatcher yamls for trigger and channel

test/e2e-common.sh
=> Adding KafkaSource to test teardown script

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types.go, control-plane/pkg/reconciler/channel/v2/channelv2.go, control-plane/pkg/reconciler/channel/v2/controllerv2.go
=> Consumer Scheduling and Scaling KafkaChannel fixes

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
- Add `event_type` label to dispatcher metrics
=> Add event_type label to dispatcher metrics

control-plane/pkg/reconciler/channel/testdata/testdata, control-plane/pkg/reconciler/channel/v2/channelv2.go, control-plane/pkg/reconciler/channel/v2/channelv2_test.go, control-plane/pkg/reconciler/channel/v2/testdata, control-plane/pkg/reconciler/testing/objects_channel.go, control-plane/pkg/reconciler/testing/objects_consumer.go, control-plane/pkg/reconciler/testing/objects_consumergroup.go
Part of #1537 
Dependent on #1618's implementation
- Adding new KafkaChannel reconciler tests
```release-note
```
**Docs**
=> Consumer scheduling scaling KafkaChannel tests

control-plane/config/post-install/200-storage-version-migrator-cluster-role.yaml, control-plane/config/post-install/200-storage-version-migrator-service-account.yaml, control-plane/config/post-install/500-storage-version-migrator.yaml
Fixes #
- as per title
-
-
```release-note
adding Storage-Version-Migrator for KafkaSource and KafkaChannel
```
**Docs**
=> Storage-Version-Migrator for KafkaSource and KafkaChannel

control-plane/pkg/reconciler/channel/testdata/testdata
Cleaning up some test artifact from #1828
=> Remove Symlink (GH action fix)

go.mod, go.sum, vendor/knative.dev/eventing/pkg/scheduler/statefulset/autoscaler.go, vendor/knative.dev/eventing/test/e2e-rekt-tests.sh, vendor/modules.txt
- Upgrades knative eventing go mod
=> Upgrade knative eventing go mod

control-plane/pkg/reconciler/broker/broker.go
Fixes #
- moving the code for creating the actual topic to a `reconcileBrokerTopic` func
- moving the clean up code to a `finalizeBrokerTopic`
-
```release-note
```
**Docs**
=> Prefactoring for topic reconciling

control-plane/pkg/reconciler/source/v2/sourcev2.go, control-plane/pkg/reconciler/source/v2/sourcev2_test.go
=> Extract func to propagate consumer group status in KafkaSource

control-plane/pkg/reconciler/channel/channel_test.go, control-plane/pkg/reconciler/channel/v2/channelv2.go, control-plane/pkg/reconciler/channel/v2/channelv2_test.go, control-plane/pkg/reconciler/channel/v2/controllerv2.go, control-plane/pkg/reconciler/testing/objects_channel.go, control-plane/pkg/reconciler/testing/objects_common.go
As per title.
I found this issue while testing KafkaChannel with eventing core tests in https://github.com/knative-sandbox/eventing-kafka-broker/pull/2025
=> Set KafkaChannel dead letter sink URI in the status

control-plane/pkg/reconciler/channel/channel.go, control-plane/pkg/reconciler/channel/channel_test.go, control-plane/pkg/reconciler/testing/objects_channel.go
Fixes #
- Reconciler tests for channel deletion
-
-
```release-note
```
**Docs**
=> Reconciler tests for channel deletion

test/e2e-common.sh, test/upgrade/continual.go, test/upgrade/continual/channel-config.toml, test/upgrade/postdowngrade.go, test/upgrade/postupgrade.go, test/upgrade/preupgrade.go, test/upgrade/suite.go, vendor/knative.dev/eventing-kafka/test/upgrade/README.md, vendor/knative.dev/eventing-kafka/test/upgrade/continual.go, vendor/knative.dev/eventing-kafka/test/upgrade/installation/eventing_core.go, vendor/knative.dev/eventing-kafka/test/upgrade/installation/githead.go, vendor/knative.dev/eventing-kafka/test/upgrade/installation/shell.go, vendor/knative.dev/eventing-kafka/test/upgrade/installation/stable.go, vendor/knative.dev/eventing-kafka/test/upgrade/postdowngrade.go, vendor/knative.dev/eventing-kafka/test/upgrade/postupgrade.go, vendor/knative.dev/eventing-kafka/test/upgrade/preupgrade.go, vendor/knative.dev/eventing-kafka/test/upgrade/smoke.go, vendor/knative.dev/eventing-kafka/test/upgrade/suite.go, vendor/knative.dev/eventing-kafka/test/upgrade/test_main.go, vendor/knative.dev/eventing/test/lib/duck/resource_checks.go, vendor/modules.txt
- Upgrade tests for KafkaChannel
-
-
```release-note
```
**Docs**
=> KafkaChannel upgrade tests

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
`max.poll.interval.ms` is used to bound the processing time at
the consumer level, however, we have application-level timeouts
that are dinamically controlled.
In this patch, I'm performing the maximum processing time (
see how in `maxProcessingTimeMs` method) and set
`max.poll.interval.ms` to that value.
- Dynamically set `max.poll.interval.ms` based on the delivery spec
```release-note
Dynamically set `max.poll.interval.ms` based on the delivery spec
```
=> Dynamically set `max.poll.interval.ms` based on the delivery spec

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
Fixes #
- manually doing the cherry-pick of 2058 (Dynamically set max.poll.interval.ms based on the delivery spec)
```release-note
Dynamically set `max.poll.interval.ms` based on the delivery spec
```
**Docs**
=> [release-v1.2] Dynamically set max.poll.interval.ms based on the delivery spec (#2058)

control-plane/pkg/reconciler/source/v2/controllerv2.go, control-plane/pkg/reconciler/source/v2/controllerv2_test.go
=> Remove unused source controller configs

control-plane/pkg/reconciler/trigger/trigger_test.go
=> Fix copylocks lint error in tests

control-plane/cmd/kafka-controller/main.go, control-plane/pkg/reconciler/channel/channel_test.go, control-plane/pkg/reconciler/channel/controller.go, control-plane/pkg/reconciler/channel/controller_test.go
Fixes #
- Fix some TODOs
- Remove outdated TODOs
-
```release-note
```
**Docs**
=> Fix or remove some TODOs

test/upgrade/continual/channel-config.toml, test/upgrade/continual/kafka-broker-config.toml, test/upgrade/continual/kafka-sink-source-config.toml
* This is required for the wathola components to properly report tracing
information to Zipkin.
This is similar to what was already done in knative-sandbox/eventing-kafka in the toml files, e.g. https://github.com/knative-sandbox/eventing-kafka/blob/main/test/upgrade/continual/channel-config.toml
```release-note
```
**Docs**
=> Configure tracing in wathola toml files

control-plane/pkg/reconciler/consumergroup/consumergroup.go
=> Check error when creating Sarama options

data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/AsyncCloseableTest.java
=> Add unit test for AsyncCloseable's compose utility

control-plane/pkg/reconciler/source/v2/sourcev2_test.go, control-plane/pkg/security/secret.go, control-plane/pkg/security/secret_test.go, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidator.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KafkaClientsAuth.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentials.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidatorTest.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KafkaClientsAuthTest.java
Fixes #2117
- Use PLAIN as default SASL if not specified
=> Use PLAIN as default SASL if not specified

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java
Fixes https://github.com/knative/specs/issues/96
- adding `408` to the list of retries
```release-note
```
**Docs**
=> adding 408 - Request Timeout to list of retryable status codes

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
We need to handle the case when the offset tracker was removed from
our Map since when partitions are revoked we remove the associated
offset tracker, however, we may get a response from the sink for a
previously owned partition after a partition has been revoked.
Note: it's not possible to commit offsets of partitions that a
particular consumer instance doesn't own.
I can't find a way to test this.
Fixes #2176
=> Handle committing offsets on revoked partitions

control-plane/cmd/kafka-controller/main.go, control-plane/pkg/reconciler/channel/channel_test.go, control-plane/pkg/reconciler/channel/controller.go, control-plane/pkg/reconciler/channel/controller_test.go
Backporting https://github.com/knative-sandbox/eventing-kafka-broker/pull/2052 manually
=> [1.3] Fix or remove some TODOs

go.mod, go.sum, vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_helper.go, vendor/knative.dev/eventing-kafka/test/upload-test-images.sh, vendor/modules.txt
Fixes #
- getting latest of recent eventing-kafka goodies
-
-
```release-note
```
**Docs**
=> Adding latest eventing-kafka dep

control-plane/pkg/reconciler/channel/channel.go, control-plane/pkg/reconciler/channel/channel_test.go, control-plane/pkg/reconciler/testing/objects_common.go, control-plane/pkg/security/secrets_provider_legacy_channel_secret.go, test/e2e-common.sh, test/kafka/kafka_setup.sh
Fixes #2213
-
-
-
```release-note
```
**Docs**
=> Support legacy KafkaChannel secret format

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/BaseConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/PartitionRevokedHandler.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
Fixes #2202
- Commit offsets on partition revoked
```release-note
```
**Docs**
=> Commit offsets on partition revoked

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/OrderedAsyncExecutor.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/BaseConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/PartitionRevokedHandler.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2221
=> [release-1.4] Commit offsets on partition revoked (#2221)

README.md, docs/channel/README.md
Fixes #
Documented these
- The differences in the new KafkaChannel implementation
- Breaking changes
- Auto migration from the consolidated channel
- Configuring the dataplane
- Discontinued features
```release-note
```
**Docs**
=> Docs for new KafkaChannel

data-plane/config/broker/100-config-kafka-broker-data-plane.yaml, data-plane/config/channel/100-config-kafka-channel-data-plane.yaml, data-plane/config/sink/100-config-kafka-sink-data-plane.yaml, data-plane/config/source/100-config-kafka-source-data-plane.yaml, hack/update-checksums.sh
Address some questions in #2227 
Part of #2227
=> Document global data plane configurations

control-plane/config/eventing-kafka-broker/200-controller/200-controller-cluster-role.yaml, control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/broker_test.go, control-plane/pkg/reconciler/testing/objects_broker.go
Fixes #2211
- add finalizer to secret
```release-note
```
**Docs**
=> Adding finalizer for auth secret

test/e2e_new/dls_test.go
- Adding simple rekt-test for Dead letter sink and retries
```release-note
```
**Docs**
=> Adding simple test for Dead letter sink and retries

go.mod, go.sum, vendor/knative.dev/eventing-kafka/pkg/common/kafka/offset/offsets.go, vendor/modules.txt
```
./hack/update-deps.sh --upgrade --release 1.6
```
=> [release-1.6] Manually upgrade dependencies

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/BaseEnv.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/utils/BaseEnvTest.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverEnvTest.java
=> Allow enabling data plane server and client metrics

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
By adding the pause/resume lifecycle, we avoid polling events
from partitions that would need to be kept in-memory since
the per-partition queue isn't empty.
=> Add pause/resume lifecyecle to ordered consumer

.github/workflows/kind-e2e.yaml, test/e2e-tests.sh, test/e2e/conformance/data_plane_conformance_test.go, test/e2e_broker/broker_redelivery_test.go, test/e2e_broker/broker_sasl_ssl_test.go, test/e2e_broker/broker_trigger_sink_test.go, test/e2e_broker/broker_trigger_test.go, test/e2e_broker/conformance/control_plane_conformance_test.go, test/pkg/broker/broker.go, test/upgrade-tests.sh
Fixes #
- Pass broker class to e2e tests
- For now, only `Kafka` broker class and not the namespaced broker class
-
```release-note
```
**Docs**
=> Pass broker class to e2e tests

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
=> Add TODO for max pool size override

test/e2e_new/broker_conformance_test.go, test/e2e_new/broker_delete_config_map_test.go, test/e2e_new/broker_not_ready_test.go, test/e2e_new/dls_test.go, test/e2e_new/main_test.go, test/e2e_new/ordered_test.go, test/e2e_new/tracing_test.go, test/reconciler-tests.sh
Fixes #
- Pass broker class to reconciler tests
-
-
```release-note
```
**Docs**
=> Pass broker class to reconciler tests

data-plane/profiler/run.sh
As per title, flamegraphs can be downloaded from
https://github.com/knative-sandbox/eventing-kafka-broker/actions/runs/2753216718
=> Fix profiler job

test/config/100-config-experimental-features.yaml, test/experimental/delivery_timeout_test.go, test/experimental/features_config/features.yaml, test/experimental/main_test.go, vendor/knative.dev/eventing/test/experimental/features/delivery_timeout/channel.go, vendor/modules.txt
=> Test delivery timeout

test/upgrade/continual/channel-config.toml, test/upgrade/continual/kafka-broker-config.toml, test/upgrade/continual/kafka-sink-source-config.toml
Fixes #2427
- Set teardown delay to 10 seconds
=> Fix upgrade test flakiness

test/e2e-common.sh
Signed-off-by: Dirk Haubenreisser <haubenr@de.ibm.com>
Fixes #2512
=> Honor prow job environment variable for chaosduck enablement

go.mod, go.sum, test/e2e/sacura_test.go, test/e2e_new/main_test.go, test/e2e_new/tracing_test.go, test/e2e_new_channel/main_test.go, test/e2e_new_channel/tracing_test.go, test/pkg/tracing/tracing.go, test/pkg/tracing/zipkin.go, third_party/VENDOR-LICENSE/go.opentelemetry.io/otel/LICENSE, third_party/VENDOR-LICENSE/go.opentelemetry.io/otel/trace/LICENSE, vendor/knative.dev/eventing/test/rekt/resources/svc/service.go, vendor/knative.dev/eventing/test/rekt/resources/svc/service.yaml, vendor/modules.txt
Backport of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2369
```release-note
```
**Docs**
=> [release-1.6] Tracing tests for Kafka Broker

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java
Backport of #2521 to 1.6 branch
=> [release-1.6] Better handle error response

.github/workflows/kind-e2e.yaml, control-plane/cmd/kafka-controller/main.go, test/e2e-tests.sh, test/reconciler-tests.sh
Fixes #
- Disable namespaced KafkaBroker
-
-
```release-note
```
**Docs**
=> Disable namespaced KafkaBroker

test/e2e-tests.sh, test/reconciler-tests.sh
=> Lets see if that makes PROW release job happy

test/e2e-tests.sh, test/reconciler-tests.sh
=> [main] Lets see if that makes PROW release job happy

control-plane/pkg/reconciler/broker/broker.go
- removing a TODO that's not really "fixable"
```release-note
```
**Docs**
=> nit: Remove a todo, there is no reasonable constant

go.mod, go.sum, test/e2e_new/features/featuressteps/broker.go, test/e2e_new/tracing_test.go, test/e2e_new_channel/tracing_test.go, vendor/knative.dev/reconciler-test/pkg/eventshub/eventshub.go, vendor/knative.dev/reconciler-test/pkg/eventshub/utils.go, vendor/modules.txt
- Removes deprecated calls to AddTracing
- Removes workaround in tracing tests for improper tracer shutdown (this issue has been fixed)
```release-note
```
**Docs**
=> Tracing tests updates

control-plane/cmd/webhook-kafka/main.go, control-plane/pkg/apis/eventing/v1/broker_validation.go, control-plane/pkg/apis/eventing/v1/broker_validation_test.go
Fixes #
- Manual backport of proper webhook implementation from this PR: #2562
- As #2562 was done when namespaced broker is around, I had to comment out some parts.
- Created https://github.com/knative-sandbox/eventing-kafka-broker/issues/2630 to track that
```release-note
```
**Docs**
=> Manual backport of proper webhook implementation

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/namespaced_broker.go
=> Do not copy locks

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/controller.go, control-plane/pkg/reconciler/broker/namespaced_broker.go, test/e2e_new/broker_test.go, test/e2e_new/features/broker_deleted_recreated.go
Fixes #
-
-
-
```release-note
```
**Docs**
=> [release-v1.7] [issue/2569] Check for kafka/network errors on finalizeKind

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/controller.go, test/e2e_new/broker_test.go, test/e2e_new/features/broker_deleted_recreated.go
Manual backport of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2629  to 1.6 branch
=> [release-1.6] [issue/2569] Check for kafka/network errors on finalizeKind

control-plane/cmd/kafka-controller/main.go, control-plane/cmd/kafka-source-controller/main.go, control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-features.yaml, control-plane/pkg/apis/config/features.go, control-plane/pkg/apis/config/features_test.go, control-plane/pkg/apis/config/testdata/config-kafka-features.yaml, control-plane/pkg/reconciler/consumergroup/consumergroup.go, control-plane/pkg/reconciler/consumergroup/consumergroup_test.go, control-plane/pkg/reconciler/consumergroup/controller.go, control-plane/pkg/reconciler/consumergroup/controller_test.go, test/config/100-config-kafka-features.yaml
- Setup a feature flag for autoscaling consumers with KEDA
=> Create a feature flag for KEDA autoscaling of consumers

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
- as per title
```release-note
```
**Docs**
=> Nit: Remove checksum, since null and generally not used in this deprecated constructor

control-plane/cmd/post-install/kafka_source_dispatcher_deleter.go
This reduces downtime and latency during migration.
=> Wait for sts to exists before deleting dispatcher during migration

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java
It's not here that we check for retry-able status codes.
=> Fix misleading log message

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
We're setting it after a Consumer is created.
=> Set MAX_POLL_INTERVAL_MS_CONFIG before creating consumer

test/e2e_broker/broker_redelivery_test.go, test/e2e_broker/broker_trigger_test.go, test/e2e_broker/conformance/control_plane_conformance_test.go, test/pkg/broker/broker.go, test/upgrade-tests.sh, test/upgrade/continual.go, test/upgrade/continual/broker.go, test/upgrade/continual/types.go, test/upgrade/postdowngrade.go, test/upgrade/postupgrade.go, test/upgrade/preupgrade.go, test/upgrade/smoke.go, test/upgrade/suite.go
Fixes #
- Read broker class env var passed by Prow in upgrade tests
- We will later use this to run upgrade tests for namespaced broker
-
```release-note
```
**Docs**
=> Namespaced broker upgrade tests

control-plane/pkg/keda/keda.go, control-plane/pkg/reconciler/consumergroup/consumergroup.go, control-plane/pkg/reconciler/testing/objects_consumergroup.go
=> KEDA Trigger Authentication SASL updates for secret spec

control-plane/pkg/keda/keda.go, control-plane/pkg/reconciler/consumergroup/consumergroup.go, control-plane/pkg/security/secret.go
Signed-off-by: aavarghese [avarghese@us.ibm.com](mailto:avarghese@us.ibm.com)
=> KEDA Trigger Authentication TLS updates for secret spec

DEVELOPMENT.md
Adding a few more information about the local registry, when developing on kind.
```release-note
```
=> Add information about local registry in development docs

control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-features.yaml, control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml, control-plane/config/eventing-kafka-source/200-controller/500-controller.yaml
Breaking down https://github.com/knative-sandbox/eventing-kafka-broker/pull/2437 into smaller PRs.
=> Source env cleanup

control-plane/pkg/apis/core/pod_defaulting.go, control-plane/pkg/apis/internals/kafka/eventing/data_plane.go, control-plane/pkg/reconciler/base/reconciler.go, control-plane/pkg/reconciler/consumer/consumer.go, control-plane/pkg/reconciler/consumergroup/consumergroup.go, control-plane/pkg/reconciler/consumergroup/consumergroup_test.go, control-plane/pkg/reconciler/consumergroup/controller.go, control-plane/pkg/reconciler/consumergroup/controller_test.go, control-plane/pkg/reconciler/testing/objects_common.go
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2773
=> [release-1.8] Create contract ConfigMaps in ConsumerGroup reconciler (#2773)

test/config/sacura/resources/200-config.yaml
This adds a limit to duplicates for the sacura test of the Broker
=> Add maxDuplicatesPercentage for Broker sacura test

control-plane/pkg/reconciler/broker/broker_test.go, control-plane/pkg/reconciler/broker/namespaced_broker_test.go, control-plane/pkg/reconciler/testing/listers.go, control-plane/pkg/reconciler/testing/objects_broker.go, control-plane/pkg/reconciler/testing/objects_common.go, control-plane/pkg/reconciler/testing/objects_consumergroup.go, vendor/github.com/manifestival/manifestival/fake/client.go, vendor/modules.txt
Fixes #
- Missing unit tests for namespaced broker
- Didn't add all cases, as we're wrapping existing well-tested reconciler
-
```release-note
```
**Docs**
=> Missing unit tests for namespaced broker

test/e2e_new/ordered_test.go, test/e2e_new/tracing_test.go
=> WithAnnotation() is deprecated, replacing with 'WithAnnotations'

go.mod, go.sum, vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go, vendor/knative.dev/eventing/test/rekt/resources/broker/broker.yaml, vendor/modules.txt
Fixes #
- as per title
-
-
```release-note
```
**Docs**
=> Bumping to latest Knative Eventing

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/testing/objects_broker.go, go.mod, go.sum, test/upgrade/continual/broker.go, vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go, vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go, vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go, vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go, vendor/knative.dev/eventing/test/rekt/features/broker/data_plane.go, vendor/knative.dev/eventing/test/upgrade/prober/sut/broker.go, vendor/modules.txt
As per title and adjust for use of broker `AddressStatus` status field to be compatible with https://github.com/knative/eventing/pull/6622
=> Bumping to latest knative/eventing

test/rekt/features/broker_deleted_recreated.go
- creating topic for "external" broker
- 
```release-note
```
**Docs**
=> Creating an actual topic

test/e2e_new/broker_test.go, test/rekt/features/broker_deleted_recreated.go
- two more tests for non-existing external topic
=> Tests for broker broker non existing external topic

control-plane/pkg/prober/cache.go, control-plane/pkg/prober/prober.go, control-plane/pkg/reconciler/broker/broker.go, test/e2e_new/broker_test.go, test/e2e_new/features/namespace.go, test/e2e_new/features/namespaced_broker.go
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2896
=> [release-1.8] Fix delete namespace with a namespaced broker stuck on finalizer (#2896)

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/broker_test.go
…om status annotations
Fixes #
-
-
-
```release-note
```
**Docs**
=> Explicit error message for failures after rebuilding it from status annotations

control-plane/pkg/reconciler/broker/broker.go
Fixes #
-
-
-
```release-note
```
**Docs**
=> Make changes to brokerconfig func

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/broker_test.go
Fixes #
- changing the `topicConfig` implementation and passing in the "broker config" `ConfigMap`
```release-note
```
**Docs**
=> Refactoring the topic config, passing directly in the broker config map

control-plane/pkg/reconciler/broker/namespaced_broker.go
Fixes #
- Don't set ownerRefs on cluster scoped resources
-
-
```release-note
```
**Docs**
=> Don't set ownerRefs on cluster scoped resources

control-plane/pkg/reconciler/broker/broker.go
Fixes #
- debug log the secret for external and internal topics
```release-note
```
**Docs**
=> nit: debug log the secret for external and internal topics

test/kafka/kafka-ephemeral.yaml, test/kafka/strimzi-cluster-operator.yaml
- Update to Strimzi 0.32 and Kafkas 3.3.x
=> Update to Strimzi 0.32 and Kafkas 3.3.x

control-plane/pkg/reconciler/consumergroup/controller.go
Fixes #2926
- as per title
```release-note
```
**Docs**
=> Perform type assertion on conversion

test/kafka/kafka-ephemeral.yaml
Fixes #
- after strimzi bump, going with Kafkas 3.3.2
```release-note
```
**Docs**
=> Going w/ Apache Kafka 3.3.2

test/kafka/strimzi-cluster-operator.yaml
- sync to latest community release (https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.33.1)
```release-note
```
**Docs**
=> Using latest Strimzi 0.33.1

test/e2e_new/broker_with_many_triggers_test.go, test/reconciler-tests.sh
As per title and follow up on https://github.com/knative-sandbox/eventing-kafka-broker/pull/2990#issuecomment-1449593699
=> Add `TestBrokerWithManyTriggers` e2e test

test/e2e-common.sh, test/e2e_new/broker_event_transformation_test.go, test/e2e_new_channel/main_test.go, test/experimental/main_test.go
=> Migrate `TestEventTransformationForTriggerV1BrokerV1` broker e2e test to rekt test framework

test/kafka/kafka-ephemeral.yaml, test/kafka/strimzi-cluster-operator.yaml
- Bump to Strimzi 0.33.2 and using kafka 3.4
```release-note
```
**Docs**
=> Bump to Strimzi 0.34.0 and using kafka 3.4

test/e2e_new/main_test.go, test/rekt/features/broker_deleted_recreated.go, test/rekt/resources/configmap/broker/broker_config.go, test/rekt/resources/configmap/broker/broker_config.yaml
Same as https://github.com/knative-sandbox/eventing-kafka-broker/pull/3008 , only adapted for release-1.9 branch.
-
-
-
```release-note
```
**Docs**
=> [release-1.9] Conformance tests against MTChannelBasedBroker

test/kafka/strimzi-cluster-operator.yaml
Fixes #
-Bumping strimzi to latest operator version. No need for kafka operand itself, this time
```release-note
```
**Docs**
=> Bumping strimzi to latest operator version

control-plane/pkg/reconciler/source/source.go, control-plane/pkg/reconciler/source/source_test.go
- Cherry pick commit https://github.com/knative-sandbox/eventing-kafka-broker/commit/e45c5fec51f1e4af193afdede8efa10d780b0fae to version 1.10
=> Cherry pick sourcev2 upgrade fix to 1.10

data-plane/receiver-vertx/src/main/java/dev/knative/eventing/kafka/broker/receiververtx/VertxKafkaProducer.java, data-plane/receiver-vertx/src/main/java/dev/knative/eventing/kafka/broker/receiververtx/VertxProducerFactory.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/ReactiveKafkaProducer.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/ReactiveProducerFactory.java
Progress for #2928 
- Identified what Kafka Producer Functions are used in Base Reciever Module
- Implemented those Methods in receiver Vert.x Module
=> ReactiveKafkaProducer Interface and it's Vert.x Implementation

control-plane/pkg/reconciler/sink/kafka_sink_test.go
Fixes #3144 
- Remove the redundant import
- Update the variable name to follow lint rules
=> Remove redundant code

control-plane/config/eventing-kafka-broker/100-source/100-kafka-source.yaml
Fixes #3081 
- Added proper openAPIV3Schema for spec and status for KafkaSource 
```release-note
```
**Docs**
=> update crd for kafkasource

DEVELOPMENT.md
Fixes #3204
- Change mvn to `./mvnw`
=> Update the document to include the code formatter

test/kafka/kafka-ephemeral.yaml, test/kafka/strimzi-cluster-operator.yaml
- as per title
```release-note
```
**Docs**
=> Strimzi operator 0.36.0 and Kafka 3.5.0

control-plane/pkg/reconciler/broker/broker.go
As per title, we should never hard code namespaces
=> Don't use hardcoded namespace

hack/update-codegen.sh
As per title, we're getting unwanted updates on the update deps automation PRs
=> Fix update-codegen.sh for update-cert-manager.sh update

data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/ExactFilterBenchmark.java, data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/FilterBenchmark.java
Fixes #3233 
- Create an abstract class for the filter benchmarks
- Extend the abstract class to benchmark the default ExactFilter filter
=> Created abstract FilterBenchmark class

test/kafka/kafka-ephemeral.yaml, test/kafka/strimzi-cluster-operator.yaml
- as per title
```release-note
```
**Docs**
=> Applying fixes to bump to latest operator and operand

DEVELOPMENT.md, data-plane/README.md, docs/broker/Loom-Modules.md
- Added a Note in DEVELOPMENT.md to install loom impls.
- Update the data-plane/README.md according to current folder structure
- Added a new Docs Loom-Modules.md as installation guide.
Please let me know if I should add anything more. 
/cc @pierDipi @matzew @Cali0707 @Leo6Leo
=> Added Installation Docs for Loom Dispatcher and Receiver Implementations

go.mod, go.sum, test/e2e-tests.sh, test/presubmit-tests.sh, test/reconciler-tests.sh, test/upgrade-tests.sh, vendor/knative.dev/hack/e2e-tests.sh, vendor/knative.dev/hack/infra-library.sh, vendor/knative.dev/hack/performance-tests.sh, vendor/knative.dev/hack/presubmit-tests.sh, vendor/modules.txt
Part of https://github.com/knative/hack/pull/230
/cc @matzew
=> Deprecate calling kubetest2 via kntest

data-plane/config/broker-tls/broker-ingress-tls-certificate.yaml, data-plane/config/channel-tls/channel-ingress-tls-certificate.yaml, data-plane/config/sink-tls/sink-ingress-tls-certificate.yaml
- Add the kafka-broker-ingress.knative-eventing.svc as hostname
=> Add the kafka-XXX.knative-eventing.svc as hostname

README.md
Part of https://github.com/knative/community/issues/1403
- Add link to clotributor to README
=> Added clotributor link

control-plane/pkg/reconciler/base/reconciler.go, control-plane/pkg/reconciler/base/reconciler_test.go
Fixes #3334 
- Use the unmarshalling option to discard unknown fields in the json 
```release-note
The data plane contract now supports downgrades from versions with new fields
```
=> Ignore unknown fields in data plane contract

test/keda-reconciler-tests.sh, test/keda/enable-keda-autoscaling.yaml
Part of #3067 
- Add a config map to enable autoscaling in tests
- Add a script which enables autoscaling in tests then runs the KafkaSource tests
=> Added script to run KafkaSource tests with KEDA

test/kafka/strimzi-cluster-operator.yaml
- Strimzi 0.37 upstream operator bump
```release-note
```
**Docs**
=> chore: Bumping Strimzi to next

control-plane/pkg/reconciler/consumergroup/evictor.go
Sometimes the `evictor` sets the unschedulable annotation in the middle of the Statefulset sequence and that causes to have unschedulable pods running and doing nothing, since this is an optimization to avoid
consumers reshuffles but leads to wrong results, we're removing it.
=> Evictor will not set unschedulable annotation anymore

data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/AllFilterBenchmark.java, data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/AnyFilterBenchmark.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/subscriptionsapi/AllFilter.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/subscriptionsapi/AnyFilter.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleBuilder.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/subscriptionsapi/AllFilterTest.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/subscriptionsapi/AnyFilterTest.java
Fixes #3364 
- Switch from using Set to List for Any filter
- Switch from using Set to List for All filter
=> Refactor filters to use lists instead of sets

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_lifecycle.go, control-plane/pkg/reconciler/consumergroup/consumergroup.go, control-plane/pkg/reconciler/consumergroup/consumergroup_test.go, control-plane/pkg/reconciler/testing/objects_consumergroup.go
=> [release-1.11] Update ConsumerGroup status on finalization for better error reporting (#3415)

control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
As per title.
Seeing this issue e.g. in #3421 while it's not related to the PR.
=> Fix gofmt issue

test/e2e_new/new_trigger_filters_test.go
- Add a test for multiple sinks receiving from multiple triggers using the new filters
=> Add test for multiple sinks and multiple triggers

test/e2e_new/broker_sasl_ssl_test.go, test/rekt/features/broker_auth.go
Fixes #
- Adding broker test for SSL/NoAuth
```release-note
```
**Docs**
=> Adding test for SSL/NoAuth

control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-autoscaler.yaml, control-plane/pkg/autoscaler/autoscaler_api.go, control-plane/pkg/reconciler/consumergroup/consumergroup.go, control-plane/pkg/reconciler/testing/objects_consumergroup.go, test/e2e_new/kafka_source_test.go, test/rekt/features/kafka_source.go, test/rekt/features/kafkafeatureflags/kafkafeatureflags.go
Fixes #3067 
- Add a test which verifies KafkaSource scale from zero and scale to zero
- Reduce the cooldown period from 300 seconds to 30 seconds to align with serving defaults
=> Test Keda Kafka Source Scaling

data-plane/dispatcher-loom/pom.xml, data-plane/pom.xml, data-plane/receiver-loom/pom.xml, data-plane/tests/pom.xml
- remove the `15` setting, and go w/ `21`
```release-note
```
**Docs**
=> We go all in jdk-21

data-plane/core/pom.xml, data-plane/dispatcher/pom.xml, data-plane/pom.xml, data-plane/receiver/pom.xml
=> Add version tag for maven plugin(#3551)

data-plane/THIRD-PARTY.txt, data-plane/pom.xml
- as per title
```release-note
```
**Docs**
=> [release-1.12] Going to logback 1.4.14 

go.mod, go.sum
Use the latest Go version 1.21
=> Bump Go to v1.21

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/CloudEventMutator.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherMutatorChain.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/NullCloudEventInterceptor.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/Main.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/main/InterceptorChainTest.java, test/e2e_new/kafka_source_test.go, test/rekt/features/kafka_source.go
Manual cherry pick of #3475 with the build issues fixed
=> [release-1.12] Fix binary events with no data and ce overrides not being delivered (#3475)

control-plane/pkg/reconciler/trigger/namespaced_trigger_test.go, control-plane/pkg/reconciler/trigger/trigger.go, control-plane/pkg/reconciler/trigger/trigger_test.go
=> set the template consumer group id first in trigger

test/e2e-common.sh
=> [release-1.13] Include TLS resources in release test setup

test/config-transport-encryption/features.yaml, test/experimental/features_config/features.yaml
Fixes #
- Based on eventing upstream PR #6608, removing the feature-flag from this test cfg
```release-note
```
**Docs**
=> Remove strict-subscriber feature flag

test/experimental/features_config/features.yaml
- adding missing features to have a "complete" feature list, to easily switch _all_ existing features
```release-note
```
**Docs**
=> Align to the defaults, list all - for convenience

test/config-transport-encryption/features.yaml
Fixes #
- as per title, and suggested in #3642 
```release-note
```
**Docs**
=> Order features.yaml like the actual upstream file/src

control-plane/config/eventing-kafka-broker/100-channel/100-kafka-channel.yaml, control-plane/config/eventing-kafka-broker/100-source/100-kafka-source.yaml, control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types.go, control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_types.go, control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/zz_generated.deepcopy.go, control-plane/pkg/apis/sources/v1beta1/kafka_lifecycle.go, control-plane/pkg/core/config/utils.go, control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/channel/channel.go, control-plane/pkg/reconciler/channel/v2/channelv2.go, control-plane/pkg/reconciler/consumer/consumer.go, control-plane/pkg/reconciler/consumergroup/consumergroup.go, control-plane/pkg/reconciler/sink/kafka_sink.go, control-plane/pkg/reconciler/source/source.go, control-plane/pkg/reconciler/source/source_test.go, control-plane/pkg/reconciler/testing/objects_consumer.go, control-plane/pkg/reconciler/trigger/trigger.go, control-plane/pkg/reconciler/trigger/trigger_test.go, control-plane/pkg/reconciler/trigger/v2/triggerv2.go
Fixes #3572 (follow up on #3571)
- Update contract with OIDC information. This includes:
- Audience of the Destination
- Audience of the Reply
- Audience of the Dead-Letter-Sink
- OIDCServiceAccountName
- Audience of the ingress
```release-note
none
```
=> Provision contract with OIDC information

control-plane/pkg/reconciler/broker/broker.go
- :broom: Remove unneeded check when setting broker audience
=> Remove unneeded check when setting broker audience

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/kafka/ProducerTracer.java, data-plane/dispatcher-loom/src/main/java/dev/knative/eventing/kafka/broker/dispatcherloom/LoomKafkaConsumer.java, data-plane/receiver-loom/src/main/java/dev/knative/eventing/kafka/broker/receiverloom/LoomKafkaProducer.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java, hack/data-plane.sh
=> Migrate to use Loom modules by default

data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/features/FeaturesConfigTest.java
As per title and as follow up for #3761 
/cc @Cali0707
=> Add unit test for FeaturesConfig class

test/e2e/main_test.go, test/e2e_channel/main_test.go, test/e2e_new_channel/main_test.go, test/e2e_sink/main_test.go, test/e2e_source/main_test.go
Fixes #3753 
Added the use of new logging package in e2e,e2e_source,e2e_sink,e2e_new_channel,e2e_channel main files and also removed the previous log exporter testlib wherever used in these files
:sparkles:  Used new log package
=> used new logging package in all e2e test main functions

test/keda-reconciler-tests.sh
Fixes #3711 
added a script in keda-reconciler-tests.sh that will run sacura tests in it
:gift: Added sacura tests in keda job
=> added sacura tests to keda test job

control-plane/pkg/reconciler/consumergroup/consumergroup.go
=> Add debug logs for ConsumerGroup reconciler to record actions taken

data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStore.java
=> Use ConcurrentHashMap in IngressProducerReconcilableStore to avoid ConcurrentModificationException

data-plane/pom.xml
- Remove the unused vertx-kafka version property
```release-note
```
**Docs**
=> Remove the unused vertx-kafka version property

hack/run.sh, test/e2e-common.sh
Fixes #3552
-
-
-
```release-note
```
**Docs**
=> Add deploy control plane command to hack/run.sh

control-plane/pkg/apis/sources/v1beta1/kafka_types.go, control-plane/pkg/client/clientset/versioned/typed/sources/v1beta1/fake/fake_kafkasource.go, control-plane/pkg/client/clientset/versioned/typed/sources/v1beta1/kafkasource.go
Fixes #3975 
- Add the generate methods for UpdateScale and ApplyScale to the api type
Note: for some reason
```release-note
:gift: The KafkaSource client now supports the UpdateScale method
```
=> feat: added UpdateScale method to KafkaSource client

test/kafka/kafka-ephemeral.yaml, test/kafka/strimzi-cluster-operator.yaml
Fixes #
- new versions coming in
```release-note
```
**Docs**
=> Bump to Strimzi 0.42.0 operator and Kafka operand to 3.7.1

test/kafka/kafka-ephemeral.yaml, test/kafka/strimzi-cluster-operator.yaml
=> Bump to Strimzi 0.43.0 operator and Kafka operand to 3.8

data-plane/pom.xml
=> Update maven-dependency-plugin to 3.8

control-plane/config/eventing-kafka-source/200-controller/100-config-kafka-descheduler.yaml, control-plane/config/eventing-kafka-source/200-controller/100-config-kafka-scheduler.yaml
=> Remove broken symlinks

test/kafka/kafka-ephemeral.yaml, test/kafka/strimzi-cluster-operator.yaml
Fixes #
- As per title.Note: we also recently bumped to kafka 3.9 client library, therefore putting the server to same makes sense
```release-note
```
**Docs**
=> Bump to Strimzi 0.45.0 operator and Kafka operand to 3.9

data-plane/THIRD-PARTY.txt, data-plane/pom.xml
Fixes #
- bump loggers (`logback` and `slf4j-api`). Replaces https://github.com/knative-extensions/eventing-kafka-broker/pull/4275 and https://github.com/knative-extensions/eventing-kafka-broker/pull/4276
```release-note
```
**Docs**
=> Bump logging bundle in one batch, to latest

control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml, control-plane/pkg/reconciler/consumergroup/controller.go, control-plane/pkg/reconciler/consumergroup/controller_test.go
This configuration helps with configuring HA for
dispatchers.
The Eventing scheduler tries to place virtual replicas on multiple
pods, by having `DISPATCHERS_MIN_REPLICAS` be more than 1, even when
the total number of virtual replicas is less than
POD_CAPACITY, the virtual replicas for resources will spread out
across replicas leading to overall better availability for _all_
resources.
Fixes #
- Allow configuring dispatchers min replicas
```release-note
Allow configuring dispatchers minimum replicas.
This configuration helps with configuring HA for dispatchers.
The Eventing scheduler tries to place virtual replicas on multiple pods, by having `DISPATCHERS_MIN_REPLICAS` be more than 1, even when the total number of virtual replicas is less than `POD_CAPACITY`, the virtual …
```
=> Allow configuring dispatchers min replicas

.github/workflows/knative-profile-data-plane.yaml, data-plane/profiler/run.sh
Fixes #
- Update profiling gh action
Bump versions in too old to run actions. Let's see if it's failing or not anymore.
/cc @matzew @pierDipi
=> Update profiling gh action

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/KReference.java
Fixes #4307
- the ET does have a Kreference.address (see: https://github.com/knative/pkg/commit/4835a4cb0c244b814c482a7227f09719de0fd106)
```release-note
```
**Docs**
=> Event Type in v1b3 has updated KRef with address

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
We have seen a `java.lang.IndexOutOfBoundsException: bitIndex < 0: -1`
=> Skip commit when records offset < initial offset

data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
Fixes #4359
- :bug: Initialize HTTPS server correctly when TLS config gets updated
=> Setup and initialize HTTPS server correctly when TLS config gets updated

test/e2e_new/broker_test.go, test/e2e_new/kafka_source_test.go
- Follow up from https://github.com/knative-extensions/eventing-kafka-broker/pull/4253, enabling the newly added test
```release-note
```
**Docs**
=> Enable new test for SASL keda

control-plane/config/eventing-kafka-source/200-controller/100-config-tracing.yaml
Fixes #
- Cleanup invalid symlink
Follow-up of original CM removal in https://github.com/knative-extensions/eventing-kafka-broker/pull/4373
/cc @gauron99
=> Cleanup invalid symlink

data-plane/dispatcher-loom/src/test/java/dev/knative/eventing/kafka/broker/dispatcherloom/LoomConsumerFactoryTest.java
- fix typo in LoomConsumerFactoryTest class name
=> fix typo in LoomConsumerFactoryTest class name
